Add local homme memory to AD mem buffer
E3SM-Project/scream pull request #1080
Opened 2021-06-22 18:29 UTC by tcclevenger

Use AD mem buffer for local Homme views.

Two parts: 
1. Changing Homme code to allow for partial construction of Functors, i.e., construct Functors with minimal information to get the requested buffer size, then setup the rest of the Functors before use (and after all info is available). This should not alter any Homme tests, only add additional options for the AD.
2. Use the AD mem buffer in `atmosphere_dynamics.cpp`. We hook into the `FunctorBuffersManager` to query to amount of memory requested, and provide the `FunctorBuffersManager` with memory (instead of it allocating itself).

2021-06-22 18:40 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-06-22 18:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1540</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1516</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1063</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: tcclevenger/homme_ad_mem_buffer</li>
    <li>SHA: 7d2179f3375c635af669671fbca558d2fd5fbf13</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: tcclevenger
</details>

2021-06-22 19:32 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1540</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1516</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1063</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 1540</b> (click to expand)
</summary>
<pre>
<code>
61/80 Test #47: p3_tests_ut_np1_omp12 ..................   Passed    1.76 sec
      Start 48: p3_tests_ut_np1_omp13
62/80 Test #48: p3_tests_ut_np1_omp13 ..................   Passed    2.99 sec
      Start 49: p3_tests_ut_np1_omp14
63/80 Test #49: p3_tests_ut_np1_omp14 ..................   Passed    3.01 sec
      Start 50: p3_tests_ut_np1_omp15
64/80 Test #50: p3_tests_ut_np1_omp15 ..................   Passed    2.99 sec
      Start 51: p3_tests_ut_np1_omp16
65/80 Test #51: p3_tests_ut_np1_omp16 ..................   Passed    2.99 sec
      Start 52: p3_run_and_cmp_cxx_ut_np1_omp16
66/80 Test #52: p3_run_and_cmp_cxx_ut_np1_omp16 ........   Passed    4.42 sec
      Start 53: p3_run_and_cmp_f90_ut_np1_omp16
67/80 Test #53: p3_run_and_cmp_f90_ut_np1_omp16 ........   Passed    0.20 sec
      Start 61: shoc_tests_ut_np1_omp6
68/80 Test #61: shoc_tests_ut_np1_omp6 .................   Passed    0.46 sec
      Start 62: shoc_tests_ut_np1_omp7
69/80 Test #62: shoc_tests_ut_np1_omp7 .................   Passed    0.47 sec
      Start 63: shoc_tests_ut_np1_omp8
70/80 Test #63: shoc_tests_ut_np1_omp8 .................   Passed    0.47 sec
      Start 64: shoc_tests_ut_np1_omp9
71/80 Test #64: shoc_tests_ut_np1_omp9 .................   Passed    0.47 sec
      Start 65: shoc_tests_ut_np1_omp10
72/80 Test #65: shoc_tests_ut_np1_omp10 ................   Passed    0.47 sec
      Start 66: shoc_tests_ut_np1_omp11
73/80 Test #66: shoc_tests_ut_np1_omp11 ................   Passed    0.46 sec
      Start 67: shoc_tests_ut_np1_omp12
74/80 Test #67: shoc_tests_ut_np1_omp12 ................   Passed    0.46 sec
      Start 68: shoc_tests_ut_np1_omp13
75/80 Test #68: shoc_tests_ut_np1_omp13 ................   Passed    0.57 sec
      Start 69: shoc_tests_ut_np1_omp14
76/80 Test #69: shoc_tests_ut_np1_omp14 ................   Passed    0.59 sec
      Start 70: shoc_tests_ut_np1_omp15
77/80 Test #70: shoc_tests_ut_np1_omp15 ................   Passed    0.59 sec
      Start 71: shoc_tests_ut_np1_omp16
78/80 Test #71: shoc_tests_ut_np1_omp16 ................   Passed    0.59 sec
      Start 72: shoc_run_and_cmp_cxx_ut_np1_omp16
79/80 Test #72: shoc_run_and_cmp_cxx_ut_np1_omp16 ......   Passed    0.06 sec
      Start 73: shoc_run_and_cmp_f90_ut_np1_omp16
80/80 Test #73: shoc_run_and_cmp_f90_ut_np1_omp16 ......   Passed    0.10 sec

100% tests passed, 0 tests failed out of 80

Label Time Summary:
cld_fraction    =   0.61 sec*proc (1 test)
driver          =   5.54 sec*proc (3 tests)
dynamics        =   4.02 sec*proc (1 test)
p3              = 397.90 sec*proc (19 tests)
physics         = 404.91 sec*proc (24 tests)
rrtmgp          =   3.86 sec*proc (3 tests)
shoc            =   2.54 sec*proc (1 test)

Total Test time (real) =  56.23 sec
===============================================================================
Testing '7d2179f3375c635af669671fbca558d2fd5fbf13' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 12-23 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=12 CTEST_PARALLEL_LEVEL=12 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/1540/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/1540/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/1540/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/1540/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master [...]

2021-06-22 23:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1541</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1517</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1064</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: tcclevenger/homme_ad_mem_buffer</li>
    <li>SHA: 7d2179f3375c635af669671fbca558d2fd5fbf13</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: tcclevenger
</details>

2021-06-23 00:20 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1541</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1517</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1064</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7d2179f3375c635af669671fbca558d2fd5fbf13</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2021-06-23 00:21 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2021-06-23 00:21 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-06-23 12:50 UTC, tcclevenger commented
@bartgol Test have passed. Fail earlier seemed to be an aborted test and nothing wrong with the new code.

2021-06-23 18:32 UTC, bartgol approved these changes

2021-06-23 18:33 UTC, bartgol requested changes
Sorry, I accidentally clicked approve earlier. I think you need to fix the optional input issue.

2021-06-23 18:52 UTC, tcclevenger commented on components/homme/src/theta-l_kokkos/prim_driver_mod.F90
> +    if (.not. present(allocate_buffer)) allocate_buffer = logical(.true.,c_bool)
I went with option 2). Seemed least involved.

2021-06-23 18:53 UTC, bartgol approved these changes

2021-06-23 19:20 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2021-06-23 19:21 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-06-23 19:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1550</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1525</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1072</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: tcclevenger/homme_ad_mem_buffer</li>
    <li>SHA: b79d5882e9686647b0b5d3b7a857046f3a85aeca</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: tcclevenger
</details>

2021-06-23 20:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1550</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1525</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1072</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;Atmosphere Driver;homme</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1080</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>tcclevenger/homme_ad_mem_buffer</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b79d5882e9686647b0b5d3b7a857046f3a85aeca</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ab527278ab020060513f64a0e146ef0a93aee169</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2021-06-23 20:02 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ bartgol ]!

2021-06-23 20:02 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2021-06-23 20:02 UTC, merged

2021-06-23 20:02 UTC, E3SM-Autotester commented
Merge on Pull Request# 1080: IS A SUCCESS - Pull Request successfully merged