Only compute SW radiative fluxes for daytime columns
E3SM-Project/scream pull request #1129
Opened 2021-07-26 23:08 UTC by brhillman

RRTMGP expects inputs to the shortwave (SW) solvers to be daytime only. Thus, no checks are made that the cosine of the solar zenith angle is greater than 0 (that the sun is above the horizon). Thus, floating point exceptions are encountered if nighttime columns are passed, due to division by the cosine of the solar zenith angle in the RRTMGP codes. To prevent this, we need to subset the inputs to the SW code to contain only daytime columns, and then expand the outputs back to all columns (filling in zeros for the fluxes where columns are not sunlit). This is consistent with the EAM treatment. Fixes #1102

2021-07-26 23:09 UTC, brhillman commented
Added WIP flag until I test and debug on GPU.

2021-07-27 21:35 UTC, AaronDonahue requested changes
We will also want to reactivate the `shoc_cld_p3_rrtmgp` test once this PR goes in.  So we should remove the conditional at this line: https://github.com/E3SM-Project/scream/blob/master/components/scream/tests/coupled/shoc_cld_p3_rrtmgp/CMakeLists.txt#L19

On the same note, if the homme_physics fix goes in earlier than this PR we can remove the equivalent conditional in that CMakeLists.txt file.

2021-07-28 19:30 UTC, brhillman commented
Removed WIP flag since this is passing my local tests on Weaver with the new commits. @AaronDonahue I also removed the conditional around the coupled test for the autotester.

2021-07-28 19:40 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-07-28 19:43 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1689</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1656</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1203</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: brhillman/scream/rrtmgp-subset-daytime</li>
    <li>SHA: cca42cefed5b48ad01921b8782d88949b9b204e0</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: brhillman
</details>

2021-07-28 20:54 UTC, AaronDonahue requested changes

2021-07-28 20:54 UTC, AaronDonahue commented on components/scream/tests/coupled/shoc_cld_p3_rrtmgp/CMakeLists.txt
> +# Test atmosphere processes.
@brhillman , can you remove this flag for the `homme_shoc_cld_p3_rrtmgp` coupled test as well?

2021-07-28 20:59 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 1689</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 1656</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1203</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>physics;radiation</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1129</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>brhillman/scream/rrtmgp-subset-daytime</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cca42cefed5b48ad01921b8782d88949b9b204e0</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a0ec5aa97e8f8bfa5f545b1f36d1c78720883dbb</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2021-07-28 20:59 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2021-07-28 20:59 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-07-28 21:14 UTC, AaronDonahue approved these changes
Thanks for making this happen Ben.

2021-07-29 00:50 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ AaronDonahue ]!

2021-07-29 00:50 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2021-07-29 03:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2021-07-29 03:11 UTC, merged

2021-07-29 03:11 UTC, E3SM-Autotester commented
Merge on Pull Request# 1129: IS A SUCCESS - Pull Request successfully merged