SCREAM: add some fine-grain switches when testing with jenkins
E3SM-Project/scream pull request #1383
Opened 2022-01-27 00:25 UTC by bartgol

A couple of upgrades:

* Can skip scream standalone testing setting the `AT: Skip Stand-Alone Testing` on the PR
* Can set `SCREAMv0` or `SCREAMv1` PR labels to run CIME cases for v0 or v1 only, respectively. Useful when making changes that _for sure_ only affect one of the two. The `CIME` label is still supported for backward compatibility, and is equivalent to set both `SCREAMv0` and `SCREAMv1`.

@jgfouca I'm not sure how to test the new mods, other than trying to add the labels that trigger the new behaviors. I guess we can set/unset labels, and ask the AT to retest, to ensure this PR works. But maybe there's a way to use the scripts tests?

Probably separate topic: should we make v1 testing ON by default, and add a `AT: Skip v1 Testing` label instead? This PR keeps the default behavior the same as master (test SA scream, do not test CIME scream). But we should start thinking about whether these defaults need to change.

2022-01-27 02:14 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-01-27 02:53 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-01-27 13:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2591</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2512</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1951</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/fine-grain-jenkins</li>
    <li>SHA: 3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-01-27 13:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2591</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2512</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1951</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2591</b> (click to expand)
</summary>
<pre>
<code>
+ '[' 0 -eq 0 ']'
+ cd /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2591/scream/components/scream/scripts/jenkins/../..
+ source scripts/jenkins/blake_setup
++ module load python/3.8.8/gcc/10.2.0
+++ /usr/bin/modulecmd bash load python/3.8.8/gcc/10.2.0
++ eval BINUTILSROOT=/home/projects/x86-64/binutils/2.30.0 ';export' 'BINUTILSROOT;BINUTILS_ROOT=/home/projects/x86-64/binutils/2.30.0' ';export' 'BINUTILS_ROOT;BINUTILS_VERSION=2.30.0' ';export' 'BINUTILS_VERSION;CC=/home/projects/x86-64/gcc/10.2.0/bin/gcc' ';export' 'CC;CC_VENDOR=gcc' ';export' 'CC_VENDOR;CPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include' ';export' 'CPATH;CXX=/home/projects/x86-64/gcc/10.2.0/bin/g++' ';export' 'CXX;CXX_VENDOR=gcc' ';export' 'CXX_VENDOR;F77=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'F77;F90=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'F90;FC=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'FC;FC_VENDOR=gcc' ';export' 'FC_VENDOR;GCCPATH=/home/projects/x86-64/gcc/10.2.0' ';export' 'GCCPATH;GCC_PATH=/home/projects/x86-64/gcc/10.2.0' ';export' 'GCC_PATH;GCC_VERSION=10.2.0' ';export' 'GCC_VERSION;INCLUDE=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include' ';export' 'INCLUDE;LD_LIBRARY_PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/lib:/home/projects/x86-64/openssl/1.1.1j/lib:/home/projects/x86-64/gcc/10.2.0/lib64:/home/projects/x86-64/gcc/10.2.0/lib:/home/projects/x86-64/binutils/2.30.0/lib:/usr/lib/gcc/x86_64-redhat-linux/4.8.5:/usr/lib/gcc/x86_64-redhat-linux/4.8.3:/usr/lib/gcc/x86_64-redhat-linux/4.4.7' ';export' 'LD_LIBRARY_PATH;LIBRARY_PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/lib:/home/projects/x86-64/openssl/1.1.1j/lib:/home/projects/x86-64/gcc/10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0:/home/projects/x86-64/gcc/10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0:/home/projects/x86-64/gcc/10.2.0/lib64:/home/projects/x86-64/gcc/10.2.0/lib:/home/projects/x86-64/binutils/2.30.0/lib:/usr/lib/gcc/x86_64-redhat-linux/4.8.5:/usr/lib/gcc/x86_64-redhat-linux/4.8.3:/usr/lib/gcc/x86_64-redhat-linux/4.4.7' ';export' 'LIBRARY_PATH;LOADEDMODULES=binutils/2.30.0:gcc/10.2.0:openssl/1.1.1j:python/3.8.8/gcc/10.2.0' ';export' 'LOADEDMODULES;MANPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/share/man:/home/projects/x86-64/openssl/1.1.1j/share/man:/home/projects/x86-64/gcc/10.2.0/man:/home/projects/x86-64/binutils/2.30.0/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;OPENSSL_ROOT=/home/projects/x86-64/openssl/1.1.1j' ';export' 'OPENSSL_ROOT;OPENSSL_VERSION=1.1.1j' ';export' 'OPENSSL_VERSION;PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin:/home/projects/x86-64/openssl/1.1.1j/bin:/home/projects/x86-64/gcc/10.2.0/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/:/home/projects/x86-64/gcc/10.2.0/libexec/gcc/x86_64-unknown-linux-gnu/10.2.0/:/home/projects/x86-64/gcc/10.2.0/bin:/home/projects/x86-64/binutils/2.30.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin' ';export' 'PATH;PIP=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin/pip' ';export' 'PIP;PYTHON=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin/python' ';export' 'PYTHON;PYTHON_ROOT=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0' ';export' 'PYTHON_ROOT;PYTHON_VERSION=3.8.8' ';export' 'PYTHON_VERSION;_LMFILES_=/home/projects/x86-64/modulefiles/binutils/2.30.0:/home/projects/x86-64/modulefiles/gcc/10.2.0:/home/projects/x86-64/modulefiles/openssl/1.1.1j:/home/projects/x86-64-skylake/modulefiles/python/3.8.8/gcc/10.2.0' ';export' '_LMFILES_;'
+++ BINUTILSROOT=/home/projects/x86-64/binutils/2.30.0
+++ export BINUTILSROOT
+++ BINUTILS_ROOT=/home/projects/x86-64/binutils/2.30.0
+++ export BINUTILS_ROOT
+++ BINUTILS_VERSION=2.30.0
+++ export BINUTILS_VERSION
+++ CC=/home/projects/x86-64/gcc/10.2.0/bin/gcc
+++ export CC
+++ CC_VENDOR=gcc
+++ export CC_VENDOR
+++ CPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include
+++ export CPATH
+++ CX [...]

2022-01-27 17:44 UTC, jgfouca requested changes
I like these enhancements. I think this is a good opportunity for some additional cleanups. One thing I've wanted for a while is for any label that affects AT behavior to have an `AT: ` prefix. So `AT: CIME` instead of just `CIME`. 

One potential point of confusion is that, if I have both `CIME` and `SCREAMv1` labels, both v1 and v0 will be tested. Maybe we should get rid of `CIME` and just have the v0 and v1 labels.

I hate to say it, but this script is getting complicated enough that it might need some real testing. I can look into some options here... I have some ideas.

2022-01-31 21:58 UTC, jgfouca approved these changes

2022-02-01 01:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-02-01 02:09 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-01 09:03 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-01 14:37 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2628</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2541</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1973</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/fine-grain-jenkins</li>
    <li>SHA: 3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-01 15:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2628</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2541</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1973</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3823def8a49ec3eaacdd7d9f3fcf751c877e7c98</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d43f43586892e1b2999cd11940e010caf6c7249a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2628</b> (click to expand)
</summary>
<pre>
<code>
+ '[' 0 -eq 0 ']'
+ cd /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2628/scream/components/scream/scripts/jenkins/../..
+ source scripts/jenkins/blake_setup
++ module load python/3.8.8/gcc/10.2.0
+++ /usr/bin/modulecmd bash load python/3.8.8/gcc/10.2.0
++ eval BINUTILSROOT=/home/projects/x86-64/binutils/2.30.0 ';export' 'BINUTILSROOT;BINUTILS_ROOT=/home/projects/x86-64/binutils/2.30.0' ';export' 'BINUTILS_ROOT;BINUTILS_VERSION=2.30.0' ';export' 'BINUTILS_VERSION;CC=/home/projects/x86-64/gcc/10.2.0/bin/gcc' ';export' 'CC;CC_VENDOR=gcc' ';export' 'CC_VENDOR;CPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include' ';export' 'CPATH;CXX=/home/projects/x86-64/gcc/10.2.0/bin/g++' ';export' 'CXX;CXX_VENDOR=gcc' ';export' 'CXX_VENDOR;F77=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'F77;F90=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'F90;FC=/home/projects/x86-64/gcc/10.2.0/bin/gfortran' ';export' 'FC;FC_VENDOR=gcc' ';export' 'FC_VENDOR;GCCPATH=/home/projects/x86-64/gcc/10.2.0' ';export' 'GCCPATH;GCC_PATH=/home/projects/x86-64/gcc/10.2.0' ';export' 'GCC_PATH;GCC_VERSION=10.2.0' ';export' 'GCC_VERSION;INCLUDE=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include' ';export' 'INCLUDE;LD_LIBRARY_PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/lib:/home/projects/x86-64/openssl/1.1.1j/lib:/home/projects/x86-64/gcc/10.2.0/lib64:/home/projects/x86-64/gcc/10.2.0/lib:/home/projects/x86-64/binutils/2.30.0/lib:/usr/lib/gcc/x86_64-redhat-linux/4.8.5:/usr/lib/gcc/x86_64-redhat-linux/4.8.3:/usr/lib/gcc/x86_64-redhat-linux/4.4.7' ';export' 'LD_LIBRARY_PATH;LIBRARY_PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/lib:/home/projects/x86-64/openssl/1.1.1j/lib:/home/projects/x86-64/gcc/10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0:/home/projects/x86-64/gcc/10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0:/home/projects/x86-64/gcc/10.2.0/lib64:/home/projects/x86-64/gcc/10.2.0/lib:/home/projects/x86-64/binutils/2.30.0/lib:/usr/lib/gcc/x86_64-redhat-linux/4.8.5:/usr/lib/gcc/x86_64-redhat-linux/4.8.3:/usr/lib/gcc/x86_64-redhat-linux/4.4.7' ';export' 'LIBRARY_PATH;LOADEDMODULES=binutils/2.30.0:gcc/10.2.0:openssl/1.1.1j:python/3.8.8/gcc/10.2.0' ';export' 'LOADEDMODULES;MANPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/share/man:/home/projects/x86-64/openssl/1.1.1j/share/man:/home/projects/x86-64/gcc/10.2.0/man:/home/projects/x86-64/binutils/2.30.0/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;OPENSSL_ROOT=/home/projects/x86-64/openssl/1.1.1j' ';export' 'OPENSSL_ROOT;OPENSSL_VERSION=1.1.1j' ';export' 'OPENSSL_VERSION;PATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin:/home/projects/x86-64/openssl/1.1.1j/bin:/home/projects/x86-64/gcc/10.2.0/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/:/home/projects/x86-64/gcc/10.2.0/libexec/gcc/x86_64-unknown-linux-gnu/10.2.0/:/home/projects/x86-64/gcc/10.2.0/bin:/home/projects/x86-64/binutils/2.30.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin' ';export' 'PATH;PIP=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin/pip' ';export' 'PIP;PYTHON=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/bin/python' ';export' 'PYTHON;PYTHON_ROOT=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0' ';export' 'PYTHON_ROOT;PYTHON_VERSION=3.8.8' ';export' 'PYTHON_VERSION;_LMFILES_=/home/projects/x86-64/modulefiles/binutils/2.30.0:/home/projects/x86-64/modulefiles/gcc/10.2.0:/home/projects/x86-64/modulefiles/openssl/1.1.1j:/home/projects/x86-64-skylake/modulefiles/python/3.8.8/gcc/10.2.0' ';export' '_LMFILES_;'
+++ BINUTILSROOT=/home/projects/x86-64/binutils/2.30.0
+++ export BINUTILSROOT
+++ BINUTILS_ROOT=/home/projects/x86-64/binutils/2.30.0
+++ export BINUTILS_ROOT
+++ BINUTILS_VERSION=2.30.0
+++ export BINUTILS_VERSION
+++ CC=/home/projects/x86-64/gcc/10.2.0/bin/gcc
+++ export CC
+++ CC_VENDOR=gcc
+++ export CC_VENDOR
+++ CPATH=/home/projects/x86-64-skylake/python/3.8.8/gcc/10.2.0/include:/home/projects/x86-64/openssl/1.1.1j/include:/home/projects/x86-64/binutils/2.30.0/include
+++ export CPATH
+++ CX [...]

2022-02-07 16:53 UTC, AaronDonahue commented
@bartgol , it looks like this PR is basically ready, except it fails with a DIFF in the SCREAMv1 test on mappy-cime.  Why would these changes make a DIFF?  Is it possible we just need to rebase and retest?

2022-02-07 18:43 UTC, bartgol commented
It's likely a matter of rebase. Let me update the branch.

2022-02-07 19:24 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-07 19:25 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2706</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2612</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2030</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/fine-grain-jenkins</li>
    <li>SHA: 77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-07 20:20 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2706</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2612</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2030</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>SCREAMv0;SCREAMv1;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1383</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/fine-grain-jenkins</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77100fc56fdabe1c8c0b46a83b0d90d1b4553c2e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3c552c066ff8a99d37045b28a1bc84531d6e6936</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2022-02-07 20:20 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2022-02-07 20:20 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-07 20:51 UTC, jgfouca approved these changes

2022-02-07 21:25 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jgfouca ]!

2022-02-07 21:25 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - AutoMerge IS ENABLED, but the Label AT: AUTOMERGE is not set.  Either set Label AT: AUTOMERGE or manually merge the PR...

2022-02-07 22:38 UTC, merged