Use native ctest features to ensure fails do happen when they should
E3SM-Project/scream pull request #1387
Opened 2022-01-27 21:47 UTC by bartgol

CMake/CTest offers a property for tests, `WILL_FAIL`, which makes the ctest test pass if the underlying test fails (a negation of the test outcome, if you will).

We can use this feature to ensure that we get failures with, e.g., OOB access in kokkos views. We do still need to use scripts-tests to detect a build failure, but any runtime failure can be tested with ctest native feature.

I haven't added a similar test for p3 baseline check. The way it is currently implemented, we would have to build p3 twice, which can be expensive on GPU archs. @jgfouca what would you think if I removed

```
#if defined(SCREAM_FORCE_RUN_DIFF) || defined(SCREAM_FORCE_RUN_DIFF_BFB_UNIT)
        precip_liq_surf *= 2;
#endif
```
from `p3_rain_sed_impl.hpp`, and instead do something similar in p3_run_and_cmp.cpp, like
```
  #if defined(SCREAM_FORCE_RUN_DIFF_BFB_UNIT)
      const auto num = std::abs(a[i] - b[i]);
  #else
      const auto num = std::abs(a[i]*1.2 - b[i]);
  #endif
```
and something similar in a p3 unit test? That way we could ensure diff and baseline diff failures happen during any normal test run (not just scripts tests runs).

2022-01-27 22:10 UTC, jgfouca requested changes
I like the general idea that we should prefer ctests over scripts-tests where it makes sense. That said, I have some concerns here.

Let's take the valgrind test. There are a lot of layers of code between `test-all-scream ... -t valg` and the cmake code you added to `fail_check/CMakeLists.txt`. If those layers don't work correctly, then this approach will not detect it. For example, if there is a problem in test-all-scream and `-t valg` makes a build that does not enable EKAT_ENABLE_VALGRIND, we would appear to get 100% PASS even though there's problem.

In other words, the tests you removed test both the scripts infrastructure and the core SCREAM cmake, while the tests you added only test core SCREAM.

On the other hand, I see the problem with the scripts-tests is that test-all-scream can pass/fail for any reason, not necessarily the thing we think we are testing.

Not sure what the best approach is here... I suppose the most-thorough would keep the scripts-tests and actually test the output coming from test-all-scream to make sure the reason for the pass/fail is what we think it should be.

2022-01-27 22:19 UTC, bartgol commented
That's a good point. Perhaps we can use scripts-test to ensure that some key CMake variables are set (inspecting CMakeCache.txt, for instance). If those are set, then whether or not testing works can be handled inside cmake.

We could actually use this paradigm for more than just valg. E.g., to ensure that `-t opt` yields CMAKE_BUILD_TYPE=RELEASE in the cache (that is, the `-t opt` flag is doing what we wanted).

So I see 3 layers of things to test:
- verify that test-all can generate the correct cmake configuration
- verify that a certain cmake config yields ctest pass/fails where we expect
- verify that test-all correctly picks up ctest's config/build/run exit code

The first and latter must be done with scripts-tests. But the middle one can (should?) be done internally with cmake/ctest features.

2022-01-27 22:21 UTC, jgfouca commented
@bartgol , that's a good plan.

2022-01-28 03:30 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-01-28 04:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2599</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2518</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1957</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-01-28 04:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has commited a change to the PR before testing completed.  The original testing SHA = 583cd7dd4c54e5c6d7debc4e6d20822b576b2aed Does not match the current commit SHA = 9968cc3d07c46962a5b93e40b8031728c61faa2e.  The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

2022-01-28 04:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2599</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2518</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1957</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>583cd7dd4c54e5c6d7debc4e6d20822b576b2aed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2599</b> (click to expand)
</summary>
<pre>
<code>
182/187 Test  #96: shoc_tests_ut_np1_omp13 .......................   Passed    2.12 sec
        Start  97: shoc_tests_ut_np1_omp14
183/187 Test  #97: shoc_tests_ut_np1_omp14 .......................   Passed    2.03 sec
        Start  98: shoc_tests_ut_np1_omp15
184/187 Test  #98: shoc_tests_ut_np1_omp15 .......................   Passed    2.12 sec
        Start  99: shoc_tests_ut_np1_omp16
185/187 Test  #99: shoc_tests_ut_np1_omp16 .......................   Passed    2.02 sec
        Start 100: shoc_run_and_cmp_cxx_ut_np1_omp16
186/187 Test #100: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.24 sec
        Start 101: shoc_run_and_cmp_f90_ut_np1_omp16
187/187 Test #101: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.51 sec

100% tests passed, 0 tests failed out of 187

Label Time Summary:
cld             = 4157.22 sec*proc (28 tests)
cld_fraction    =   0.82 sec*proc (1 test)
driver          = 2675.19 sec*proc (23 tests)
dynamics        = 2831.70 sec*proc (29 tests)
fail            = 818.88 sec*proc (20 tests)
io              = 221.48 sec*proc (12 tests)
p3              = 6216.62 sec*proc (70 tests)
physics         = 7400.79 sec*proc (95 tests)
rrtmgp          = 4857.23 sec*proc (38 tests)
shoc            = 4256.56 sec*proc (35 tests)
spa             = 1599.89 sec*proc (26 tests)

Total Test time (real) = 409.32 sec
===============================================================================
Testing '701d61435c0df5bda7b4bee66e9b2f66aa1d9cc8' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/release/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/ctest-build/release
===============================================================================
Testing '701d61435c0df5bda7b4bee66e9b2f66aa1d9cc8' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2599/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNING [...]

2022-01-28 04:56 UTC, bartgol commented
I think I reached a good status. I was able to do things a bit more cleanly (wihtout, e.g., the need to create fake baselines), and I think I lowered the scripts tests runtime quite a bit. I was running on mappy, while mappy_e3sm_master was running (I taskset-ed the scripts test on cores that jenkins was using less often, which btw caused failures of the spread tests), and I ran scripts-tests in about 10 minutes or so (I didn't run with time, so I had to manually keep an eye on the process with top/ps). From jenkins, I see that our nightly scripts tests take about 30min to run, so this might be a good improvement.

Main ingredients of the speedup:
- Run most of the tests to detect failures during normal builds, as additional tests (little compilation/testing overhead)
- Avoid building _all_ of the src folder and most of the test folder if SCREAM_FAKE_ONLY is in the env
- Run some of the scripts tests with SCREAM_FAKE_ONLY on and/or test-all-scream options such as `--no-tests` or `--config-only` (the latter, a new one), to speed up each call to test-all. E.g, when testing baseline handling logic, we do not need to actually build baselines; we only need test-all to run its logic to see if new baselines are needed, and if, so, to generate the baselines dir, with the baseline_sha file. Building/running tests/baselines execs is not needed.
- When running test_full (the most expensive test), add the `-p` flag to test-all, to squeeze the last drop of perf out of the CPU cores. Note: I did not have this option when I timed scripts-tests on mappy, so performance might be even a bit better.

@jgfouca I have two questions for you:
- While moving the "FORCE_DIFF" tests from scripts-tests to inside our normal cmake builds, I did not move the tests that check no diff are triggered in opt mode. I did not quite get that test. Why shouldn't diffs trigger a fail in release mode?
- Do we really need to "really" run test-all-scream in test_full? What are we actually testing? We should not care whether tests pass or not, since that's a responsibility of the normal nightlies to check. In scripts-tests we simply want to ensure the scripts are doing what we think they are. What's the goal of running a real (i.e., no FAKE) test-all-scream?

2022-01-28 05:54 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-01-28 06:34 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-01-28 10:49 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2607</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2521</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1958</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 0f067faf1381fb235bd87a6e1aae15f0592a750e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-01-28 12:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2607</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2521</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1958</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2607</b> (click to expand)
</summary>
<pre>
<code>
182/187 Test  #96: shoc_tests_ut_np1_omp13 .......................   Passed    2.12 sec
        Start  97: shoc_tests_ut_np1_omp14
183/187 Test  #97: shoc_tests_ut_np1_omp14 .......................   Passed    1.93 sec
        Start  98: shoc_tests_ut_np1_omp15
184/187 Test  #98: shoc_tests_ut_np1_omp15 .......................   Passed    1.93 sec
        Start  99: shoc_tests_ut_np1_omp16
185/187 Test  #99: shoc_tests_ut_np1_omp16 .......................   Passed    2.01 sec
        Start 100: shoc_run_and_cmp_cxx_ut_np1_omp16
186/187 Test #100: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.10 sec
        Start 101: shoc_run_and_cmp_f90_ut_np1_omp16
187/187 Test #101: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.51 sec

100% tests passed, 0 tests failed out of 187

Label Time Summary:
cld             = 4221.71 sec*proc (28 tests)
cld_fraction    =   0.82 sec*proc (1 test)
driver          = 2657.44 sec*proc (23 tests)
dynamics        = 2697.37 sec*proc (29 tests)
fail            = 749.14 sec*proc (20 tests)
io              = 137.42 sec*proc (12 tests)
p3              = 6240.67 sec*proc (70 tests)
physics         = 7479.93 sec*proc (95 tests)
rrtmgp          = 4951.76 sec*proc (38 tests)
shoc            = 4299.39 sec*proc (35 tests)
spa             = 1618.91 sec*proc (26 tests)

Total Test time (real) = 398.58 sec
===============================================================================
Testing '091c9b298116a31ea053fcb536fd77594a5f09e6' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/full_sp_debug/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/ctest-build/full_sp_debug
===============================================================================
Testing '091c9b298116a31ea053fcb536fd77594a5f09e6' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2607/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release -DEKAT_DISA [...]

2022-01-28 16:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2611</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2525</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1962</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 0f067faf1381fb235bd87a6e1aae15f0592a750e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-01-28 17:20 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2611</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2525</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1962</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2611</b> (click to expand)
</summary>
<pre>
<code>
182/187 Test  #96: shoc_tests_ut_np1_omp13 .......................   Passed    2.15 sec
        Start  97: shoc_tests_ut_np1_omp14
183/187 Test  #97: shoc_tests_ut_np1_omp14 .......................   Passed    1.94 sec
        Start  98: shoc_tests_ut_np1_omp15
184/187 Test  #98: shoc_tests_ut_np1_omp15 .......................   Passed    1.93 sec
        Start  99: shoc_tests_ut_np1_omp16
185/187 Test  #99: shoc_tests_ut_np1_omp16 .......................   Passed    1.94 sec
        Start 100: shoc_run_and_cmp_cxx_ut_np1_omp16
186/187 Test #100: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.09 sec
        Start 101: shoc_run_and_cmp_f90_ut_np1_omp16
187/187 Test #101: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.44 sec

100% tests passed, 0 tests failed out of 187

Label Time Summary:
cld             = 4099.93 sec*proc (28 tests)
cld_fraction    =   0.72 sec*proc (1 test)
driver          = 2616.28 sec*proc (23 tests)
dynamics        = 2653.78 sec*proc (29 tests)
fail            = 758.00 sec*proc (20 tests)
io              = 123.65 sec*proc (12 tests)
p3              = 6069.81 sec*proc (70 tests)
physics         = 7359.02 sec*proc (95 tests)
rrtmgp          = 4832.60 sec*proc (38 tests)
shoc            = 4191.73 sec*proc (35 tests)
spa             = 1762.93 sec*proc (26 tests)

Total Test time (real) = 398.53 sec
===============================================================================
Testing 'fd5dbf103f821a5400fb30be495c3ef532ea0a32' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/full_sp_debug/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/ctest-build/full_sp_debug
===============================================================================
Testing 'fd5dbf103f821a5400fb30be495c3ef532ea0a32' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2611/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release -DEKAT_DISA [...]

2022-01-28 23:28 UTC, jgfouca commented
@bartgol 

> While moving the "FORCE_DIFF" tests from scripts-tests to inside our normal cmake builds, I did not recreate the tests that check no diff are triggered in opt mode. I did not quite get that test. Why shouldn't diffs trigger a fail in release mode?

Things are not BFB between fortran and cxx in release mode.

> Do we really need to "really" run test-all-scream in test_full? What are we actually testing? We should not care whether tests pass or not, since that's a responsibility of the normal nightlies to check. In scripts-tests we simply want to ensure the scripts are doing what we think they are. What's the goal of running a real (i.e., no FAKE) test-all-scream?

It looks like test_full is used to hit some use cases:
```
    CMDS_TO_TEST = [
        "./test-all-scream -m $machine -b HEAD -k",
        "./test-all-scream -m $machine -b HEAD -k -t dbg",
        "./test-all-scream --baseline-dir $results -c EKAT_DISABLE_TPL_WARNINGS=ON -i -m $machine --submit --dry-run", # always dry run                                                                                                           
    ]
```
The test runs these commands and stores all output which can then serve as a baseline to check against. This is to check that behavior is exactly identical to the version used in the baseline, at least as far as it can be determined from the output.

2022-01-31 16:19 UTC, jgfouca requested changes
Looks good, just one minor request.

2022-01-31 16:19 UTC, jgfouca commented on components/scream/scripts/scripts-tests
> +                            self._machine, dry_run=False)
We should test that `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK` is on.

2022-01-31 18:50 UTC, jgfouca commented
@bartgol most of the work is in the base class. Look for compare/generate in the code.

2022-02-03 01:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-02-03 01:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2651</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2562</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1990</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 0f067faf1381fb235bd87a6e1aae15f0592a750e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-03 01:50 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2651</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2562</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1990</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: RETEST;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2651</b> (click to expand)
</summary>
<pre>
<code>
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
182/187 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
183/187 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
184/187 Test #119: homme_standalone_ut_np1_omp1 ..................   Passed  609.99 sec
        Start 123: homme_np1_vs_np2_bfb
185/187 Test #123: homme_np1_vs_np2_bfb ..........................   Passed    0.10 sec
        Start 124: homme_np1_vs_np3_bfb
186/187 Test #124: homme_np1_vs_np3_bfb ..........................   Passed    0.07 sec
        Start 125: homme_np1_vs_np4_bfb
187/187 Test #125: homme_np1_vs_np4_bfb ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 187

Label Time Summary:
cld             = 5831.90 sec*proc (28 tests)
cld_fraction    =   0.80 sec*proc (1 test)
driver          = 6979.85 sec*proc (23 tests)
dynamics        = 7013.25 sec*proc (29 tests)
fail            = 683.70 sec*proc (20 tests)
io              = 117.22 sec*proc (12 tests)
p3              = 7563.56 sec*proc (70 tests)
physics         = 8670.21 sec*proc (95 tests)
rrtmgp          = 6527.41 sec*proc (38 tests)
shoc            = 5895.44 sec*proc (35 tests)
spa             = 1430.57 sec*proc (26 tests)

Total Test time (real) = 610.54 sec
===============================================================================
Testing '64e4e076f69a2fb2649f2a3135fc31a589632cce' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/full_sp_debug/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/ctest-build/full_sp_debug
===============================================================================
Testing '64e4e076f69a2fb2649f2a3135fc31a589632cce' for test 'full_debug'
===============================================================================
RUN: taskset -c 0-23 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/ctest-build/full_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/ctest-build/full_debug -DBUILD_NAME_MOD=full_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2651/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf [...]

2022-02-03 07:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-03 12:15 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2660</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2569</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1996</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 0f067faf1381fb235bd87a6e1aae15f0592a750e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-03 13:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2660</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2569</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 1996</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>0f067faf1381fb235bd87a6e1aae15f0592a750e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>20611ef5a60014c2ff7dc067e46159b2c8143a7a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2660</b> (click to expand)
</summary>
<pre>
<code>
[ 94%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_diag_second_shoc_moments_tests.cpp.o
[ 94%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_pblintd_cldcheck_tests.cpp.o
[ 94%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_compute_shoc_vapor_tests.cpp.o
[ 94%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_update_prognostics_implicit_tests.cpp.o
[ 94%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_main_tests.cpp.o
[ 95%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_pblintd_height_tests.cpp.o
[ 96%] Linking CXX executable p3_tests
[ 96%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_vd_shoc_decomp_and_solve_tests.cpp.o
[ 96%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_pblintd_surf_temp_tests.cpp.o
[ 96%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_pblintd_check_pblh_tests.cpp.o
[ 97%] Building CXX object src/physics/shoc/tests/CMakeFiles/shoc_tests.dir/shoc_pblintd_tests.cpp.o
[ 97%] Linking CXX executable output_restart_test
[ 97%] Linking CXX executable shoc_tests
[ 97%] Linking CXX static library libscream_control.a
[ 97%] Built target p3_tests
[ 97%] Built target output_restart_test
[ 97%] Built target scream_control
[ 97%] Built target shoc_tests
gmake: *** [all] Error 2

CMake Error at /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2660/scream/components/scream/cmake/ctest_script.cmake:79 (message):
  Test had fails


.........*.....**.*..*.***........*..*.*.  Size: 100K
    **...***...*..*...*...*.*.*..*.......*.****....  Size: 99K
    ........**.**.........................  Size: 99K
FATAL: command execution failed
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2872)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3367)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
Caused: java.io.IOException: Backing channel 'blake' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:216)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:286)
	at com.sun.proxy.$Proxy66.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1213)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1205)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:194)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:144)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
	at hudson.model.Build$BuildExecution.build(Build.java:198)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:432)
FATAL: Unable to delete script file /tmp/jenkins495263097041520090.sh
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2872)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3367)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectIn [...]

2022-02-03 16:56 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-03 17:36 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-03 23:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2022-02-04 01:37 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-04 02:31 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2674</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2582</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2006</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 034c448497af1dcd94aaf5df2dade9688769fc8d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-04 03:04 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2674</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2582</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2006</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2674</b> (click to expand)
</summary>
<pre>
<code>
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
185/188 Test #120: homme_standalone_ut_np1_omp1 ..................   Passed  610.38 sec
        Start 124: homme_np1_vs_np2_bfb
186/188 Test #124: homme_np1_vs_np2_bfb ..........................   Passed    0.08 sec
        Start 125: homme_np1_vs_np3_bfb
187/188 Test #125: homme_np1_vs_np3_bfb ..........................   Passed    0.07 sec
        Start 126: homme_np1_vs_np4_bfb
188/188 Test #126: homme_np1_vs_np4_bfb ..........................   Passed    0.08 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 5815.97 sec*proc (28 tests)
cld_fraction    =   0.85 sec*proc (1 test)
driver          = 6951.76 sec*proc (23 tests)
dynamics        = 6987.99 sec*proc (29 tests)
fail            = 700.53 sec*proc (20 tests)
io              = 126.84 sec*proc (12 tests)
p3              = 7576.69 sec*proc (70 tests)
physics         = 8695.25 sec*proc (95 tests)
rrtmgp          = 6501.20 sec*proc (38 tests)
shoc            = 5883.89 sec*proc (35 tests)
spa             = 1443.35 sec*proc (26 tests)

Total Test time (real) = 611.95 sec
===============================================================================
Testing '034c448497af1dcd94aaf5df2dade9688769fc8d' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/full_sp_debug/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/ctest-build/full_sp_debug
===============================================================================
Testing '034c448497af1dcd94aaf5df2dade9688769fc8d' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2674/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release  [...]

2022-02-04 08:02 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-04 14:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2686</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2592</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2012</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 034c448497af1dcd94aaf5df2dade9688769fc8d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-04 15:40 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2686</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2592</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2012</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>034c448497af1dcd94aaf5df2dade9688769fc8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2686</b> (click to expand)
</summary>
<pre>
<code>
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
185/188 Test #120: homme_standalone_ut_np1_omp1 ..................   Passed  631.17 sec
        Start 124: homme_np1_vs_np2_bfb
186/188 Test #124: homme_np1_vs_np2_bfb ..........................   Passed    0.08 sec
        Start 125: homme_np1_vs_np3_bfb
187/188 Test #125: homme_np1_vs_np3_bfb ..........................   Passed    0.07 sec
        Start 126: homme_np1_vs_np4_bfb
188/188 Test #126: homme_np1_vs_np4_bfb ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 6239.52 sec*proc (28 tests)
cld_fraction    =   0.80 sec*proc (1 test)
driver          = 7282.57 sec*proc (23 tests)
dynamics        = 7313.99 sec*proc (29 tests)
fail            = 688.39 sec*proc (20 tests)
io              = 118.32 sec*proc (12 tests)
p3              = 7980.40 sec*proc (70 tests)
physics         = 9118.35 sec*proc (95 tests)
rrtmgp          = 6949.21 sec*proc (38 tests)
shoc            = 6301.04 sec*proc (35 tests)
spa             = 1552.12 sec*proc (26 tests)

Total Test time (real) = 631.66 sec
===============================================================================
Testing '43d5fcad47bbfb6f0c9158ee1fdce479b47f8f0d' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake/full_sp_debug/data" '
FROM: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/ctest-build/full_sp_debug
===============================================================================
Testing '43d5fcad47bbfb6f0c9158ee1fdce479b47f8f0d' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2686/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release  [...]

2022-02-04 18:37 UTC, jgfouca approved these changes

2022-02-05 03:43 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-05 04:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-02-05 13:57 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2699</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2605</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2023</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: f58368a2fb86a54b4ada1e2230a9b6834ace19f1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-05 14:11 UTC, E3SM-Autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2022-02-05 14:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2700</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2606</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2024</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: f58368a2fb86a54b4ada1e2230a9b6834ace19f1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-05 15:35 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2700</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2606</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2024</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2700</b> (click to expand)
</summary>
<pre>
<code>
        Start  82: p3_run_and_cmp_cxx_fail_ut_np1_omp16
173/188 Test  #82: p3_run_and_cmp_cxx_fail_ut_np1_omp16 ..........   Passed    4.85 sec
        Start  96: shoc_tests_ut_np1_omp12
174/188 Test  #96: shoc_tests_ut_np1_omp12 .......................   Passed    2.19 sec
        Start  97: shoc_tests_ut_np1_omp13
175/188 Test  #97: shoc_tests_ut_np1_omp13 .......................   Passed    2.18 sec
        Start  98: shoc_tests_ut_np1_omp14
176/188 Test  #98: shoc_tests_ut_np1_omp14 .......................   Passed    1.96 sec
        Start  99: shoc_tests_ut_np1_omp15
177/188 Test  #99: shoc_tests_ut_np1_omp15 .......................   Passed    1.96 sec
        Start 100: shoc_tests_ut_np1_omp16
178/188 Test #100: shoc_tests_ut_np1_omp16 .......................   Passed    1.96 sec
        Start 101: shoc_run_and_cmp_cxx_ut_np1_omp16
179/188 Test #101: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.19 sec
        Start 102: shoc_run_and_cmp_f90_ut_np1_omp16
180/188 Test #102: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.45 sec
181/188 Test #182: homme_shoc_cld_spa_p3_rrtmgp_ut_np1_omp1 ......   Passed  519.79 sec
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
182/188 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.18 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
185/188 Test #120: homme_standalone_ut_np1_omp1 ..................   Passed  635.61 sec
        Start 124: homme_np1_vs_np2_bfb
186/188 Test #124: homme_np1_vs_np2_bfb ..........................   Passed    0.10 sec
        Start 125: homme_np1_vs_np3_bfb
187/188 Test #125: homme_np1_vs_np3_bfb ..........................   Passed    0.08 sec
        Start 126: homme_np1_vs_np4_bfb
188/188 Test #126: homme_np1_vs_np4_bfb ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 6265.91 sec*proc (28 tests)
cld_fraction    =   1.25 sec*proc (1 test)
driver          = 7312.57 sec*proc (23 tests)
dynamics        = 7340.79 sec*proc (29 tests)
fail            = 693.49 sec*proc (20 tests)
io              = 115.96 sec*proc (12 tests)
p3              = 8026.10 sec*proc (70 tests)
physics         = 9154.24 sec*proc (95 tests)
rrtmgp          = 6960.66 sec*proc (38 tests)
shoc            = 6329.39 sec*proc (35 tests)
spa             = 1548.75 sec*proc (26 tests)

Total Test time (real) = 636.26 sec
===============================================================================
Testing '11de648c60f1d5c4359c0a2017184e7680f9954c' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2700/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2700/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2700/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2700/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/blake [...]

2022-02-05 19:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2701</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2607</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2025</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: f58368a2fb86a54b4ada1e2230a9b6834ace19f1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-05 20:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2701</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2607</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2025</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2701</b> (click to expand)
</summary>
<pre>
<code>
172/188 Test  #95: shoc_tests_ut_np1_omp11 .......................   Passed    2.17 sec
        Start  96: shoc_tests_ut_np1_omp12
173/188 Test  #94: shoc_tests_ut_np1_omp10 .......................   Passed    2.19 sec
174/188 Test  #96: shoc_tests_ut_np1_omp12 .......................   Passed    2.13 sec
        Start  97: shoc_tests_ut_np1_omp13
175/188 Test  #97: shoc_tests_ut_np1_omp13 .......................   Passed    2.17 sec
        Start  98: shoc_tests_ut_np1_omp14
176/188 Test  #98: shoc_tests_ut_np1_omp14 .......................   Passed    1.96 sec
        Start  99: shoc_tests_ut_np1_omp15
177/188 Test  #99: shoc_tests_ut_np1_omp15 .......................   Passed    1.96 sec
        Start 100: shoc_tests_ut_np1_omp16
178/188 Test #100: shoc_tests_ut_np1_omp16 .......................   Passed    1.95 sec
        Start 101: shoc_run_and_cmp_cxx_ut_np1_omp16
179/188 Test #101: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.18 sec
        Start 102: shoc_run_and_cmp_f90_ut_np1_omp16
180/188 Test #102: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.45 sec
181/188 Test #182: homme_shoc_cld_spa_p3_rrtmgp_ut_np1_omp1 ......   Passed  517.99 sec
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
182/188 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.19 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
185/188 Test #120: homme_standalone_ut_np1_omp1 ..................   Passed  637.40 sec
        Start 124: homme_np1_vs_np2_bfb
186/188 Test #124: homme_np1_vs_np2_bfb ..........................   Passed    0.08 sec
        Start 125: homme_np1_vs_np3_bfb
187/188 Test #125: homme_np1_vs_np3_bfb ..........................   Passed    0.08 sec
        Start 126: homme_np1_vs_np4_bfb
188/188 Test #126: homme_np1_vs_np4_bfb ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 6227.18 sec*proc (28 tests)
cld_fraction    =   0.71 sec*proc (1 test)
driver          = 7246.69 sec*proc (23 tests)
dynamics        = 7275.54 sec*proc (29 tests)
fail            = 686.57 sec*proc (20 tests)
io              = 107.23 sec*proc (12 tests)
p3              = 7977.11 sec*proc (70 tests)
physics         = 9112.03 sec*proc (95 tests)
rrtmgp          = 6938.17 sec*proc (38 tests)
shoc            = 6287.83 sec*proc (35 tests)
spa             = 1535.03 sec*proc (26 tests)

Total Test time (real) = 637.94 sec
===============================================================================
Testing '37f9f10b43e258d3eeab3f522a09b32cbd69a304' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2701/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2701/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2701/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2701/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-a [...]

2022-02-06 00:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2702</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2608</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2026</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: f58368a2fb86a54b4ada1e2230a9b6834ace19f1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-06 01:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2702</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2608</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2026</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f58368a2fb86a54b4ada1e2230a9b6834ace19f1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2702</b> (click to expand)
</summary>
<pre>
<code>
172/188 Test  #94: shoc_tests_ut_np1_omp10 .......................   Passed    2.18 sec
173/188 Test  #95: shoc_tests_ut_np1_omp11 .......................   Passed    2.19 sec
        Start  96: shoc_tests_ut_np1_omp12
174/188 Test  #96: shoc_tests_ut_np1_omp12 .......................   Passed    2.16 sec
        Start  97: shoc_tests_ut_np1_omp13
175/188 Test  #97: shoc_tests_ut_np1_omp13 .......................   Passed    2.13 sec
        Start  98: shoc_tests_ut_np1_omp14
176/188 Test  #98: shoc_tests_ut_np1_omp14 .......................   Passed    1.94 sec
        Start  99: shoc_tests_ut_np1_omp15
177/188 Test  #99: shoc_tests_ut_np1_omp15 .......................   Passed    1.94 sec
        Start 100: shoc_tests_ut_np1_omp16
178/188 Test #100: shoc_tests_ut_np1_omp16 .......................   Passed    1.94 sec
        Start 101: shoc_run_and_cmp_cxx_ut_np1_omp16
179/188 Test #101: shoc_run_and_cmp_cxx_ut_np1_omp16 .............   Passed    1.17 sec
        Start 102: shoc_run_and_cmp_f90_ut_np1_omp16
180/188 Test #102: shoc_run_and_cmp_f90_ut_np1_omp16 .............   Passed    0.46 sec
181/188 Test #182: homme_shoc_cld_spa_p3_rrtmgp_ut_np1_omp1 ......   Passed  515.80 sec
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
182/188 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.51 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
185/188 Test #120: homme_standalone_ut_np1_omp1 ..................   Passed  628.16 sec
        Start 124: homme_np1_vs_np2_bfb
186/188 Test #124: homme_np1_vs_np2_bfb ..........................   Passed    0.08 sec
        Start 125: homme_np1_vs_np3_bfb
187/188 Test #125: homme_np1_vs_np3_bfb ..........................   Passed    0.07 sec
        Start 126: homme_np1_vs_np4_bfb
188/188 Test #126: homme_np1_vs_np4_bfb ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 6194.46 sec*proc (28 tests)
cld_fraction    =   0.82 sec*proc (1 test)
driver          = 7212.64 sec*proc (23 tests)
dynamics        = 7244.21 sec*proc (29 tests)
fail            = 696.50 sec*proc (20 tests)
io              = 117.37 sec*proc (12 tests)
p3              = 7936.77 sec*proc (70 tests)
physics         = 9087.09 sec*proc (95 tests)
rrtmgp          = 6913.25 sec*proc (38 tests)
shoc            = 6265.16 sec*proc (35 tests)
spa             = 1500.13 sec*proc (26 tests)

Total Test time (real) = 628.66 sec
===============================================================================
Testing '7bbd12acc71fada1a20a3a92cdf905f7963be17e' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2702/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2702/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2702/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2702/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATHS=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATHS=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-a [...]

2022-02-07 16:40 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-07 16:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2703</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e6fd574fd1ceca9a5b0b74e8d4ce9f5107376dc8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2609</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e6fd574fd1ceca9a5b0b74e8d4ce9f5107376dc8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2027</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e6fd574fd1ceca9a5b0b74e8d4ce9f5107376dc8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: e6fd574fd1ceca9a5b0b74e8d4ce9f5107376dc8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-07 18:39 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-02-07 18:40 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2705</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>638a9496fe0862bbb44c5ca9bd58391d6635fb93</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2611</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>638a9496fe0862bbb44c5ca9bd58391d6635fb93</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2029</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;scripts</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1387</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/test-failures-with-ctest</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>638a9496fe0862bbb44c5ca9bd58391d6635fb93</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d4f0410072732440339dc01c0683de9bf4a08868</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/test-failures-with-ctest</li>
    <li>SHA: 638a9496fe0862bbb44c5ca9bd58391d6635fb93</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2022-02-07 19:21 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2022-02-07 19:21 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-07 20:44 UTC, jgfouca approved these changes

2022-02-07 21:26 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jgfouca ]!

2022-02-07 21:26 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2022-02-07 21:26 UTC, merged

2022-02-07 21:26 UTC, E3SM-Autotester commented
Merge on Pull Request# 1387: IS A SUCCESS - Pull Request successfully merged