Add ability to write diagnostic to file.
E3SM-Project/scream pull request #1496
Opened 2022-03-21 23:50 UTC by AaronDonahue

This commit will make it possible to request a diagnostic as output to file.  Each new diagnostic needs to be added to the register_diagnostics routine in order to be available to the scorpio_output class.  Requesting a diagnostic as output is as simple as adding the name that the diagnostic was registered under in the scorpio output YAML file.

An example can be found in the io_test which has been changed to also test for diagnostic output.

2022-03-22 00:21 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-03-22 03:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-03-22 13:03 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2966</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3a1aad0a0afec43683edc7a78fd24908f3586b43</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>5e79938aee1d4b6a76d544b4e066fa24f0d481e7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2860</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3a1aad0a0afec43683edc7a78fd24908f3586b43</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>5e79938aee1d4b6a76d544b4e066fa24f0d481e7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2227</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3a1aad0a0afec43683edc7a78fd24908f3586b43</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>5e79938aee1d4b6a76d544b4e066fa24f0d481e7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 3a1aad0a0afec43683edc7a78fd24908f3586b43</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-24 01:48 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-03-24 01:48 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-03-24 02:05 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2981</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2873</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2236</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-24 03:06 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2981</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2873</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2236</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2981</b> (click to expand)
</summary>
<pre>
<code>
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.57 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.37 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.34 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 469.40 sec*proc (28 tests)
cld_fraction    =   0.58 sec*proc (1 test)
diagnostics     =   0.68 sec*proc (1 test)
driver          = 299.85 sec*proc (23 tests)
dynamics        = 311.55 sec*proc (29 tests)
fail            = 196.59 sec*proc (18 tests)
io              =  55.87 sec*proc (12 tests)
p3              = 1105.95 sec*proc (70 tests)
physics         = 1262.34 sec*proc (95 tests)
rrtmgp          = 562.24 sec*proc (38 tests)
shoc            = 491.67 sec*proc (35 tests)
spa             = 206.50 sec*proc (27 tests)

Total Test time (real) =  76.83 sec
177/185 Test  #97: shoc_tests_omp16 ..............................   Passed    1.95 sec
178/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  456.49 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.10 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec
182/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  495.41 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.17 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6762.49 sec*proc (28 tests)
cld_fraction    =   0.79 sec*proc (1 test)
diagnostics     =   0.74 sec*proc (1 test)
driver          = 5439.62 sec*proc (23 tests)
dynamics        = 5472.78 sec*proc (29 tests)
fail            = 652.07 sec*proc (19 tests)
io              =  77.11 sec*proc (12 tests)
p3              = 8551.66 sec*proc (67 tests)
physics         = 9724.96 sec*proc (92 tests)
rrtmgp          = 7549.25 sec*proc (38 tests)
shoc            = 6811.68 sec*proc (35 tests)
spa             = 1550.64 sec*proc (27 tests)

Total Test time (real) = 579.81 sec
===============================================================================
Testing 'f70d67c26f6a9777b15d41a462329a18d60ce62a' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2981/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2981/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2981/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2981/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64 [...]

2022-03-24 08:03 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2984</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2876</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2238</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-24 10:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2984</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2876</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2238</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2984</b> (click to expand)
</summary>
<pre>
<code>
driver          = 319.73 sec*proc (23 tests)
dynamics        = 339.49 sec*proc (29 tests)
fail            = 196.90 sec*proc (18 tests)
io              =  96.64 sec*proc (12 tests)
p3              = 1180.02 sec*proc (70 tests)
physics         = 1363.11 sec*proc (95 tests)
rrtmgp          = 655.20 sec*proc (38 tests)
shoc            = 575.36 sec*proc (35 tests)
spa             = 264.73 sec*proc (27 tests)

Total Test time (real) =  83.23 sec
171/185 Test  #78: p3_tests_fail_omp15 ...........................   Passed    4.32 sec
        Start  79: p3_tests_fail_omp16
172/185 Test  #79: p3_tests_fail_omp16 ...........................   Passed    3.94 sec
        Start  93: shoc_tests_omp12
173/185 Test  #93: shoc_tests_omp12 ..............................   Passed    2.16 sec
        Start  94: shoc_tests_omp13
174/185 Test  #94: shoc_tests_omp13 ..............................   Passed    2.14 sec
        Start  95: shoc_tests_omp14
175/185 Test  #95: shoc_tests_omp14 ..............................   Passed    1.94 sec
        Start  96: shoc_tests_omp15
176/185 Test  #96: shoc_tests_omp15 ..............................   Passed    1.94 sec
        Start  97: shoc_tests_omp16
177/185 Test  #97: shoc_tests_omp16 ..............................   Passed    1.94 sec
178/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  458.05 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.18 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
182/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  512.01 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.09 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 7006.68 sec*proc (28 tests)
cld_fraction    =   1.63 sec*proc (1 test)
diagnostics     =   1.18 sec*proc (1 test)
driver          = 5551.38 sec*proc (23 tests)
dynamics        = 5585.76 sec*proc (29 tests)
fail            = 667.55 sec*proc (19 tests)
io              = 134.48 sec*proc (12 tests)
p3              = 8809.31 sec*proc (67 tests)
physics         = 10086.40 sec*proc (92 tests)
rrtmgp          = 7843.17 sec*proc (38 tests)
shoc            = 7069.20 sec*proc (35 tests)
spa             = 1716.22 sec*proc (27 tests)

Total Test time (real) = 600.41 sec
===============================================================================
Testing '05e203d87abe7ce12fb001491f7056ce65949338' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2984/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2984/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2984/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2984/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2 [...]

2022-03-24 14:57 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-03-24 19:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2990</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2882</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2243</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-24 20:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2990</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2882</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2243</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4befd26fb6be3b0cbc4085cf4598f25cc97e3a3e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 2990</b> (click to expand)
</summary>
<pre>
<code>
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.56 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.31 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.33 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 453.38 sec*proc (28 tests)
cld_fraction    =   0.56 sec*proc (1 test)
diagnostics     =   0.67 sec*proc (1 test)
driver          = 272.43 sec*proc (23 tests)
dynamics        = 284.70 sec*proc (29 tests)
fail            = 193.61 sec*proc (18 tests)
io              =  57.51 sec*proc (12 tests)
p3              = 1076.21 sec*proc (70 tests)
physics         = 1221.53 sec*proc (95 tests)
rrtmgp          = 543.34 sec*proc (38 tests)
shoc            = 473.72 sec*proc (35 tests)
spa             = 192.12 sec*proc (27 tests)

Total Test time (real) =  73.71 sec
177/185 Test  #97: shoc_tests_omp16 ..............................   Passed    1.95 sec
178/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  455.82 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.09 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec
182/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  487.97 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.17 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6744.99 sec*proc (28 tests)
cld_fraction    =   1.35 sec*proc (1 test)
diagnostics     =   0.67 sec*proc (1 test)
driver          = 5404.47 sec*proc (23 tests)
dynamics        = 5438.84 sec*proc (29 tests)
fail            = 658.16 sec*proc (19 tests)
io              =  79.42 sec*proc (12 tests)
p3              = 8520.52 sec*proc (67 tests)
physics         = 9687.25 sec*proc (92 tests)
rrtmgp          = 7527.46 sec*proc (38 tests)
shoc            = 6797.73 sec*proc (35 tests)
spa             = 1555.01 sec*proc (27 tests)

Total Test time (real) = 570.90 sec
===============================================================================
Testing '6f7eba28694afa3cf8d0002ba3626315db276133' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2990/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2990/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2990/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/2990/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64 [...]

2022-03-24 21:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-03-24 21:12 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-03-24 21:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2991</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2883</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2244</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: ebc26312ebba30fefb472388e4a4d84629be3af3</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-24 22:33 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 2991</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2883</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2244</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ebc26312ebba30fefb472388e4a4d84629be3af3</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2022-03-24 22:33 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2022-03-24 22:33 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-03-26 00:03 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-03-27 00:14 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-03-28 01:11 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-03-28 23:13 UTC, bartgol requested changes
Looks good. I only have a few minor comments.

2022-03-28 23:20 UTC, AaronDonahue commented on components/scream/src/diagnostics/potential_temperature.cpp
> +  auto ts = timestamp();  // TODO - how confident are we with how this timestamp is being handled?
okay good.  I just want to make sure that the timestamp in a diagnostic isn't necessarily out of sync with the rest of the model.  So I put this comment in the code to elicit just this kind of response.

2022-03-28 23:40 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2022-03-28 23:40 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-03-29 16:55 UTC, AaronDonahue commented
@bartgol , thank you for the review.  I've made all the changes you asked for, when you get a chance can you re-review?

2022-03-29 20:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-03-29 20:22 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-03-29 20:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3002</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2894</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2250</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: e7dd6983fa09d7f4dc661124328f3a94b770cf3a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-29 21:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3002</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2894</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2250</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3002</b> (click to expand)
</summary>
<pre>
<code>
        Start 100: shoc_tests_omp16
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.55 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.30 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.32 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 564.21 sec*proc (28 tests)
cld_fraction    =   0.73 sec*proc (1 test)
diagnostics     =   0.58 sec*proc (1 test)
driver          = 318.12 sec*proc (23 tests)
dynamics        = 332.73 sec*proc (29 tests)
fail            = 194.09 sec*proc (18 tests)
io              =  92.50 sec*proc (12 tests)
p3              = 1170.56 sec*proc (70 tests)
physics         = 1350.47 sec*proc (95 tests)
rrtmgp          = 668.80 sec*proc (38 tests)
shoc            = 586.28 sec*proc (35 tests)
spa             = 263.84 sec*proc (27 tests)

Total Test time (real) =  81.53 sec
178/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  457.63 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.10 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec
182/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  446.48 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.17 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6691.47 sec*proc (28 tests)
cld_fraction    =   0.79 sec*proc (1 test)
diagnostics     =   1.02 sec*proc (1 test)
driver          = 5341.35 sec*proc (23 tests)
dynamics        = 5384.55 sec*proc (29 tests)
fail            = 634.01 sec*proc (19 tests)
io              = 122.81 sec*proc (12 tests)
p3              = 8475.02 sec*proc (67 tests)
physics         = 9676.45 sec*proc (92 tests)
rrtmgp          = 7479.26 sec*proc (38 tests)
shoc            = 6750.97 sec*proc (35 tests)
spa             = 1626.20 sec*proc (27 tests)

Total Test time (real) = 577.70 sec
===============================================================================
Testing 'dada87f594cb807b43d98abfee662336060e03fe' for test 'release'
===============================================================================
RUN: taskset -c 72-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3002/scream/components/scream/ctest-build/release/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3002/scream/components/scream/ctest-build/release -DBUILD_NAME_MOD=release -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3002/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3002/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Release -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_ [...]

2022-03-29 22:29 UTC, bartgol approved these changes

2022-03-30 03:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3006</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2898</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2254</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: e7dd6983fa09d7f4dc661124328f3a94b770cf3a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-30 04:40 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3006</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2898</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2254</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e7dd6983fa09d7f4dc661124328f3a94b770cf3a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>dc278c0b167335ef93d9af4422d70f11c14c982a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3006</b> (click to expand)
</summary>
<pre>
<code>
        Start 100: shoc_tests_omp16
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.55 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.35 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.32 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 564.94 sec*proc (28 tests)
cld_fraction    =   0.64 sec*proc (1 test)
diagnostics     =   0.64 sec*proc (1 test)
driver          = 324.16 sec*proc (23 tests)
dynamics        = 338.18 sec*proc (29 tests)
fail            = 194.88 sec*proc (18 tests)
io              =  94.01 sec*proc (12 tests)
p3              = 1183.38 sec*proc (70 tests)
physics         = 1367.43 sec*proc (95 tests)
rrtmgp          = 670.94 sec*proc (38 tests)
shoc            = 588.47 sec*proc (35 tests)
spa             = 266.58 sec*proc (27 tests)

Total Test time (real) =  82.47 sec
178/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  467.83 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.11 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec
182/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  443.70 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.16 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6792.63 sec*proc (28 tests)
cld_fraction    =   1.86 sec*proc (1 test)
diagnostics     =   1.48 sec*proc (1 test)
driver          = 5378.40 sec*proc (23 tests)
dynamics        = 5412.10 sec*proc (29 tests)
fail            = 632.28 sec*proc (19 tests)
io              = 130.21 sec*proc (12 tests)
p3              = 8544.05 sec*proc (67 tests)
physics         = 9806.59 sec*proc (92 tests)
rrtmgp          = 7618.73 sec*proc (38 tests)
shoc            = 6865.96 sec*proc (35 tests)
spa             = 1699.81 sec*proc (27 tests)

Total Test time (real) = 577.59 sec
===============================================================================
Testing 'f6c69a0a10ce8c3870c87c156534597c7aaae96e' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3006/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3006/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3006/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3006/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSC [...]

2022-03-30 09:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-03-30 16:13 UTC, AaronDonahue commented
This is failing because it needs a rebase for v0 baselines to pass and because of the fail we already know about for v1 tests that is fixed in PR #1512 .  Once #1512 goes in I'll rebase this PR and RETEST

2022-03-30 23:28 UTC, bartgol approved these changes
Looks good. I have a comment, but it's not a road blocker.

2022-03-30 23:36 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-03-31 00:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-03-31 04:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-03-31 04:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-03-31 04:52 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-03-31 09:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3021</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2912</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2262</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-31 10:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3021</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2912</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2262</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3021</b> (click to expand)
</summary>
<pre>
<code>
        Start  97: shoc_tests_omp13
183/188 Test  #97: shoc_tests_omp13 ..............................   Passed    0.55 sec
        Start  98: shoc_tests_omp14
184/188 Test  #98: shoc_tests_omp14 ..............................   Passed    0.55 sec
        Start  99: shoc_tests_omp15
185/188 Test  #99: shoc_tests_omp15 ..............................   Passed    0.56 sec
        Start 100: shoc_tests_omp16
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.55 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.36 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.32 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 460.45 sec*proc (28 tests)
cld_fraction    =   0.69 sec*proc (1 test)
diagnostics     =   0.58 sec*proc (1 test)
driver          = 253.12 sec*proc (23 tests)
dynamics        = 266.17 sec*proc (29 tests)
fail            = 198.69 sec*proc (18 tests)
io              =  54.27 sec*proc (12 tests)
p3              = 1061.76 sec*proc (70 tests)
physics         = 1196.73 sec*proc (95 tests)
rrtmgp          = 550.38 sec*proc (38 tests)
shoc            = 472.92 sec*proc (35 tests)
spa             = 191.21 sec*proc (27 tests)

Total Test time (real) =  71.03 sec
182/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  473.44 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.18 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6681.51 sec*proc (28 tests)
cld_fraction    =   0.86 sec*proc (1 test)
diagnostics     =   0.66 sec*proc (1 test)
driver          = 5386.60 sec*proc (23 tests)
dynamics        = 5435.66 sec*proc (29 tests)
fail            = 645.72 sec*proc (19 tests)
io              =  93.50 sec*proc (12 tests)
p3              = 8428.71 sec*proc (67 tests)
physics         = 9555.51 sec*proc (92 tests)
rrtmgp          = 7438.99 sec*proc (38 tests)
shoc            = 6730.92 sec*proc (35 tests)
spa             = 1510.82 sec*proc (27 tests)

Total Test time (real) = 555.23 sec
===============================================================================
Testing 'f04d9c93329d51d327d7a53ccaeeec5218e2e45e' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3021/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3021/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3021/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3021/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=24 -DSCREAM_TEST_DATA_DIR=/home/projects/e3sm/scream/pr-autotester/master-baselines/bla [...]

2022-03-31 14:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3023</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2914</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2264</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-03-31 15:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3023</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2914</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2264</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3023</b> (click to expand)
</summary>
<pre>
<code>
186/188 Test #100: shoc_tests_omp16 ..............................   Passed    0.56 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
187/188 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.31 sec
        Start 102: shoc_run_and_cmp_f90_omp16
188/188 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.33 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 552.55 sec*proc (28 tests)
cld_fraction    =   0.65 sec*proc (1 test)
diagnostics     =   0.75 sec*proc (1 test)
driver          = 305.48 sec*proc (23 tests)
dynamics        = 320.66 sec*proc (29 tests)
fail            = 194.63 sec*proc (18 tests)
io              =  92.79 sec*proc (12 tests)
p3              = 1166.75 sec*proc (70 tests)
physics         = 1342.78 sec*proc (95 tests)
rrtmgp          = 656.21 sec*proc (38 tests)
shoc            = 573.39 sec*proc (35 tests)
spa             = 264.70 sec*proc (27 tests)

Total Test time (real) =  81.13 sec
178/185 Test #179: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  436.02 sec
        Start 183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
179/185 Test #183: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.19 sec
        Start 184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
180/185 Test #184: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
181/185 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec
182/185 Test #168: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  490.57 sec
        Start 172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
183/185 Test #172: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.09 sec
        Start 173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
184/185 Test #173: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
185/185 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.09 sec

100% tests passed, 0 tests failed out of 185

Label Time Summary:
cld             = 6627.47 sec*proc (28 tests)
cld_fraction    =   1.81 sec*proc (1 test)
diagnostics     =   1.00 sec*proc (1 test)
driver          = 5302.34 sec*proc (23 tests)
dynamics        = 5338.99 sec*proc (29 tests)
fail            = 638.33 sec*proc (19 tests)
io              = 136.07 sec*proc (12 tests)
p3              = 8421.63 sec*proc (67 tests)
physics         = 9645.91 sec*proc (92 tests)
rrtmgp          = 7417.54 sec*proc (38 tests)
shoc            = 6694.15 sec*proc (35 tests)
spa             = 1633.92 sec*proc (27 tests)

Total Test time (real) = 583.96 sec
===============================================================================
Testing 'f04d9c93329d51d327d7a53ccaeeec5218e2e45e' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3023/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3023/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3023/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3023/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMM [...]

2022-04-08 15:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3071</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2951</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2295</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-08 16:48 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3071</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2951</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2295</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3071</b> (click to expand)
</summary>
<pre>
<code>
        Start 100: shoc_tests_omp16
189/191 Test #100: shoc_tests_omp16 ..............................   Passed    0.57 sec
        Start 101: shoc_run_and_cmp_cxx_omp16
190/191 Test #101: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.32 sec
        Start 102: shoc_run_and_cmp_f90_omp16
191/191 Test #102: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.33 sec

100% tests passed, 0 tests failed out of 191

Label Time Summary:
cld             = 550.85 sec*proc (28 tests)
cld_fraction    =   0.68 sec*proc (1 test)
diagnostics     =   0.67 sec*proc (1 test)
driver          = 305.60 sec*proc (23 tests)
dynamics        = 320.97 sec*proc (29 tests)
fail            = 200.64 sec*proc (18 tests)
io              =  93.84 sec*proc (12 tests)
p3              = 1162.91 sec*proc (71 tests)
physics         = 1340.85 sec*proc (95 tests)
rrtmgp          = 654.98 sec*proc (38 tests)
shoc            = 572.86 sec*proc (36 tests)
spa             = 265.29 sec*proc (27 tests)

Total Test time (real) =  81.81 sec
181/188 Test #171: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  438.05 sec
        Start 175: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
182/188 Test #175: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.10 sec
        Start 176: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
183/188 Test #176: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.09 sec
        Start 177: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
184/188 Test #177: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.09 sec
185/188 Test #182: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  478.17 sec
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
186/188 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.18 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
187/188 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
188/188 Test #188: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 188

Label Time Summary:
cld             = 6138.10 sec*proc (28 tests)
cld_fraction    =   1.30 sec*proc (1 test)
diagnostics     =   1.02 sec*proc (1 test)
driver          = 4876.36 sec*proc (23 tests)
dynamics        = 4905.96 sec*proc (29 tests)
fail            = 615.01 sec*proc (19 tests)
io              = 118.28 sec*proc (12 tests)
p3              = 7842.73 sec*proc (68 tests)
physics         = 9099.83 sec*proc (92 tests)
rrtmgp          = 6929.80 sec*proc (38 tests)
shoc            = 6212.41 sec*proc (36 tests)
spa             = 1598.78 sec*proc (27 tests)

Total Test time (real) = 598.60 sec
===============================================================================
Testing '5b044b8187f343d83a5b0c2d6031bdac261827b9' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3071/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3071/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3071/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3071/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/o [...]

2022-04-08 21:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3074</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2954</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2298</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-08 22:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3074</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2954</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2298</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3074</b> (click to expand)
</summary>
<pre>
<code>
        Start  99: shoc_tests_omp16
188/190 Test  #99: shoc_tests_omp16 ..............................   Passed    0.56 sec
        Start 100: shoc_run_and_cmp_cxx_omp16
189/190 Test #100: shoc_run_and_cmp_cxx_omp16 ....................   Passed    0.30 sec
        Start 101: shoc_run_and_cmp_f90_omp16
190/190 Test #101: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.32 sec

100% tests passed, 0 tests failed out of 190

Label Time Summary:
cld             = 499.20 sec*proc (28 tests)
cld_fraction    =   0.80 sec*proc (1 test)
diagnostics     =   0.57 sec*proc (1 test)
driver          = 280.19 sec*proc (23 tests)
dynamics        = 295.96 sec*proc (29 tests)
fail            = 195.95 sec*proc (18 tests)
io              =  93.81 sec*proc (12 tests)
p3              = 1050.04 sec*proc (71 tests)
physics         = 1242.58 sec*proc (95 tests)
rrtmgp          = 604.95 sec*proc (38 tests)
shoc            = 526.46 sec*proc (36 tests)
spa             = 256.66 sec*proc (27 tests)

Total Test time (real) =  76.47 sec
180/187 Test #170: homme_shoc_cld_p3_rrtmgp_np1 ..................   Passed  484.87 sec
        Start 174: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
181/187 Test #174: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .......   Passed    0.10 sec
        Start 175: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
182/187 Test #175: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .......   Passed    0.08 sec
        Start 176: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
183/187 Test #176: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .......   Passed    0.08 sec
184/187 Test #181: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  469.71 sec
        Start 185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
185/187 Test #185: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ...   Passed    0.17 sec
        Start 186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
186/187 Test #186: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb ...   Passed    0.16 sec
        Start 187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
187/187 Test #187: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb ...   Passed    0.16 sec

100% tests passed, 0 tests failed out of 187

Label Time Summary:
cld             = 7267.01 sec*proc (28 tests)
cld_fraction    =   1.00 sec*proc (1 test)
diagnostics     =   1.45 sec*proc (1 test)
driver          = 5666.74 sec*proc (23 tests)
dynamics        = 5705.58 sec*proc (29 tests)
fail            = 711.54 sec*proc (19 tests)
io              = 146.69 sec*proc (12 tests)
p3              = 8964.41 sec*proc (68 tests)
physics         = 10166.67 sec*proc (92 tests)
rrtmgp          = 8062.90 sec*proc (38 tests)
shoc            = 7324.08 sec*proc (36 tests)
spa             = 1699.20 sec*proc (27 tests)

Total Test time (real) = 584.86 sec
===============================================================================
Testing '6edbafff355ab3af93f1d660bbd9075a92f74bee' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 24-47 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=24 CTEST_PARALLEL_LEVEL=24 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3074/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3074/scream/components/scream/ctest-build/full_sp_debug -DBUILD_NAME_MOD=full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3074/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3074/scream/components/scream/cmake/machine-files/blake.cmake -DNetCDF_Fortran_PATH=/home/projects/e3sm/scream/libs/netcdf-fortran/install/blake -DNetCDF_C_PATH=/ascldap/users/projects/e3sm/scream/libs/netcdf-c/install/blake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.2/intel/19.3.199/bin/ [...]

2022-04-09 16:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3077</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2957</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2301</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-09 17:40 UTC, E3SM-Autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2022-04-09 17:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3078</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2958</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2302</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-09 20:47 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3078</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2958</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2302</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3078</b> (click to expand)
</summary>
<pre>
<code>
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/BGC.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.MARBL.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.MARBL.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.components/mpas-ocean/src/gotm.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/gotm.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.externals/mct.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.externals/mct.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
ERROR: Timeout after 10 minutes
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr" returned status code 1:
stdout: 
stderr: Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3078/scream/components/elm/src/external_models/sbetr'...
/home/projects/x86-64/git/2.9.4/libexec/git-core/git-submodule: line 491: 266882 Terminated              $command "$sha1"
Unable to checkout '51be6d5f858145654d3c94c2985b3e347dd5a1d4' in submodule path 'components/elm/src/external_models/sbetr'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to blake
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org. [...]

2022-04-10 02:08 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-04-10 06:31 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3080</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2959</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2303</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: f04d9c93329d51d327d7a53ccaeeec5218e2e45e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-10 07:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3080</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2959</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2303</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;CIME;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f04d9c93329d51d327d7a53ccaeeec5218e2e45e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3080</b> (click to expand)
</summary>
<pre>
<code>
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.externals/mct.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive externals/kokkos # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/eam/src/physics/rrtmgp/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive externals/scorpio # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive externals/scorpio_classic # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/eam/src/physics/cosp2/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive cime # timeout=10
ERROR: Timeout after 10 minutes
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive cime" returned status code 143:
stdout: 
stderr: Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3080/scream/cime'...

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to blake
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)
		at com.sun.proxy.$Proxy84.execute(Unknown Source)
		at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:160)
		at hudson. [...]

2022-04-11 18:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-11 18:42 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-04-11 18:43 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3084</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2963</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2305</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 1ed3432204caa068bf0662594b2fe6cf0dada2b9</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-11 19:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3084</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2963</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2305</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ed3432204caa068bf0662594b2fe6cf0dada2b9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3a702f306b0d6aefaeddaf82af2fe674612bdf65</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3084</b> (click to expand)
</summary>
<pre>
<code>
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/BGC.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.MARBL.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.MARBL.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.components/mpas-ocean/src/gotm.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/gotm.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.externals/mct.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.externals/mct.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
ERROR: Timeout after 10 minutes
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr" returned status code 1:
stdout: 
stderr: Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3084/scream/components/elm/src/external_models/sbetr'...
/home/projects/x86-64/git/2.9.4/libexec/git-core/git-submodule: line 491: 214973 Terminated              $command "$sha1"
Unable to checkout '51be6d5f858145654d3c94c2985b3e347dd5a1d4' in submodule path 'components/elm/src/external_models/sbetr'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to blake
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.ref [...]

2022-04-12 00:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2022-04-12 17:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-12 17:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2022-04-12 20:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-12 20:39 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-04-12 21:02 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3099</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2974</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2315</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: cde59f65752b4e06a356e975e1b3fc156785be4a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-12 21:34 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3099</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2974</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2315</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>cde59f65752b4e06a356e975e1b3fc156785be4a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3099</b> (click to expand)
</summary>
<pre>
<code>
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/BGC.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.MARBL.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.MARBL.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.components/mpas-ocean/src/gotm.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/gotm.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.externals/mct.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.externals/mct.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
ERROR: Timeout after 10 minutes
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr" returned status code 1:
stdout: 
stderr: Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3099/scream/components/elm/src/external_models/sbetr'...
/home/projects/x86-64/git/2.9.4/libexec/git-core/git-submodule: line 491: 40474 Terminated              $command "$sha1"
Unable to checkout '51be6d5f858145654d3c94c2985b3e347dd5a1d4' in submodule path 'components/elm/src/external_models/sbetr'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to blake
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.refl [...]

2022-04-13 01:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-13 01:27 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-04-13 02:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-13 02:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3102</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2977</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2317</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 719128392ee4072a8a963e46c720eca04d5d7ef1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-13 03:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3102</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2977</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2317</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3102</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on blake in workspace /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Wiping out workspace first.
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > /home/projects/x86-64/git/2.9.4/bin/git init /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3102/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > /home/projects/x86-64/git/2.9.4/bin/git --version # timeout=10
 > git --version # 'git version 2.9.4'
using GIT_SSH to set credentials jgfouca github key
Setting http proxy: proxy.sandia.gov:80
 > /home/projects/x86-64/git/2.9.4/bin/git fetch --tags --progress -- https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1496/head:refs/heads/pr/1496 # timeout=30
ERROR: Timeout after 30 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git fetch --tags --progress -- https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1496/head:refs/heads/pr/1496" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 346830, done.        
remote: Counting objects:   0% (1/17739)        
remote: Counting objects:   1% (178/17739)        
remote: Counting objects:   2% (355/17739)        
remote: Counting objects:   3% (533/17739)        
remote: Counting objects:   4% (710/17739)        
remote: Counting objects:   5% (887/17739)        
remote: Counting objects:   6% (1065/17739)        
remote: Counting objects:   7% (1242/17739)        
remote: Counting objects:   8% (1420/17739)        
remote: Counting objects:   9% (1597/17739)        
remote: Counting objects:  10% (1774/17739)        
remote: Counting objects:  11% (1952/17739)        
remote: Counting objects:  12% (2129/17739)        
remote: Counting objects:  13% (2307/17739)        
remote: Counting objects:  14% (2484/17739)        
remote: Counting objects:  15% (2661/17739)        
remote: Counting objects:  16% (2839/17739)        
remote: Counting objects:  17% (3016/17739)        
remote: Counting objects:  18% (3194/17739)        
remote: Counting objects:  19% (3371/17739)        
remote: Counting objects:  20% (3548/17739)        
remote: Counting objects:  21% (3726/17739)        
remote: Counting objects:  22% (3903/17739)        
remote: Counting objects:  23% (4080/17739)        
remote: Counting objects:  24% (4258/17739)        
remote: Counting objects:  25% (4435/17739)        
remote: Counting objects:  26% (4613/17739)        
remote: Counting objects:  27% (4790/17739)        
remote: Counting objects:  28% (4967/17739)        
remote: Counting objects:  29% (5145/17739)        
remote: Counting objects:  30% (5322/17739)        
remote: Counting objects:  31% (5500/17739)        
remote: Counting objects:  32% (5677/17739)        
remote: Counting objects:  33% (5854/17739)        
remote: Counting objects:  34% (6032/17739)        
remote: Counting objects:  35% (6209/17739)        
remote: Counting objects:  36% (6387/17739)        
remote: Counting objects:  37% (6564/17739)        
remote: Counting objects:  38% (6741/17739)        
remote: Counting objects:  39% (6919/17739)        
remote: Counting objects:  40% (7096/17739)        
remote: Counting objects:  41% (7273/17739)        
remote: Counting objects:  42% (7451/17739)        
remote: Counting objects:  43% (7628/17739)        
remote: Counting objects:  44% (7806/17739)        
remote: Counting objects:  45% (7983/17739)        
remote: Counting objects:  46% (8160/17739)        
remote: Counting objects:  47% (8338/17739)        
remote: Counting objects:  48% (8515/17739)        
remote: Counting objects:  49% (8693/17739)        
remote: Counting objects:  50% (8870/17739)        
remote: Counting objects:  51% (9047/17739)        
remote: Counting objects:  52% (9225/17739)        
remote: Counting objects:  53% (9402/17739)        
remote: Counting objects:  54% (9580/17739)        
remote: Coun [...]

2022-04-13 08:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-04-13 13:19 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3108</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2983</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2321</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 719128392ee4072a8a963e46c720eca04d5d7ef1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-13 16:33 UTC, AaronDonahue commented
Retesting this PR, the only fails were `blake` which is expected and the one fail on `mappy` was the `p3_tests_omp13` which shouldn't be impacted by this PR at all.

2022-04-13 17:17 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-13 17:56 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-04-13 18:02 UTC, AaronDonahue commented
adding the `skip blake` label so the AT won't time-out like above.

2022-04-13 18:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-04-13 18:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3112</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2987</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2325</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_diagnostics_to_io</li>
    <li>SHA: 719128392ee4072a8a963e46c720eca04d5d7ef1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-04-13 19:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3112</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 2987</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2325</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;AT: Skip blake;SCREAMv1;diagnostic</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1496</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_diagnostics_to_io</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>719128392ee4072a8a963e46c720eca04d5d7ef1</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a02efd9361ca4e203996c44cecd389d244f46808</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 3112</b> (click to expand)
</summary>
<pre>
<code>
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.MARBL.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.MARBL.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.components/mpas-ocean/src/gotm.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.components/mpas-ocean/src/gotm.path # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get submodule.externals/mct.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git remote # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config --get remote.origin.url # timeout=10
 > /home/projects/x86-64/git/2.9.4/bin/git config -f .gitmodules --get submodule.externals/mct.path # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > /home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
ERROR: Timeout after 10 minutes
hudson.plugins.git.GitException: Command "/home/projects/x86-64/git/2.9.4/bin/git submodule update --init --recursive components/elm/src/external_models/sbetr" returned status code 143:
stdout: Submodule path 'components/elm/src/external_models/sbetr': checked out '51be6d5f858145654d3c94c2985b3e347dd5a1d4'

stderr: Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/3112/scream/components/elm/src/external_models/sbetr'...
/home/projects/x86-64/git/2.9.4/libexec/git-core/git-submodule: line 491: 279207 Done                    { git submodule--helper update-clone ${GIT_QUIET:+--quiet} ${wt_prefix:+--prefix "$wt_prefix"} ${prefix:+--recursive-prefix "$prefix"} ${update:+--update "$update"} ${reference:+--reference "$reference"} ${depth:+--depth "$depth"} ${jobs:+$jobs} "$@" || echo "#unmatched"; }
error: git-submodule died of signal 15

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to blake
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk [...]

2022-04-13 22:03 UTC, AaronDonahue commented
Luca, this passed on `mappy` and `weaver`.  I'm going to manually run on `quartz`.  In the meantime do you mind rereviewing?

2022-04-13 23:06 UTC, AaronDonahue commented
Testing on quartz returned a PASS for all of the test suites.

2022-04-14 02:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-04-14 02:22 UTC, bartgol approved these changes

2022-04-14 03:51 UTC, merged