Adjust the scream-scorpio interface freeing pio decomp memory when not needed
E3SM-Project/scream pull request #1643
Opened 2022-05-13 19:37 UTC by AaronDonahue

This commit adds the new subroutine in the scream_scorpio_interface.F90 code,
`free_decomp`, which will free the memory in scorpio for any pio decomposition
that is no longer needed.  This routine is called whenever a file is closed.

There is also some updates to the infrastructure in the scream scorpio interface
to keep track of which PIO decompositions are still in use, and if one is deleted
having it removed from the list of valid pio decomps.

Should address #1621

2022-05-13 19:37 UTC, AaronDonahue commented
@ndkeen , this hasn't been reviewed yet, but you are welcome to grab the branch and merge it to your to see how well it addresses the memory usage you are seeing at ne120.

2022-05-13 19:59 UTC, PeterCaldwell commented
In addition to reducing our overall memory footprint, I'm also curious whether this fixes our memory leak when writing output!

2022-05-13 20:51 UTC, AaronDonahue commented
@PeterCaldwell , unfortunately, my preliminary checks seem to indicate the output mem-leak is still an issue.  I'm investigating that now.

2022-05-13 22:01 UTC, ndkeen commented
I added this to my branch. It does look like ne30 now using less memory (can run with spa on 1 node). I do see the slight memory growth per snapshot.

But then for ne120, I'm getting some fails.  I assume you haven't tried with ne120.

```
1536: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
1536: 
1536: Backtrace for this error:
1536: #0  0x14a8e35c5d6f in ???
1536: #1  0x14a8e6e5b911 in ???
1536: #2  0x14a8e6e33b77 in ???
1536: #3  0x14a8e58e3398 in ???
1536: #4  0x14a8e5919eb5 in ???
1536: #5  0x14a8e591ac75 in ???
1536: #6  0xf040d6 in pio_swapm
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pio_spmd.c:404
1536: #7  0xed0e05 in compute_counts
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pio_rearrange.c:824
1536: #8  0xed2537 in box_rearrange_create
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pio_rearrange.c:1596
1536: #9  0xecbfa8 in PIOc_InitDecomp
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/clib/pioc.c:771
1536: #10  0xe8756a in pio_initdecomp_internal
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/flib/piolib_mod.F90:600
1536: #11  0xe8756a in __piolib_mod_MOD_pio_initdecomp_dof_i8
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/flib/piolib_mod.F90:625
1536: #12  0xe879d5 in __piolib_mod_MOD_pio_initdecomp_dof_i4
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/externals/scorpio/src/flib/piolib_mod.F90:535
1536: #13  0xfdd8ac in __scream_scorpio_interface_MOD_get_decomp
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/io/scream_scorpio_interface.F90:977
1536: #14  0xfde86e in __scream_scorpio_interface_MOD_set_decomp
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/io/scream_scorpio_interface.F90:1055
1536: #15  0xfe71f0 in set_decomp_c2f
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/io/scream_scorpio_interface_iso_c2f.F90:68
1536: #16  0xfe5515 in _ZN6scream7scorpio10set_decompERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/io/scream_scorpio_interface.cpp:59
1536: #17  0x172a266 in _ZN6scream3spa12SPAFunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE27get_remap_weights_from_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiRKNS2_4ViewIPiJNS2_11LayoutRightES6_NS2_12MemoryTraitsILj0EEEEEERNS7_14SPAHorizInterpE
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/physics/spa/spa_functions_impl.hpp:392
1536: #18  0x171aba5 in _ZN6scream3SPA15initialize_implENS_7RunTypeE
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/physics/spa/atmosphere_prescribed_aerosol.cpp:170
1536: #19  0x174d688 in _ZN6scream17AtmosphereProcess10initializeERKNS_4util9TimeStampENS_7RunTypeE
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/atm_process/atmosphere_process.cpp:44
1536: #20  0x1751860 in _ZN6scream22AtmosphereProcessGroup15initialize_implENS_7RunTypeE
1536:   at /global/cfs/cdirs/e3sm/ndk/se03-may6/components/scream/src/share/atm_process/atmosphere_process_group.cpp:186
```

2022-05-16 16:09 UTC, AaronDonahue commented
@ndkeen , thanks for trying the branch out and providing that stack trace.  I'm going to try to figure out what could be going wrong.  To answer your question, I haven't tried ne120 myself yet.

2022-05-16 16:23 UTC, AaronDonahue commented
@ndkeen , can you point me to the branch you have merge this branch into?  When I follow the stack trace it takes me to lines of code that don't make sense given the stack trace.  Is it possible that your local branch also changed the file `scream_scorpio_interface.F90` ?  For example the stacktrace points to line `scream_scorpio_interface.F90:1055` which should point here: https://github.com/E3SM-Project/scream/pull/1643/files#diff-30eeaf24856c1191c8f6ac7ba71d316bd1f65481d13232837518d6db6805f47fR1055, but that is not calling a separate routine.  Furthermore, the next line up in the stack trace: `scream_scorpio_interface.F90:977` points to the line: https://github.com/E3SM-Project/scream/pull/1643/files#diff-30eeaf24856c1191c8f6ac7ba71d316bd1f65481d13232837518d6db6805f47fR977 which is just the end of an `if` statement.

2022-05-16 17:03 UTC, ndkeen commented
As I noted, I've applied your changes on top of others of mine (unrelated).  Perhaps it would be easier if I made a fresh clone and tried again.

2022-05-16 19:00 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-16 19:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2534</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3188</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3309</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: 225cd748be8e7abfd5201a269d75c36cdd6d25ed</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-16 19:51 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2534</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3188</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3309</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>225cd748be8e7abfd5201a269d75c36cdd6d25ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>3241630a98d2360e19b043f50a2c186a4eea0ecc</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2534</b> (click to expand)
</summary>
<pre>
<code>
Test fpe can use 32 jobs to compile, and 32 jobs for test
Test opt can use 32 jobs to compile, and 32 jobs for test
RUN: { module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export CTEST_PARALLEL_LEVEL=128 && export OMP_PROC_BIND=spread;  } > /dev/null && env | sort
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2534/scream/components/scream
ERROR: Command: 'git submodule update --init --recursive' failed with error 'Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to fetch in submodule path '../../externals/ekat'' from dir '/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2534/scream/components/scream'
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2534/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
RUN: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2534/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2534/scream/components/scream
mappy failed
+ [[ 1 != 0 ]]
+ fails=0+1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ mappy == \m\a\p\p\y ]]
+ [[ 0 == 1 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ '[' -n 1643 ']'
+ ./scripts/git-merge-ref origin/master
+ [[ 0 != 0 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ ../../cime/scripts/create_test e3sm_scream_v1 --compiler=gnu9 -c -b master
No project info available
create_test will do up to 3 tasks simultaneously
create_test will use up to 80 cores simultaneously
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.C.20220516_130326_8sdcdo
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9.C.20220516_130326_8sdcdo
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9.C.20220516_130326_8sdcdo
RUNNING TESTS:
  SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.599464 seconds (PASS)
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.600390 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.618528 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.374063 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.384652 seconds (PASS)
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy [...]

2022-05-16 20:15 UTC, AaronDonahue commented
This latest commit should address the issue #1565 .

2022-05-16 20:32 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-16 20:33 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2536</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3190</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3311</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: 97c66db5d1c3bf6183ee02c484dbf78613e3065b</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-16 21:04 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2536</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3190</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3311</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2536</b> (click to expand)
</summary>
<pre>
<code>
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/kokkos # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/eam/src/physics/rrtmgp/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/scorpio # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/scorpio_classic # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/eam/src/physics/cosp2/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive cime # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/ekat # timeout=10
hudson.plugins.git.GitException: Command "git submodule update --init --recursive externals/ekat" returned status code 1:
stdout: Cloning into 'externals/ekat'...

stderr: fatal: reference is not a tree: 20a5633f8d34bdf78cdb532b4141ec5b3f6b5b38
Unable to checkout '20a5633f8d34bdf78cdb532b4141ec5b3f6b5b38' in submodule path 'externals/ekat'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mappy
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)
		at com.sun.proxy.$Proxy85.execute(Unknown Source)
		at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:160)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1379)
		at hudson.scm.SCM.checkout(SCM.java:540)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1215)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:645)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
		at hudson.model.AbstractBui [...]

2022-05-16 21:29 UTC, jgfouca commented
@AaronDonahue , that looks like the kind of error you get when a developer pushes an update to a submodule that was never published in the submodule repo. Since this PR doesn't appear to touch the EKAT submodule, I don't see why we'd get this error unless something bad is on master too. It's possible a network issue resulted in a misleading Jenkins error. Let's let the AT take another crack at it to be sure.

2022-05-16 21:34 UTC, AaronDonahue commented
@jgfouca , this could also be my fault.  I recently force-pushed a PR that had EKAT changes.  Although I was under the impression that PR passed manual testing, so presumably it shouldn't have been a problem.  I labeled RETEST, we can see what happens after that.

2022-05-16 21:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-16 22:17 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2537</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3191</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3312</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>97c66db5d1c3bf6183ee02c484dbf78613e3065b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>832ecb996143c728077d9de6aa5a215a3cd6bdd7</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2537</b> (click to expand)
</summary>
<pre>
<code>
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/fates # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/mpp # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/elm/src/external_models/sbetr # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/kokkos # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/eam/src/physics/rrtmgp/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/scorpio # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/scorpio_classic # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive components/eam/src/physics/cosp2/external # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive cime # timeout=10
using GIT_SSH to set credentials jgfouca github key
 > git submodule update --init --recursive externals/ekat # timeout=10
hudson.plugins.git.GitException: Command "git submodule update --init --recursive externals/ekat" returned status code 1:
stdout: Cloning into 'externals/ekat'...

stderr: fatal: reference is not a tree: 20a5633f8d34bdf78cdb532b4141ec5b3f6b5b38
Unable to checkout '20a5633f8d34bdf78cdb532b4141ec5b3f6b5b38' in submodule path 'externals/ekat'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$7.lambda$execute$0(CliGitAPIImpl.java:1505)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.submitRemainingCommand(GitCommandsExecutor.java:98)
	at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutor.invokeAll(GitCommandsExecutor.java:92)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mappy
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)
		at com.sun.proxy.$Proxy85.execute(Unknown Source)
		at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:160)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1379)
		at hudson.scm.SCM.checkout(SCM.java:540)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1215)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:645)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
		at hudson.model.AbstractBui [...]

2022-05-16 22:30 UTC, bartgol commented
@AaronDonahue that error was my fault. I forgot to update the dyn grid IO pr, which was using EKAT from a sha that was not in the repo. #1644 should fix master, but you will have to rebase on master once more, to get the correct submodule SHA.

2022-05-16 22:48 UTC, AaronDonahue commented
@bartgol , ok great, thanks for fixing that.

2022-05-16 23:35 UTC, AaronDonahue commented
![image](https://user-images.githubusercontent.com/11351562/168698900-43508b34-6292-417f-bb13-df9f8590bb9f.png)

2022-05-16 23:46 UTC, AaronDonahue commented
We no longer see any big memory leak for 1 file - all snapshots.  Although there is still some slight leak when we have 1 snapshot per file.  There must be something that isn't being deallocated properly that isn't covered in this PR.

2022-05-17 00:53 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-17 00:53 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-17 01:36 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-05-17 11:21 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2543</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3197</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3318</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-17 11:50 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2543</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3197</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3318</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b4fa0bb9d96b01c4ab766eb8bcd5a0696634a4d4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2543</b> (click to expand)
</summary>
<pre>
<code>
38:dyn_grid_io_np4

Build type release failed. Here's a list of failed tests:
35:dyn_grid_io_np1
36:dyn_grid_io_np2
37:dyn_grid_io_np3
38:dyn_grid_io_np4

Error(s) occurred during test phase
OVERALL STATUS: FAIL
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2543/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
RUN: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2543/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2543/scream/components/scream
mappy failed
+ [[ 1 != 0 ]]
+ fails=0+1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ mappy == \m\a\p\p\y ]]
+ [[ 0 == 1 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ '[' -n 1643 ']'
+ ./scripts/git-merge-ref origin/master
+ [[ 0 != 0 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ ../../cime/scripts/create_test e3sm_scream_v1 --compiler=gnu9 -c -b master
No project info available
create_test will do up to 3 tasks simultaneously
create_test will use up to 80 cores simultaneously
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9.C.20220517_052735_7wedw0
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.C.20220517_052735_7wedw0
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9.C.20220517_052735_7wedw0
RUNNING TESTS:
  SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.589467 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.603564 seconds (PASS)
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.607982 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.200024 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.329632 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.332326 seconds (PASS)
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 2.557477 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 3.348767 seconds (PASS)
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 2.955893 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9  [...]

2022-05-17 16:03 UTC, AaronDonahue commented
@bartgol , all good points/questions.
1. I'll answer the last bullet first - This is using STATM, so I agree that absolute numbers are probably not helpful, just trends.  Also note, I'm using a different number of MPI ranks, the CIME runs use 96 ranks, the unit test runs use 12 I believe.  That will impact absolute numbers too.
2. The difference between blue and purple is that blue is a CIME run.  That might point to something particular with CIME runs.  I'm going to rerun with no output to see if there is an unrelated trend in the run in general.
3. x-axis is simulation hrs, not wall clock time.  The first snapshot is after initialization and the y-axis has the memory usage after the first RUN step subtracted from all values.  So this is growth from step 1.
4. As per "flattening out", yes, I wonder if I let the other simulations run longer if they too would flatten out.  It is worth noting, there is still some growth over time, even for the orange line, but it is very small.  Near the end we are talking about only a jump of 5-10KB, so not much at all.  In the beginning it is more like O(100KB).

2022-05-17 16:43 UTC, AaronDonahue commented
![image](https://user-images.githubusercontent.com/11351562/168864251-f559edb9-2188-4f6e-94a5-f021eee17395.png)

Here are the same tests but without output.  Running with CIME shows a couple of noticeable bumps before flattening out.  I should also note, the unit test is an ne2 test with remapping ne4->ne2 SPA data, while the CIME test is ne4 with mapping ne30->ne4 SPA data.

2022-05-17 17:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-17 17:41 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-17 17:47 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2545</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3199</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3320</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: 1ca3c7725da62485da449ea5f3668fff0ced5e1c</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-17 18:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2545</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3199</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3320</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2545</b> (click to expand)
</summary>
<pre>
<code>
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.605526 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.326497 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.356960 seconds (PASS)
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.321290 seconds (PASS)
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 2.945506 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 3.040987 seconds (PASS)
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 3.275529 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Finished SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 41.329305 seconds (PASS)
Starting MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 16 procs
Finished SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 41.171856 seconds (PASS)
Finished SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 41.185349 seconds (PASS)
Starting MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 16 procs
Starting MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 16 procs
Finished MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 94.050877 seconds (PASS)
Starting RUN for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 24 procs
Finished MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 95.395985 seconds (PASS)
Starting RUN for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 24 procs
Finished MODEL_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 97.608096 seconds (PASS)
Starting RUN for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 24 procs
FATAL: command execution failed
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2905)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3400)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
Caused: java.io.IOException: Backing channel 'mappy' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:215)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
	at com.sun.proxy.$Proxy86.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1215)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1207)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:195)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:145)
	at hudso [...]

2022-05-17 19:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-17 19:17 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2546</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3200</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3321</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: 1ca3c7725da62485da449ea5f3668fff0ced5e1c</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-17 19:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2546</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3200</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3321</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>1ca3c7725da62485da449ea5f3668fff0ced5e1c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2546</b> (click to expand)
</summary>
<pre>
<code>
===============================================================================
Testing '1ca3c7725da62485da449ea5f3668fff0ced5e1c' for test 'debug_nopack_fpe'
===============================================================================
RUN: taskset -c 64-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/debug_nopack_fpe/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/debug_nopack_fpe -DBUILD_NAME_MOD=debug_nopack_fpe -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DSCREAM_PACK_SIZE=1 -DSCREAM_SMALL_PACK_SIZE=1 -DSCREAM_ENABLE_BASELINE_TESTS=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/debug_nopack_fpe
===============================================================================
Testing '1ca3c7725da62485da449ea5f3668fff0ced5e1c' for test 'full_debug'
===============================================================================
RUN: taskset -c 0-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/full_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/full_debug -DBUILD_NAME_MOD=full_debug -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32 -DSCREAM_TEST_DATA_DIR=/sems-data-store/ACME/baselines/scream/master-baselines/full_debug/data" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream/ctest-build/full_debug
OVERALL STATUS: PASS
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2546/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-ne [...]

2022-05-17 20:33 UTC, AaronDonahue commented
@jgfouca or @bartgol , can one of you share with me the FAIL stacktrace for the AT on mappy?  I've tested this branch on quartz, which is an intel build, and it passes so I'm curious to what is causing the fail on mappy.

2022-05-17 20:51 UTC, bartgol commented
It appears to be a double free error during `eam_pio_finalize`, at line 892:
```
      deallocate(prev_file_ptr%pio_file)
```

2022-05-17 20:56 UTC, AaronDonahue commented
strange that didn't pop in my testing on quartz.  But that is the same issue that @ndkeen is seeing with ne120.

2022-05-17 21:59 UTC, ndkeen commented
I tried this on cori-knl with ne120.  It failed with error below. I would verify nospa works on this machine, but just to give you potential feedback quickly:

```
 334: forrtl: error (76): Abort trap signal
 334: Image              PC                Routine            Line        Source             
 334: e3sm.exe           0000000003F1F89B  Unknown               Unknown  Unknown
 334: e3sm.exe           0000000002885120  Unknown               Unknown  Unknown
 334: e3sm.exe           0000000004087280  Unknown               Unknown  Unknown
 334: e3sm.exe           0000000004503961  Unknown               Unknown  Unknown
 334: e3sm.exe           0000000003E31395  _ZN6Kokkos4Impl10          65  Kokkos_Error.cpp
 334: e3sm.exe           0000000003B19833  _ZZN6scream4shoc9         209  Kokkos_Error.hpp
 334: e3sm.exe           0000000003B1CDEE  _ZN6scream4shoc9F         842  Kokkos_HostThreadTeam.hpp
 334: e3sm.exe           0000000003B06988  _ZN6scream4shoc9F         228  shoc_main_impl.hpp
 334: e3sm.exe           0000000003AF3280  _ZZN6scream4shoc9         364  shoc_main_impl.hpp
 334: e3sm.exe           0000000003B04D75  _ZN6Kokkos4Impl11         867  Kokkos_OpenMP_Parallel.hpp
 334: e3sm.exe           0000000003B04813  _ZN6Kokkos12paral         940  Kokkos_OpenMP_Parallel.hpp
 334: e3sm.exe           00000000019C4883  Unknown               Unknown  Unknown
 334: e3sm.exe           000000000198B13C  Unknown               Unknown  Unknown
 334: e3sm.exe           000000000195AC28  Unknown               Unknown  Unknown
 334: e3sm.exe           0000000003B04217  _ZN6Kokkos12paral         914  Kokkos_OpenMP_Parallel.hpp
 334: e3sm.exe           0000000003B03557  _ZN6scream4shoc9F         313  shoc_main_impl.hpp
 334: e3sm.exe           0000000003AF165A  _ZN6scream16SHOCM         402  atmosphere_macrophysics.cpp
 334: e3sm.exe           0000000003C792F1  _ZN6scream17Atmos          70  atmosphere_process.cpp
 334: e3sm.exe           0000000003CABD96  _ZN6scream22Atmos         211  atmosphere_process_group.cpp
 334: e3sm.exe           0000000003C792F1  _ZN6scream17Atmos          70  atmosphere_process.cpp
 334: e3sm.exe           0000000003CABD96  _ZN6scream22Atmos         211  atmosphere_process_group.cpp
 334: e3sm.exe           0000000003C792F1  _ZN6scream17Atmos          70  atmosphere_process.cpp
 334: e3sm.exe           0000000003CABD96  _ZN6scream22Atmos         211  atmosphere_process_group.cpp
 334: e3sm.exe           0000000003C792F1  _ZN6scream17Atmos          70  atmosphere_process.cpp
 334: e3sm.exe           0000000002B3ADBB  _ZN6scream7contro         984  atmosphere_driver.cpp
 334: e3sm.exe           0000000000504132  scream_run                205  scream_cxx_f90_interface.cpp
 334: e3sm.exe           00000000004FC28F  atm_comp_mct_mp_a         220  atm_comp_mct.F90
 334: e3sm.exe           00000000004297B9  component_mod_mp_         762  component_mod.F90
 334: e3sm.exe           0000000000405114  cime_comp_mod_mp_        3100  cime_comp_mod.F90
 334: e3sm.exe           0000000000428EBC  MAIN__                    208  cime_driver.F90
```

2022-05-17 22:59 UTC, AaronDonahue commented
thats strange.  Nothing about this PR should impact SHOC, that error is in the `shoc_assumed_pdf` routine.

2022-05-17 23:00 UTC, ndkeen commented
Yea I get same error now without spa. So maybe that's good new -- ie it's working on cori-knl with spa.  Trying again on cori with GNU.

2022-05-17 23:08 UTC, AaronDonahue commented
@ndkeen , it would be good to know if this is an error with this PR or with `master` in general.

2022-05-17 23:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-17 23:29 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-17 23:30 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2548</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3202</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3323</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: a155fc6f039c75ef2e48e12d0d33dd8657b045b2</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-17 23:41 UTC, ndkeen commented
With GNU and spa, it also fails after 12 steps (not same error -- actually no useful error) on cori-knl. But actually, this is where it was stopping without spa anyway.  So I think this PR would be good to have. I also plotted the memory use with SPA and I think it looks good.

![top_usedmem j59147518 n128](https://user-images.githubusercontent.com/5684727/168929412-90ca956f-a736-40b1-ae95-664ec237e0ab.png)

2022-05-18 00:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2548</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3202</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3323</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2548</b> (click to expand)
</summary>
<pre>
<code>
===============================================================================
Testing 'a155fc6f039c75ef2e48e12d0d33dd8657b045b2' for test 'full_debug'
===============================================================================
RUN: taskset -c 0-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/full_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/full_debug -DBUILD_NAME_MOD=full_debug -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32 -DSCREAM_TEST_DATA_DIR=/sems-data-store/ACME/baselines/scream/master-baselines/full_debug/data" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/full_debug
===============================================================================
Testing 'a155fc6f039c75ef2e48e12d0d33dd8657b045b2' for test 'debug_nopack_fpe'
===============================================================================
RUN: taskset -c 64-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/debug_nopack_fpe/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/debug_nopack_fpe -DBUILD_NAME_MOD=debug_nopack_fpe -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DSCREAM_PACK_SIZE=1 -DSCREAM_SMALL_PACK_SIZE=1 -DSCREAM_ENABLE_BASELINE_TESTS=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream/ctest-build/debug_nopack_fpe
OVERALL STATUS: PASS
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2548/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-ne [...]

2022-05-18 05:05 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-05-18 09:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2553</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3207</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3328</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: a155fc6f039c75ef2e48e12d0d33dd8657b045b2</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-18 10:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2553</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3207</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3328</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a155fc6f039c75ef2e48e12d0d33dd8657b045b2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>882e56d8a5c59461e9f0ae7a92152b5d4bfa7187</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2553</b> (click to expand)
</summary>
<pre>
<code>
===============================================================================
Testing 'a155fc6f039c75ef2e48e12d0d33dd8657b045b2' for test 'debug_nopack_fpe'
===============================================================================
RUN: taskset -c 64-95 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/debug_nopack_fpe/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/debug_nopack_fpe -DBUILD_NAME_MOD=debug_nopack_fpe -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DSCREAM_PACK_SIZE=1 -DSCREAM_SMALL_PACK_SIZE=1 -DSCREAM_ENABLE_BASELINE_TESTS=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/debug_nopack_fpe
===============================================================================
Testing 'a155fc6f039c75ef2e48e12d0d33dd8657b045b2' for test 'full_debug'
===============================================================================
RUN: taskset -c 0-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=32 CTEST_PARALLEL_LEVEL=32 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/full_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/full_debug -DBUILD_NAME_MOD=full_debug -S /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/cmake/machine-files/mappy.cmake -DNetCDF_Fortran_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DNetCDF_C_PATH=/projects/sems/install/rhel7-x86_64/sems/tpl/netcdf/4.7.3/gcc/9.2.0/openmpi/4.0.2/parallel -DCMAKE_BUILD_TYPE=Debug -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DSCREAM_AUTOTESTER='ON' -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicxx -DCMAKE_C_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/9.2.0/openmpi/4.0.2/bin/mpifort -DSCREAM_DYNAMICS_DYCORE=HOMME -DSCREAM_TEST_MAX_TOTAL_THREADS=32 -DSCREAM_TEST_DATA_DIR=/sems-data-store/ACME/baselines/scream/master-baselines/full_debug/data" '
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream/ctest-build/full_debug
OVERALL STATUS: PASS
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2553/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP [...]

2022-05-18 16:41 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-05-18 16:48 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2558</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3212</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3333</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: b594f094b77da982cb629d61af493a723b9b1083</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-18 17:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2558</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3212</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3333</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2558</b> (click to expand)
</summary>
<pre>
<code>
38:dyn_grid_io_np4

Build type release failed. Here's a list of failed tests:
35:dyn_grid_io_np1
36:dyn_grid_io_np2
37:dyn_grid_io_np3
38:dyn_grid_io_np4

Error(s) occurred during test phase
OVERALL STATUS: FAIL
Starting analysis on mappy with cmd: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2558/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
RUN: cd /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2558/scream/components/scream && module purge && module load sems-archive-env sems-archive-gcc/9.2.0 sems-archive-cmake/3.19.1 sems-archive-git/2.10.1 sems-archive-openmpi/4.0.2 sems-archive-netcdf/4.7.3/parallel && export OMP_PROC_BIND=spread && true &&  ./scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -c SCREAM_AUTOTESTER=ON -p -i -m mappy 
FROM: /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2558/scream/components/scream
mappy failed
+ [[ 1 != 0 ]]
+ fails=0+1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ mappy == \m\a\p\p\y ]]
+ [[ 0 == 1 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ '[' -n 1643 ']'
+ ./scripts/git-merge-ref origin/master
+ [[ 0 != 0 ]]
+ [[ 0 == 1 ]]
+ [[ 1 == 1 ]]
+ ../../cime/scripts/create_test e3sm_scream_v1 --compiler=gnu9 -c -b master
No project info available
create_test will do up to 3 tasks simultaneously
create_test will use up to 80 cores simultaneously
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.C.20220518_105602_5th47s
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9.C.20220518_105602_5th47s
Creating test directory /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9.C.20220518_105602_5th47s
RUNNING TESTS:
  SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9
  SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.587298 seconds (PASS)
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.589473 seconds (PASS)
Finished CREATE_NEWCASE for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.589514 seconds (PASS)
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 0.447479 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 0.452745 seconds (PASS)
Finished XML for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 0.473467 seconds (PASS)
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 with 1 procs
Starting SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 in 3.045501 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 with 1 procs
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 in 3.460332 seconds (PASS)
Finished SETUP for test SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9 in 3.484566 seconds (PASS)
Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P24x1.n [...]

2022-05-18 21:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2563</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3217</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3338</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: b594f094b77da982cb629d61af493a723b9b1083</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-18 21:52 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has commited a change to the PR before testing completed.  The original testing SHA = b594f094b77da982cb629d61af493a723b9b1083 Does not match the current commit SHA = 562cd541e76ba939fd505ae9679045e8e52690c2.  The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

2022-05-18 21:52 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2563</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3217</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3338</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>b594f094b77da982cb629d61af493a723b9b1083</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Mappy # 2563</b> (click to expand)
</summary>
<pre>
<code>
        Start  89: p3_run_and_cmp_cxx_fail_omp16
191/203 Test  #87: p3_run_and_cmp_cxx_omp16 ......................   Passed    5.53 sec
        Start  99: shoc_tests_omp8
192/203 Test  #99: shoc_tests_omp8 ...............................   Passed    3.50 sec
        Start 100: shoc_tests_omp9
178/199 Test  #70: p3_tests_omp16 ................................   Passed    7.43 sec
        Start  82: p3_tests_fail_omp12
193/203 Test #100: shoc_tests_omp9 ...............................   Passed    3.81 sec
        Start 101: shoc_tests_omp10
194/203 Test  #89: p3_run_and_cmp_cxx_fail_omp16 .................   Passed    7.54 sec
        Start 102: shoc_tests_omp11
195/203 Test #101: shoc_tests_omp10 ..............................   Passed    3.29 sec
        Start 103: shoc_tests_omp12
196/203 Test #102: shoc_tests_omp11 ..............................   Passed    3.33 sec
        Start 104: shoc_tests_omp13
197/203 Test #103: shoc_tests_omp12 ..............................   Passed    3.25 sec
        Start 105: shoc_tests_omp14
179/199 Test  #82: p3_tests_fail_omp12 ...........................   Passed    6.74 sec
        Start  83: p3_tests_fail_omp13
198/203 Test #104: shoc_tests_omp13 ..............................   Passed    3.26 sec
        Start 106: shoc_tests_omp15
199/203 Test #105: shoc_tests_omp14 ..............................   Passed    2.92 sec
        Start 107: shoc_tests_omp16
200/203 Test #106: shoc_tests_omp15 ..............................   Passed    2.80 sec
        Start 108: shoc_run_and_cmp_cxx_omp16
201/203 Test #108: shoc_run_and_cmp_cxx_omp16 ....................   Passed    2.13 sec
        Start 109: shoc_run_and_cmp_f90_omp16
202/203 Test #109: shoc_run_and_cmp_f90_omp16 ....................   Passed    0.66 sec
203/203 Test #107: shoc_tests_omp16 ..............................   Passed    3.13 sec

98% tests passed, 4 tests failed out of 203

Label Time Summary:
cld             = 3868.71 sec*proc (28 tests)
cld_fraction    =   0.56 sec*proc (1 test)
diagnostics     =   0.70 sec*proc (1 test)
driver          = 2466.73 sec*proc (23 tests)
dynamics        = 2486.48 sec*proc (29 tests)
fail            = 974.34 sec*proc (19 tests)
io              =  75.21 sec*proc (16 tests)
p3              = 6362.61 sec*proc (71 tests)
physics         = 6906.63 sec*proc (95 tests)
rrtmgp          = 4109.74 sec*proc (38 tests)
shoc            = 3950.17 sec*proc (36 tests)
spa             = 1229.59 sec*proc (27 tests)

Total Test time (real) = 271.83 sec

The following tests FAILED:
	 35 - dyn_grid_io_np1 (Failed)
	 36 - dyn_grid_io_np2 (Failed)
	 37 - dyn_grid_io_np3 (Failed)
	 38 - dyn_grid_io_np4 (Failed)
CMake Error at /home/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2563/scream/components/scream/cmake/ctest_script.cmake:76 (message):
  Test had fails


180/199 Test  #83: p3_tests_fail_omp13 ...........................   Passed    6.45 sec
        Start  84: p3_tests_fail_omp14
181/199 Test  #84: p3_tests_fail_omp14 ...........................   Passed    5.94 sec
        Start  85: p3_tests_fail_omp15
182/199 Test  #85: p3_tests_fail_omp15 ...........................   Passed    5.62 sec
        Start  86: p3_tests_fail_omp16
183/199 Test  #86: p3_tests_fail_omp16 ...........................   Passed    6.33 sec
        Start 100: shoc_tests_omp12
184/199 Test #100: shoc_tests_omp12 ..............................   Passed    3.34 sec
        Start 101: shoc_tests_omp13
185/199 Test #101: shoc_tests_omp13 ..............................   Passed    3.19 sec
        Start 102: shoc_tests_omp14
186/199 Test #102: shoc_tests_omp14 ..............................   Passed    2.83 sec
        Start 103: shoc_tests_omp15
187/199 Test #103: shoc_tests_omp15 ..............................   Passed    2.74 sec
        Start 104: shoc_tests_omp16
188/199 Test #104: shoc_tests_omp16 ..............................   Passed    2.72 sec
189/199 Test #193: homme_shoc_cld_spa_p3_rrtmgp_np1 ..............   Passed  261.90 sec
190/199 Test #196: homme_shoc_cld_spa_p3_rrtmgp_np4 ..............   Passed  192.39 sec
191/199 Test #179: homme_shoc_cld_p3_rrtmgp_np2 ..................   Passed  286.99 sec
192/199 Test #194: homme_shoc_cld_spa_p3_rrtmgp_np2 ..............   Passed  286.04 sec
 [...]

2022-05-18 22:32 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2565</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3219</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3340</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/scorpio_free_decomp_memory</li>
    <li>SHA: 562cd541e76ba939fd505ae9679045e8e52690c2</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2022-05-18 23:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2565</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3219</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3340</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>562cd541e76ba939fd505ae9679045e8e52690c2</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2022-05-18 23:22 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2022-05-18 23:22 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-05-18 23:48 UTC, bartgol requested changes
I think we should scale down the log level for these fine grain details. I suggested a "debug" level.

2022-05-18 23:48 UTC, bartgol commented on components/scream/src/share/atm_process/atmosphere_process_group.cpp
> +    m_atm_logger->info("[EAMxx::run_sequential::"+atm_proc->name()+"] memory usage: " + std::to_string(max_mem_usage) + "MB");
Imho, reporting mem usage of all atm procs during each timestep is more of a "debug" log level than an "info" log level.

2022-05-18 23:48 UTC, bartgol commented on components/scream/src/control/atmosphere_driver.cpp
> +  m_atm_logger->info("[EAMxx::init::initialize_fields] memory usage: " + std::to_string(max_mem_usage) + "MB");
These new calls to the memory usage in the middle of init sequence seems more of a "debug" log level than "info"...

2022-05-18 23:48 UTC, bartgol commented on components/scream/src/share/atm_process/atmosphere_process_group.cpp
> +    m_atm_logger->info("[EAMxx::initialize::"+atm_proc->name()+"] memory usage: " + std::to_string(max_mem_usage) + "MB");
Here too. The AD already reports a total ATM memory usage right after all atm procs are inited. This is more fine grained, which probably is better suited for "debug" level.

2022-05-18 23:48 UTC, bartgol commented on components/scream/src/share/atm_process/atmosphere_process_group.cpp
> +    m_atm_logger->info("[EAMxx::finalize::"+atm_proc->name()+"] memory usage: " + std::to_string(max_mem_usage) + "MB");
Here too: "debug" level seems better suited for fine grain stuff like this.

2022-05-18 23:48 UTC, bartgol commented on components/scream/src/control/atmosphere_driver.cpp
> +  m_atm_logger->info("[EAMxx::finalize] memory usage: " + std::to_string(max_mem_usage) + "MB");
Debug here too?

2022-05-19 00:09 UTC, AaronDonahue commented
@bartgol , good points on the "info" vs. "debug" level.  I made the changes and got them all, I think.  When you get a chance go ahead and re-review.

2022-05-19 00:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-05-19 00:24 UTC, bartgol approved these changes

2022-05-19 00:50 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2566</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2375c0f5333b047ddf3029d1b104335ba8846b1a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3220</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2375c0f5333b047ddf3029d1b104335ba8846b1a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3341</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;B4B;I/O;AT: RETEST;AT: AUTOMERGE;priority:high;CIME;SPA</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1643</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/scorpio_free_decomp_memory</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2375c0f5333b047ddf3029d1b104335ba8846b1a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f6b973968f1da9db17e3a3062a7c99718ff4c4c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2022-05-19 00:50 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ bartgol ]!

2022-05-19 00:50 UTC, merged

2022-05-19 00:50 UTC, E3SM-Autotester commented
Merge on Pull Request# 1643: IS A SUCCESS - Pull Request successfully merged