Jgfouca/upstream merge 2022 07 26
E3SM-Project/scream pull request #1821
Opened 2022-07-26 19:58 UTC by jgfouca

Conflict summary:

### File: components/eam/bld/build-namelist

```
<<<<<<< HEAD
    if ($chem eq 'none' or $chem eq 'spa' or $chem eq 'waccm_ghg' or $chem eq 'super_fast_llnl' or $chem eq 'waccm_mozart' or $chem eq 'waccm_mozart_sulfur') {
        # If no chemistry then there must be prescribed aerosols unless physics
        # package is adiabatic or ideal.
        if ($phys eq 'default') {
            $prescribed_aero_model = 'modal';
        }
        elsif ($phys eq 'cam4' or $phys eq 'cam3') {
            $prescribed_aero_model = 'bulk';
        }
=======
    if ($chem eq 'none' or $chem eq 'waccm_ghg' or $chem eq 'super_fast_llnl' or $chem eq 'waccm_mozart' or $chem eq 'waccm_mozart_sulfur') {
        # If no chemistry then there must be prescribed aerosols unless physics
        # package is adiabatic or ideal.
        if ($phys eq 'default') {
            $prescribed_aero_model = 'modal';
        }
>>>>>>> upstream/master
```

Solution: add `$chem eq 'spa'` to upstream if statement

### File: components/eam/src/physics/cam/check_energy.F90

```
<<<<<<< HEAD
    elseif (icldliq > 1  .and.  icldice > 1 .and. irain > 1 .and. microp_scheme == 'P3') then
       ! In the case where the micro-physics scheme is P3 there is no snow
       ! constituent and isnow = -1.  So we still calculate the rest of the
       ! consituents and ensure that ws = 0.0.  NOTE! This change will likely
       ! lead to conflicts with upstream E3SM any time check_energy is
       ! changed...  The most important thing is to avoid any SNOW calculations
       ! when P3 is the microphysics scheme.
       do i = 1, ncol
          call energy_helper_eam_def_column(u(i,:),v(i,:),T(i,:),q(i,1:pver,1:pcnst),&
                                   ps(i),pdel(i,:),phis(i), &
                                   ke(i),se(i),wv(i),wl(i),wi(i),wr(i),ws(i),te(i),tw(i) )
          ws(i) = 0.0_r8
       enddo
    else
       call endrun('energy_helper...column is not implemented if water forms do not exist')
    endif
=======
    !else
    !   call endrun('energy_helper...column is not implemented if water forms do not exist')
    !endif
>>>>>>> upstream/master
```

Solution:

```
    !if (icldliq > 1  .and.  icldice > 1 .and. irain > 1 .and. isnow > 1) then
       do i = 1, ncol
          call energy_helper_eam_def_column(u(i,:),v(i,:),T(i,:),q(i,1:pver,1:pcnst),&
                                   ps(i),pdel(i,:),phis(i), &
                                   ke(i),se(i),wv(i),wl(i),wi(i),wr(i),ws(i),te(i),tw(i) )
          ! In the case where the micro-physics scheme is P3 there is no snow
          ! constituent and isnow = -1.  So we still calculate the rest of the
          ! consituents and ensure that ws = 0.0.  NOTE! This change will likely
          ! lead to conflicts with upstream E3SM any time check_energy is
          ! changed...  The most important thing is to avoid any SNOW calculations
          ! when P3 is the microphysics scheme.
          if (microp_scheme == 'P3') then
             ws(i) = 0.0_r8
          endif
       enddo
    !else
    !   call endrun('energy_helper...column is not implemented if water forms do not exist')
    !endif
```

In other words, take upstream except add the P3 check after the energy_helper call

```
<<<<<<< HEAD
    do k = 1, pver
       wr = wr + q(k,irain)*pdel(k)/gravit
       ! Recall, P3 does not have a snow constituent.
       if (.not.microp_scheme == 'P3') then
         ws = ws + q(k,isnow)*pdel(k)/gravit
       end if
    end do
=======
    if (irain > 1 .and. isnow > 1) then
       do k = 1, pver
          wr = wr + q(k,irain)*pdel(k)/gravit
          ws = ws + q(k,isnow)*pdel(k)/gravit
       end do
    end if
>>>>>>> upstream/master
```

Solution: Take upstream but add the P3 check before changing ws

### File: components/eam/src/physics/cam/phys_control.F90

```
<<<<<<< HEAD
      rrtmg_temp_fix 
=======
      rrtmg_temp_fix, ideal_phys_option
>>>>>>> upstream/master
```

Solution: Take upstream

2022-07-26 20:08 UTC, ambrad approved these changes
The radiation and build-namelist conflict resolutions look fine. Aaron should assess the P3-related ones. Ben doesn't need to review this.

2022-07-26 20:11 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-07-26 20:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2871</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>194a9372e5cb82c367153021fca7513707182055</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3499</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>194a9372e5cb82c367153021fca7513707182055</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3618</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>194a9372e5cb82c367153021fca7513707182055</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 194a9372e5cb82c367153021fca7513707182055</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-27 01:54 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-07-27 17:53 UTC, AaronDonahue commented
@jgfouca , I'm concerned about the P3 energy conservation fixes.  If P3 is active than isnow will not be >1 but irain will be and we want to still do the calculation just ignoring snow.  With the conflict fixes above I think we will just always skip adding rain to the check with P3.

2022-07-27 17:59 UTC, AaronDonahue requested changes

2022-07-27 17:59 UTC, AaronDonahue commented on components/eam/src/physics/cam/check_energy.F90
> +    if (irain > 1 .and. isnow > 1) then
I think we will need to break this if up into an `if (irain>1)` and a `if (isnow>1 && microp_scheme!="P3")` set of conditionals.

2022-07-27 17:59 UTC, AaronDonahue commented on components/eam/src/physics/cam/check_energy.F90
> +    if (irain > 1 .and. isnow > 1) then
maybe add an "else ws(i) = 0` and then we can remove the `P3` conditional up above.

2022-07-27 20:51 UTC, jgfouca commented
@AaronDonahue , ok, see if you like my latest commit.

2022-07-27 21:28 UTC, AaronDonahue requested changes
@jgfouca , looks much better.  Just one more minor fix I would suggest.

2022-07-27 21:28 UTC, AaronDonahue commented on components/eam/src/physics/cam/check_energy.F90
> +          if (microp_scheme == 'P3') then
Looks much better, not to be nitpicky but we can probably move this conditional to down below with the P3 check.  Then this chunk of code won't be too out of sync with upstream master.

2022-07-27 21:53 UTC, jgfouca commented
@AaronDonahue , done. Note that this changes behavior a bit. The `ws` field won't be zero'd in the subroutine `energy_helper_eam_def`; it will be zero'd in `energy_helper_eam_def_column`.

2022-07-27 21:54 UTC, jgfouca commented
Ah, I see `energy_helper_eam_def` calls `energy_helper_eam_def_column`. So behavior is not really changed.

2022-07-27 21:57 UTC, AaronDonahue approved these changes
@jgfouca , thanks for making the changes.  I can see that it will change the behavior a little bit but I think functionally we will get the same behavior, with ws being zero for all columns.

2022-07-28 16:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-07-28 16:41 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-07-28 16:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2874</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3502</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3621</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-28 16:48 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2874</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3502</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3621</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 2874</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2874/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using known hosts file, will automatically accept unseen keys
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/1821^{commit} # timeout=10
 > git rev-parse pr/1821^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad (pr/1821)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
Commit message: "Fix P3 irain handling"
 > git rev-list --no-walk 194a9372e5cb82c367153021fca7513707182055 # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config - [...]

2022-07-28 19:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-07-28 19:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2878</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3506</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3625</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-28 19:49 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2878</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3506</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3625</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 2878</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2878/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using known hosts file, will automatically accept unseen keys
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/1821^{commit} # timeout=10
 > git rev-parse pr/1821^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad (pr/1821)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
Commit message: "Fix P3 irain handling"
 > git rev-list --no-walk 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config - [...]

2022-07-29 00:53 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2885</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3513</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3632</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-29 00:57 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2885</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3513</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3632</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 2885</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2885/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using known hosts file, will automatically accept unseen keys
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/1821^{commit} # timeout=10
 > git rev-parse pr/1821^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad (pr/1821)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
Commit message: "Fix P3 irain handling"
 > git rev-list --no-walk 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.ext [...]

2022-07-29 05:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2892</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3520</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3639</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-29 05:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2892</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3520</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3639</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 2892</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/2892/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using known hosts file, will automatically accept unseen keys
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/1821/head:refs/heads/pr/1821 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/1821^{commit} # timeout=10
 > git rev-parse pr/1821^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad (pr/1821)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
Commit message: "Fix P3 irain handling"
 > git rev-list --no-walk 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.ext [...]

2022-07-29 22:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-07-29 22:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2898</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3526</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3645</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-29 23:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-07-29 23:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2899</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3527</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3646</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-30 00:04 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-07-30 00:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2900</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3528</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3647</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-07-30 06:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-08-01 23:47 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-08-01 23:47 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2912</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3540</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3659</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: jgfouca/upstream_merge_2022_07_26</li>
    <li>SHA: 2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jgfouca
</details>

2022-08-02 00:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 2912</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 3540</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 3659</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;AT: AUTOMERGE;CIME</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1821</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>jgfouca/upstream_merge_2022_07_26</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>2d5b0cab4c27564b2186ff7ff2d12f140d7448ad</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fef3aadab6b95ce7a845321ed5d9486e533c301f</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 2912</b> (click to expand)
</summary>
<pre>
<code>
117/220 Test  #57: p3_tests_omp3 ...........................................   Passed    5.21 sec
        Start  73: p3_tests_fail_omp3
139/219 Test  #59: p3_tests_omp5 ...........................................   Passed    5.30 sec
        Start  74: p3_tests_fail_omp4
        Start 205: restarted_vs_monolithic_check_np4
140/219 Test #205: restarted_vs_monolithic_check_np4 .......................   Passed    0.09 sec
141/219 Test  #74: p3_tests_fail_omp4 ......................................   Passed    4.95 sec
        Start  75: p3_tests_fail_omp5
118/220 Test  #73: p3_tests_fail_omp3 ......................................   Passed    5.78 sec
        Start  94: shoc_tests_omp3
142/219 Test  #60: p3_tests_omp6 ...........................................   Passed    6.50 sec
        Start  76: p3_tests_fail_omp6
119/220 Test  #94: shoc_tests_omp3 .........................................   Passed    1.95 sec
        Start 112: spa_read_data_test_np3
143/219 Test #208: homme_shoc_cld_spa_p3_rrtmgp_np3 ........................   Passed  131.08 sec
120/220 Test #203: model_baseline_np4 ......................................   Passed   35.05 sec
        Start 205: model_restart_np4
121/220 Test #112: spa_read_data_test_np3 ..................................   Passed    1.89 sec
        Start 116: spa_read_remap_test_np3
122/220 Test #116: spa_read_remap_test_np3 .................................   Passed    0.67 sec
        Start 120: spa_one_to_one_remap_test_np3
144/219 Test  #75: p3_tests_fail_omp5 ......................................   Passed    4.92 sec
        Start  46: physics_tests_omp8
145/219 Test  #46: physics_tests_omp8 ......................................   Passed    0.38 sec
        Start  61: p3_tests_omp7
146/219 Test  #76: p3_tests_fail_omp6 ......................................   Passed    4.88 sec
        Start  77: p3_tests_fail_omp7
123/220 Test #120: spa_one_to_one_remap_test_np3 ...........................   Passed    1.72 sec
147/219 Test  #61: p3_tests_omp7 ...........................................   Passed    4.89 sec
        Start  95: shoc_tests_omp4
148/219 Test  #77: p3_tests_fail_omp7 ......................................   Passed    5.03 sec
        Start  47: physics_tests_omp9
149/219 Test  #47: physics_tests_omp9 ......................................   Passed    0.49 sec
        Start  48: physics_tests_omp10
150/219 Test  #48: physics_tests_omp10 .....................................   Passed    0.46 sec
        Start  62: p3_tests_omp8
151/219 Test  #95: shoc_tests_omp4 .........................................   Passed    2.34 sec
        Start  96: shoc_tests_omp5
152/219 Test  #96: shoc_tests_omp5 .........................................   Passed    1.90 sec
        Start  97: shoc_tests_omp6
153/219 Test  #97: shoc_tests_omp6 .........................................   Passed    1.73 sec
        Start 113: spa_read_data_test_np4
154/219 Test  #62: p3_tests_omp8 ...........................................   Passed    5.11 sec
        Start  63: p3_tests_omp9
155/219 Test #113: spa_read_data_test_np4 ..................................   Passed    1.46 sec
        Start 117: spa_read_remap_test_np4
156/219 Test #117: spa_read_remap_test_np4 .................................   Passed    0.49 sec
        Start 121: spa_one_to_one_remap_test_np4
157/219 Test #121: spa_one_to_one_remap_test_np4 ...........................   Passed    1.41 sec
124/220 Test #205: model_restart_np4 .......................................   Passed   16.94 sec
        Start 210: homme_shoc_cld_spa_p3_rrtmgp_np4
        Start 206: restarted_vs_monolithic_check_np4
125/220 Test #206: restarted_vs_monolithic_check_np4 .......................   Passed    0.05 sec
158/219 Test  #63: p3_tests_omp9 ...........................................   Passed    5.58 sec
        Start  49: physics_tests_omp11
159/219 Test  #49: physics_tests_omp11 .....................................   Passed    0.27 sec
        Start  50: physics_tests_omp12
160/219 Test  #50: physics_tests_omp12 .....................................   Passed    0.27 sec
        Start  51: physics_tests_omp13
161/219 Test  #51: physics_tests_omp13 .....................................   Passed    0.27 sec
        Start  52: physics_tests_omp14
162/219 Test  #52: physics_tests_omp14 .....................................   Pa [...]

2022-08-02 05:51 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2022-08-02 15:17 UTC, merged