Add U and V subfields of horiz_winds to the field manager
E3SM-Project/scream pull request #2172
Opened 2023-02-14 00:59 UTC by bartgol

Allows to save U and V separately in the output NC files.

2023-02-14 01:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-14 01:13 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3544</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4142</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4200</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 147659fdd1e92b4b385a3b558d47d1ed814d857e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-14 01:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3544</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4142</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4200</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3544</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/3544/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using manually-configured host key entries
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/2172^{commit} # timeout=10
 > git rev-parse pr/2172^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 147659fdd1e92b4b385a3b558d47d1ed814d857e (pr/2172)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 147659fdd1e92b4b385a3b558d47d1ed814d857e # timeout=10
Commit message: "EAMxx: make U and V available in the field managers"
First time build. Skipping changelog.
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/YAKL.path # timeout=10
 > g [...]

2023-02-14 05:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3545</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4143</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4201</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 147659fdd1e92b4b385a3b558d47d1ed814d857e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-14 05:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3545</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4143</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4201</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3545</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/3545/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using manually-configured host key entries
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/2172^{commit} # timeout=10
 > git rev-parse pr/2172^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 147659fdd1e92b4b385a3b558d47d1ed814d857e (pr/2172)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 147659fdd1e92b4b385a3b558d47d1ed814d857e # timeout=10
Commit message: "EAMxx: make U and V available in the field managers"
 > git rev-list --no-walk 147659fdd1e92b4b385a3b558d47d1ed814d857e # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submo [...]

2023-02-14 10:13 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3546</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4144</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4202</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 147659fdd1e92b4b385a3b558d47d1ed814d857e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-14 10:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3546</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4144</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4202</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3546</b> (click to expand)
</summary>
<pre>
<code>
Running as SYSTEM
Building remotely on mappy in workspace /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy
The recommended git tool is: NONE
using credential cf1815d3-62c3-4157-a38d-0ad235093618
Cloning the remote Git repository
Honoring refspec on initial clone
Cloning repository https://github.com/E3SM-Project/scream.git
 > git init /ascldap/users/e3sm-jenkins/jenkins-ws/workspace/SCREAM_PullRequest_Autotester_Mappy/3546/scream # timeout=10
Fetching upstream changes from https://github.com/E3SM-Project/scream.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials jgfouca github key
Verifying host key using manually-configured host key entries
Setting http proxy: proxy.sandia.gov:80
 > git fetch --tags --progress https://github.com/E3SM-Project/scream.git +refs/heads/master:refs/remotes/origin/master +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
 > git config remote.origin.url https://github.com/E3SM-Project/scream.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config --add remote.origin.fetch +refs/pull/2172/head:refs/heads/pr/2172 # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/pr/2172^{commit} # timeout=10
 > git rev-parse pr/2172^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://plugins.jenkins.io/git/#remove-git-plugin-buildsbybranch-builddata-script
Checking out Revision 147659fdd1e92b4b385a3b558d47d1ed814d857e (pr/2172)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 147659fdd1e92b4b385a3b558d47d1ed814d857e # timeout=10
Commit message: "EAMxx: make U and V available in the field managers"
 > git rev-list --no-walk 147659fdd1e92b4b385a3b558d47d1ed814d857e # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule init # timeout=10
 > git config -f .gitmodules --get-regexp ^submodule\.(.+)\.url # timeout=10
 > git config --get submodule.fates.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.fates.path # timeout=10
 > git config --get submodule.alm-mpp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.alm-mpp.path # timeout=10
 > git config --get submodule.sbetr.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.sbetr.path # timeout=10
 > git config --get submodule.externals/kokkos.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/kokkos.path # timeout=10
 > git config --get submodule.rrtmgp.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.rrtmgp.path # timeout=10
 > git config --get submodule.externals/scorpio.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio.path # timeout=10
 > git config --get submodule.externals/scorpio_classic.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/scorpio_classic.path # timeout=10
 > git config --get submodule.cosp2.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cosp2.path # timeout=10
 > git config --get submodule.cime.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.cime.path # timeout=10
 > git config --get submodule.externals/ekat.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submodule.externals/ekat.path # timeout=10
 > git config --get submodule.externals/YAKL.url # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git config -f .gitmodules --get submo [...]

2023-02-14 15:57 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2023-02-14 16:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3547</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4145</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4203</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 147659fdd1e92b4b385a3b558d47d1ed814d857e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-14 16:54 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3547</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4145</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4203</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>147659fdd1e92b4b385a3b558d47d1ed814d857e</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2023-02-14 16:55 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2023-02-14 16:55 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-02-14 17:00 UTC, AaronDonahue requested changes
Thanks for putting this in so quickly Luca.  Just one question, would it be possible to add a unit test for u/v?  Maybe a quick run where we write `horiz_winds` and `u` and `v` and check that u=horiz_winds(0) and v=horiz_winds(1)?

2023-02-14 17:05 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2023-02-14 17:05 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-02-14 17:08 UTC, bartgol commented
> Thanks for putting this in so quickly Luca. Just one question, would it be possible to add a unit test for u/v? Maybe a quick run where we write `horiz_winds` and `u` and `v` and check that u=horiz_winds(0) and v=horiz_winds(1)?

That would be nice. I'm not sure how to proceed though, since it probably requires manipulating output files with NCO tools. I'll think about it.

2023-02-15 00:09 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-15 00:10 UTC, bartgol commented
@AaronDonahue Crafting a script that compares vars in two nc files (possibly subsliced) wasn't really hard, especially since some of the boilerplate netcdf stuff was already in other scripts we have.

I added U and V in the output of  shoc_standalone, and added unit tests that verify U/V are correctly subviewing the horiz_winds field. I used uppercase for the fields, but we can change to lowercase if that's what existing postprocessing scripts would expect.

2023-02-15 00:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3548</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4146</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4204</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 8df14a5897ac3fa87801533954f6a75c5de3ae27</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-15 00:49 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3548</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4146</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4204</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8df14a5897ac3fa87801533954f6a75c5de3ae27</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3548</b> (click to expand)
</summary>
<pre>
<code>
        Start 116: shoc_tests_omp8
186/269 Test #125: shoc_sk_tests_omp4 ........................................   Passed    0.62 sec
        Start 126: shoc_sk_tests_omp5
187/269 Test #126: shoc_sk_tests_omp5 ........................................   Passed    0.57 sec
        Start 141: spa_read_data_test_np4
188/269 Test  #92: p3_tests_fail_omp5 ........................................   Passed    5.26 sec
        Start  93: p3_tests_fail_omp6
221/274 Test #116: shoc_tests_omp8 ...........................................   Passed    1.84 sec
        Start 117: shoc_tests_omp9
189/269 Test #141: spa_read_data_test_np4 ....................................   Passed    2.20 sec
        Start 145: spa_one_to_one_remap_test_np4
222/274 Test #117: shoc_tests_omp9 ...........................................   Passed    1.66 sec
        Start 118: shoc_tests_omp10
223/274 Test  #97: p3_tests_fail_omp10 .......................................   Passed    5.91 sec
        Start 131: shoc_sk_tests_omp7
224/274 Test #131: shoc_sk_tests_omp7 ........................................   Passed    0.71 sec
        Start 132: shoc_sk_tests_omp8
190/269 Test #145: spa_one_to_one_remap_test_np4 .............................   Passed    1.36 sec
        Start 210: surface_coupling_np4
225/274 Test #118: shoc_tests_omp10 ..........................................   Passed    1.66 sec
        Start  83: p3_tests_omp12
226/274 Test #132: shoc_sk_tests_omp8 ........................................   Passed    0.80 sec
191/269 Test #210: surface_coupling_np4 ......................................   Passed    0.80 sec
192/269 Test  #93: p3_tests_fail_omp6 ........................................   Passed    5.35 sec
        Start  62: physics_tests_omp7
193/269 Test  #62: physics_tests_omp7 ........................................   Passed    0.25 sec
        Start  63: physics_tests_omp8
194/269 Test  #63: physics_tests_omp8 ........................................   Passed    0.26 sec
        Start  64: physics_tests_omp9
195/269 Test  #64: physics_tests_omp9 ........................................   Passed    0.24 sec
        Start  65: physics_tests_omp10
196/269 Test  #65: physics_tests_omp10 .......................................   Passed    0.24 sec
        Start  78: p3_tests_omp7
227/274 Test #233: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  276.85 sec
        Start 133: shoc_sk_tests_omp9
228/274 Test #133: shoc_sk_tests_omp9 ........................................   Passed    0.68 sec
        Start 237: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
229/274 Test #237: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb .....................   Passed    0.06 sec
        Start 238: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
230/274 Test #238: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.07 sec
        Start 239: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
231/274 Test #239: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.06 sec
232/274 Test  #83: p3_tests_omp12 ............................................   Passed    4.45 sec
        Start  84: p3_tests_omp13
197/269 Test #228: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  294.32 sec
        Start 232: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
198/269 Test #232: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb .....................   Passed    0.06 sec
        Start 233: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
199/269 Test #254: homme_shoc_cld_spa_p3_rrtmgp_np2 ..........................   Passed  264.49 sec
200/269 Test #233: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.11 sec
        Start 111: shoc_tests_omp6
201/269 Test  #78: p3_tests_omp7 .............................................   Passed    3.34 sec
        Start  94: p3_tests_fail_omp7
202/269 Test #111: shoc_tests_omp6 ...........................................   Passed    1.82 sec
        Start 127: shoc_sk_tests_omp6
203/269 Test #127: shoc_sk_tests_omp6 ........................................   Passed    0.68 sec
        Start 234: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
204/269 Test #234: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.06 sec
233/274 Test  #84: p3_tests_omp13 ............................................   Passed    4.83 sec
        Start  85: p3_tests_omp14
205/269 Test  #94: p3_tests_fail_omp7 .......... [...]

2023-02-15 01:09 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-15 01:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3549</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4147</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4205</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 602c6613997e112e540d459e17fce3d3abd83b8d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-15 02:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3549</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4147</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4205</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3549</b> (click to expand)
</summary>
<pre>
<code>
156/269 Test  #50: homme_pd_remap_np3 ........................................   Passed    0.67 sec
        Start  54: dyn_grid_io_np3
157/269 Test  #46: horizontal_remap_np3 ......................................   Passed    0.99 sec
        Start  58: physics_tests_omp3
158/269 Test  #58: physics_tests_omp3 ........................................   Passed    0.29 sec
        Start  74: p3_tests_omp3
159/269 Test  #54: dyn_grid_io_np3 ...........................................   Passed    0.63 sec
        Start  90: p3_tests_fail_omp3
232/274 Test  #84: p3_tests_omp13 ............................................   Passed    4.96 sec
        Start  85: p3_tests_omp14
160/269 Test  #74: p3_tests_omp3 .............................................   Passed    4.19 sec
        Start 108: shoc_tests_omp3
161/269 Test   #4: io_test_np4 ...............................................   Passed   27.53 sec
        Start   8: io_test_se_grid_np4
162/269 Test   #8: io_test_se_grid_np4 .......................................   Passed    0.64 sec
        Start  20: io_remap_test_np4
163/269 Test  #90: p3_tests_fail_omp3 ........................................   Passed    5.33 sec
        Start 124: shoc_sk_tests_omp3
164/269 Test #108: shoc_tests_omp3 ...........................................   Passed    1.74 sec
        Start 140: spa_read_data_test_np3
165/269 Test #124: shoc_sk_tests_omp3 ........................................   Passed    0.63 sec
        Start 144: spa_one_to_one_remap_test_np3
233/274 Test  #85: p3_tests_omp14 ............................................   Passed    4.79 sec
        Start  86: p3_tests_omp15
166/269 Test #144: spa_one_to_one_remap_test_np3 .............................   Passed    1.91 sec
        Start 209: surface_coupling_np3
167/269 Test #140: spa_read_data_test_np3 ....................................   Passed    2.21 sec
168/269 Test  #20: io_remap_test_np4 .........................................   Passed    2.93 sec
        Start  28: field_utils_np4
169/269 Test  #28: field_utils_np4 ...........................................   Passed    0.35 sec
        Start  33: grid_np4
170/269 Test #209: surface_coupling_np3 ......................................   Passed    0.73 sec
        Start  37: coarsening_remapper_np4
171/269 Test  #33: grid_np4 ..................................................   Passed    0.35 sec
        Start  41: vertical_remapper_np4
172/269 Test  #41: vertical_remapper_np4 .....................................   Passed    0.46 sec
        Start  47: horizontal_remap_np4
173/269 Test #228: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  264.86 sec
        Start 232: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
174/269 Test  #37: coarsening_remapper_np4 ...................................   Passed    1.09 sec
        Start  51: homme_pd_remap_np4
175/269 Test #232: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb .....................   Passed    0.06 sec
        Start 233: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
176/269 Test #233: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.06 sec
        Start 234: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
177/269 Test #234: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.06 sec
178/269 Test  #47: horizontal_remap_np4 ......................................   Passed    0.97 sec
        Start  55: dyn_grid_io_np4
179/269 Test  #51: homme_pd_remap_np4 ........................................   Passed    0.64 sec
        Start  59: physics_tests_omp4
180/269 Test  #59: physics_tests_omp4 ........................................   Passed    0.34 sec
        Start  60: physics_tests_omp5
181/269 Test  #55: dyn_grid_io_np4 ...........................................   Passed    0.70 sec
        Start  61: physics_tests_omp6
182/269 Test  #60: physics_tests_omp5 ........................................   Passed    0.31 sec
        Start  75: p3_tests_omp4
183/269 Test  #61: physics_tests_omp6 ........................................   Passed    0.26 sec
        Start  62: physics_tests_omp7
184/269 Test  #62: physics_tests_omp7 ........................................   Passed    0.24 sec
        Start  76: p3_tests_omp5
234/274 Test  #86: p3_tests_omp15 ............................................   Passed    4.72 sec
        Start  87: p3_tests_omp16
185/269 Test  #75: p3_tests_omp4 ........ [...]

2023-02-15 07:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2023-02-15 11:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3551</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4149</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4207</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 602c6613997e112e540d459e17fce3d3abd83b8d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-15 12:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3551</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4149</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4207</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>602c6613997e112e540d459e17fce3d3abd83b8d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>ec5d77e24f53e7a41a80a14ba61799f5c3e8a4a4</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3551</b> (click to expand)
</summary>
<pre>
<code>
        Start   8: io_test_se_grid_np4
211/274 Test #243: homme_shoc_cld_p3_rrtmgp_np1 ..............................   Passed  245.87 sec
        Start 247: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
212/274 Test #247: homme_shoc_cld_p3_rrtmgp_np1_vs_np2_bfb ...................   Passed    0.04 sec
        Start 248: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
213/274 Test #248: homme_shoc_cld_p3_rrtmgp_np1_vs_np3_bfb ...................   Passed    0.04 sec
        Start 249: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
214/274 Test #249: homme_shoc_cld_p3_rrtmgp_np1_vs_np4_bfb ...................   Passed    0.04 sec
167/269 Test   #8: io_test_se_grid_np4 .......................................   Passed    0.63 sec
        Start  20: io_remap_test_np4
168/269 Test #241: homme_shoc_cld_p3_rrtmgp_np4 ..............................   Passed  113.21 sec
        Start  28: field_utils_np4
169/269 Test  #28: field_utils_np4 ...........................................   Passed    0.36 sec
        Start  33: grid_np4
170/269 Test  #20: io_remap_test_np4 .........................................   Passed    2.28 sec
        Start  37: coarsening_remapper_np4
171/269 Test  #33: grid_np4 ..................................................   Passed    0.34 sec
        Start  41: vertical_remapper_np4
172/269 Test  #41: vertical_remapper_np4 .....................................   Passed    0.40 sec
        Start  47: horizontal_remap_np4
173/269 Test  #37: coarsening_remapper_np4 ...................................   Passed    1.30 sec
        Start  51: homme_pd_remap_np4
215/274 Test #261: homme_shoc_cld_spa_p3_rrtmgp_np4 ..........................   Passed   94.37 sec
        Start  96: p3_tests_fail_omp9
174/269 Test  #47: horizontal_remap_np4 ......................................   Passed    0.98 sec
        Start  55: dyn_grid_io_np4
216/274 Test  #81: p3_tests_omp10 ............................................   Passed    5.54 sec
        Start  82: p3_tests_omp11
175/269 Test  #51: homme_pd_remap_np4 ........................................   Passed    0.76 sec
        Start  59: physics_tests_omp4
176/269 Test  #55: dyn_grid_io_np4 ...........................................   Passed    0.61 sec
        Start  60: physics_tests_omp5
177/269 Test  #59: physics_tests_omp4 ........................................   Passed    0.29 sec
        Start  75: p3_tests_omp4
178/269 Test  #60: physics_tests_omp5 ........................................   Passed    0.25 sec
        Start  61: physics_tests_omp6
179/269 Test  #61: physics_tests_omp6 ........................................   Passed    0.25 sec
        Start  76: p3_tests_omp5
217/274 Test  #96: p3_tests_fail_omp9 ........................................   Passed    4.51 sec
        Start 115: shoc_tests_omp7
180/269 Test  #76: p3_tests_omp5 .............................................   Passed    3.50 sec
        Start  77: p3_tests_omp6
218/274 Test  #82: p3_tests_omp11 ............................................   Passed    4.77 sec
        Start  83: p3_tests_omp12
181/269 Test  #75: p3_tests_omp4 .............................................   Passed    4.89 sec
        Start  91: p3_tests_fail_omp4
219/274 Test #115: shoc_tests_omp7 ...........................................   Passed    1.91 sec
        Start 116: shoc_tests_omp8
182/269 Test  #77: p3_tests_omp6 .............................................   Passed    3.27 sec
        Start  92: p3_tests_fail_omp5
220/274 Test #116: shoc_tests_omp8 ...........................................   Passed    1.90 sec
        Start 131: shoc_sk_tests_omp7
221/274 Test #131: shoc_sk_tests_omp7 ........................................   Passed    0.79 sec
        Start 132: shoc_sk_tests_omp8
222/274 Test #132: shoc_sk_tests_omp8 ........................................   Passed    0.98 sec
223/274 Test  #83: p3_tests_omp12 ............................................   Passed    4.79 sec
        Start  71: physics_tests_omp16
224/274 Test  #71: physics_tests_omp16 .......................................   Passed    0.26 sec
        Start  84: p3_tests_omp13
183/269 Test  #91: p3_tests_fail_omp4 ........................................   Passed    5.71 sec
        Start 109: shoc_tests_omp4
184/269 Test  #92: p3_tests_fail_omp5 ........................................   Passed    4.03 sec
        Start  93: p3_tests_fail_omp6
185/269 Test #10 [...]

2023-02-15 17:12 UTC, AaronDonahue commented on components/eamxx/tests/uncoupled/shoc/CMakeLists.txt
> +# These tests ensure that the compare-nc-files script does always pass
do you mean "doesn't" always pass?

2023-02-15 17:14 UTC, AaronDonahue approved these changes
@bartgol , thank you for adding the test and a tool that we can use for other unit tests.  It looks like weaver still has some issues with installing netCDF, but I approve of the changes.  Ping me to reapprove whenever the netCDF weaver stuff gets sorted out.

2023-02-16 19:38 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-16 19:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2023-02-16 20:39 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-16 20:42 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3562</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4160</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4218</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: 93823e5634ceb2be055d1e4a1701e1ef6e033610</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-16 21:09 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3562</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4160</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4218</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>93823e5634ceb2be055d1e4a1701e1ef6e033610</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3562</b> (click to expand)
</summary>
<pre>
<code>
219/278 Test  #68: physics_tests_omp13 .......................................   Passed    0.32 sec
        Start  69: physics_tests_omp14
220/278 Test  #69: physics_tests_omp14 .......................................   Passed    0.31 sec
        Start  70: physics_tests_omp15
221/278 Test  #70: physics_tests_omp15 .......................................   Passed    0.32 sec
        Start  71: physics_tests_omp16
222/278 Test  #71: physics_tests_omp16 .......................................   Passed    0.31 sec
        Start  81: p3_tests_omp10
166/273 Test #243: homme_shoc_cld_p3_rrtmgp_np2 ..............................   Passed  218.28 sec
        Start 229: shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
167/273 Test #229: shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .........................   Passed    0.10 sec
        Start 230: shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
168/273 Test #230: shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .........................   Passed    0.17 sec
        Start 231: shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
169/273 Test #231: shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .........................   Passed    0.17 sec
223/278 Test  #81: p3_tests_omp10 ............................................   Passed    4.75 sec
        Start  82: p3_tests_omp11
224/278 Test #265: homme_shoc_cld_spa_p3_rrtmgp_np4 ..........................   Passed   94.38 sec
        Start  96: p3_tests_fail_omp9
225/278 Test  #82: p3_tests_omp11 ............................................   Passed    4.58 sec
        Start  97: p3_tests_fail_omp10
226/278 Test  #96: p3_tests_fail_omp9 ........................................   Passed    4.27 sec
        Start 117: shoc_tests_omp9
227/278 Test #117: shoc_tests_omp9 ...........................................   Passed    1.67 sec
        Start 118: shoc_tests_omp10
170/273 Test   #4: io_test_np4 ...............................................   Passed   24.46 sec
        Start   8: io_test_se_grid_np4
228/278 Test #118: shoc_tests_omp10 ..........................................   Passed    1.72 sec
        Start 132: shoc_sk_tests_omp8
171/273 Test   #8: io_test_se_grid_np4 .......................................   Passed    1.20 sec
        Start  20: io_remap_test_np4
229/278 Test #132: shoc_sk_tests_omp8 ........................................   Passed    0.73 sec
        Start 133: shoc_sk_tests_omp9
230/278 Test #133: shoc_sk_tests_omp9 ........................................   Passed    0.70 sec
        Start 134: shoc_sk_tests_omp10
231/278 Test  #97: p3_tests_fail_omp10 .......................................   Passed    5.72 sec
232/278 Test #134: shoc_sk_tests_omp10 .......................................   Passed    0.70 sec
        Start  83: p3_tests_omp12
172/273 Test  #20: io_remap_test_np4 .........................................   Passed    2.27 sec
        Start  28: field_utils_np4
173/273 Test  #28: field_utils_np4 ...........................................   Passed    0.33 sec
        Start  33: grid_np4
174/273 Test  #33: grid_np4 ..................................................   Passed    0.36 sec
        Start  37: coarsening_remapper_np4
175/273 Test  #37: coarsening_remapper_np4 ...................................   Passed    1.06 sec
        Start  41: vertical_remapper_np4
176/273 Test  #41: vertical_remapper_np4 .....................................   Passed    0.40 sec
        Start  47: horizontal_remap_np4
177/273 Test  #47: horizontal_remap_np4 ......................................   Passed    0.89 sec
        Start  51: homme_pd_remap_np4
233/278 Test #237: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  273.66 sec
        Start 241: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
234/278 Test #241: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb .....................   Passed    0.12 sec
        Start 242: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
235/278 Test #242: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.09 sec
        Start 243: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
178/273 Test  #51: homme_pd_remap_np4 ........................................   Passed    0.66 sec
        Start  55: dyn_grid_io_np4
236/278 Test #243: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.06 sec
179/273 Test  #55: dyn_grid_io_np4 ...........................................   Passed    0.59 sec
        Start  59: physics_tests_omp4
237/278 Test  #83: p3_tests_om [...]

2023-02-16 23:00 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-02-16 23:01 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3564</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4162</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4220</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: f5abed245c37b515f5965617574514d23e5addb4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-17 00:18 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3564</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4162</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4220</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3564</b> (click to expand)
</summary>
<pre>
<code>
218/273 Test #263: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_output_bfb ........   Passed    0.07 sec
        Start 264: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_diagnostics_bfb
219/273 Test #264: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np3_diagnostics_bfb ...   Passed    0.02 sec
        Start 265: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_output_bfb
220/273 Test #265: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_output_bfb ........   Passed    0.06 sec
        Start 266: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_diagnostics_bfb
221/273 Test #266: homme_shoc_cld_spa_p3_rrtmgp_np1_vs_np4_diagnostics_bfb ...   Passed    0.03 sec
226/278 Test #114: shoc_tests_omp6 ...........................................   Passed   62.53 sec
        Start  64: physics_tests_omp9
227/278 Test  #64: physics_tests_omp9 ........................................   Passed    1.06 sec
        Start  65: physics_tests_omp10
228/278 Test  #65: physics_tests_omp10 .......................................   Passed    1.01 sec
        Start  66: physics_tests_omp11
222/273 Test  #79: p3_tests_omp8 .............................................   Passed   64.79 sec
        Start  80: p3_tests_omp9
229/278 Test  #66: physics_tests_omp11 .......................................   Passed    1.25 sec
        Start  80: p3_tests_omp9
223/273 Test #268: homme_shoc_cld_spa_p3_rrtmgp_128levels_np2 ................   Passed  806.73 sec
        Start 271: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np2_bfb
224/273 Test #271: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np2_bfb .....   Passed    0.10 sec
        Start 272: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np3_bfb
225/273 Test #272: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np3_bfb .....   Passed    0.13 sec
        Start 273: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np4_bfb
226/273 Test #273: homme_shoc_cld_spa_p3_rrtmgp_128levels_np1_vs_np4_bfb .....   Passed    0.09 sec
230/278 Test  #74: p3_tests_omp3 .............................................   Passed  517.74 sec
160/205 Test  #72: p3_tests_omp9 ....................   Passed  307.55 sec
        Start  62: physics_tests_omp15
161/205 Test  #62: physics_tests_omp15 ..............   Passed    0.29 sec
        Start  74: p3_tests_omp11
231/278 Test  #90: p3_tests_fail_omp3 ........................................   Passed  519.02 sec
        Start 116: shoc_tests_omp8
227/273 Test  #78: p3_tests_omp7 .............................................   Passed   91.80 sec
        Start  81: p3_tests_omp10
162/205 Test  #70: p3_tests_omp7 ....................   Passed  725.63 sec
        Start  86: p3_tests_fail_omp7
228/273 Test  #77: p3_tests_omp6 .............................................   Passed  262.48 sec
        Start 127: shoc_sk_tests_omp6
229/273 Test  #81: p3_tests_omp10 ............................................   Passed    3.81 sec
        Start  95: p3_tests_fail_omp8
232/278 Test  #95: p3_tests_fail_omp8 ........................................   Passed  176.38 sec
        Start 131: shoc_sk_tests_omp7
230/273 Test  #94: p3_tests_fail_omp7 ........................................   Passed   56.52 sec
        Start  96: p3_tests_fail_omp9
163/205 Test  #74: p3_tests_omp11 ...................   Passed    9.60 sec
        Start  75: p3_tests_omp12
233/278 Test #131: shoc_sk_tests_omp7 ........................................   Passed    9.62 sec
        Start 132: shoc_sk_tests_omp8
234/278 Test #132: shoc_sk_tests_omp8 ........................................   Passed    9.81 sec
231/273 Test #127: shoc_sk_tests_omp6 ........................................   Passed   22.98 sec
232/273 Test  #80: p3_tests_omp9 .............................................   Passed   67.19 sec
        Start  66: physics_tests_omp11
233/273 Test  #66: physics_tests_omp11 .......................................   Passed    0.99 sec
        Start  67: physics_tests_omp12
234/273 Test  #67: physics_tests_omp12 .......................................   Passed    0.78 sec
        Start  68: physics_tests_omp13
235/273 Test  #68: physics_tests_omp13 .......................................   Passed    0.94 sec
        Start  69: physics_tests_omp14
236/273 Test  #69: physics_tests_omp14 .......................................   Passed    2.31 sec
        Start  70: physics_tests_omp15
237/273 Test  #70: physics_tests_omp15 .......................................   Passed    0.91  [...]

2023-02-17 00:45 UTC, bartgol commented
@jgfouca the weaver fail is b/c pip cannot install the netCDF4 package:

```
16:33:54 Detected missing package netCDF4. Will attempt to install locally
16:33:54 Looking in links: /tmp/tmp_o7dtcb5
16:33:54 Requirement already satisfied: setuptools in /projects/ppc64le/python/3.7.3/lib/python3.7/site-packages (40.8.0)
16:33:54 Requirement already satisfied: pip in /home/e3sm-jenkins/.local/lib/python3.7/site-packages (21.3.1)
16:33:54 ERROR: Failed to install netCDF4, cannot continue:
16:33:54 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-uviojvk9/025205f9fe213fcace1cc098dc0aae7fd9d310f12047df50e65f43a8'
16:33:54 
16:33:54 WARNING: You are using pip version 21.3.1; however, version 23.0 is available.
16:33:54 You should consider upgrading via the '/home/projects/ppc64le/python/3.7.3/bin/python3 -m pip install --upgrade pip' command.
```
The `No such file or directory` is something I don't understand. Does it ring any bell to you?

2023-02-17 05:08 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3566</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4164</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4222</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: f5abed245c37b515f5965617574514d23e5addb4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-17 05:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3566</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4164</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4222</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3566</b> (click to expand)
</summary>
<pre>
<code>
        Start 242: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
220/278 Test  #67: physics_tests_omp12 .......................................   Passed    0.30 sec
        Start  68: physics_tests_omp13
221/278 Test #242: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.10 sec
        Start 243: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
222/278 Test #243: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.09 sec
223/278 Test  #68: physics_tests_omp13 .......................................   Passed    0.31 sec
        Start  69: physics_tests_omp14
224/278 Test  #69: physics_tests_omp14 .......................................   Passed    0.31 sec
        Start  70: physics_tests_omp15
225/278 Test  #70: physics_tests_omp15 .......................................   Passed    0.30 sec
        Start  71: physics_tests_omp16
226/278 Test  #71: physics_tests_omp16 .......................................   Passed    0.31 sec
        Start  81: p3_tests_omp10
166/273 Test #243: homme_shoc_cld_p3_rrtmgp_np2 ..............................   Passed  211.44 sec
        Start 229: shoc_cld_p3_rrtmgp_np1_vs_np2_bfb
167/273 Test #229: shoc_cld_p3_rrtmgp_np1_vs_np2_bfb .........................   Passed    0.03 sec
        Start 230: shoc_cld_p3_rrtmgp_np1_vs_np3_bfb
168/273 Test #230: shoc_cld_p3_rrtmgp_np1_vs_np3_bfb .........................   Passed    0.03 sec
        Start 231: shoc_cld_p3_rrtmgp_np1_vs_np4_bfb
169/273 Test #231: shoc_cld_p3_rrtmgp_np1_vs_np4_bfb .........................   Passed    0.03 sec
227/278 Test  #81: p3_tests_omp10 ............................................   Passed    4.65 sec
        Start  82: p3_tests_omp11
228/278 Test #265: homme_shoc_cld_spa_p3_rrtmgp_np4 ..........................   Passed   95.01 sec
        Start  97: p3_tests_fail_omp10
229/278 Test  #82: p3_tests_omp11 ............................................   Passed    4.59 sec
        Start  98: p3_tests_fail_omp11
230/278 Test  #98: p3_tests_fail_omp11 .......................................   Passed    4.44 sec
        Start 116: shoc_tests_omp8
231/278 Test  #97: p3_tests_fail_omp10 .......................................   Passed    5.72 sec
        Start  83: p3_tests_omp12
232/278 Test #116: shoc_tests_omp8 ...........................................   Passed    1.88 sec
        Start 117: shoc_tests_omp9
233/278 Test #117: shoc_tests_omp9 ...........................................   Passed    1.90 sec
        Start 132: shoc_sk_tests_omp8
170/273 Test #232: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  261.68 sec
        Start 236: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
171/273 Test #236: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb .....................   Passed    0.06 sec
        Start 237: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb
172/273 Test #237: shoc_cld_spa_p3_rrtmgp_np1_vs_np3_bfb .....................   Passed    0.06 sec
        Start 238: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb
173/273 Test #238: shoc_cld_spa_p3_rrtmgp_np1_vs_np4_bfb .....................   Passed    0.06 sec
234/278 Test #132: shoc_sk_tests_omp8 ........................................   Passed    0.72 sec
        Start 133: shoc_sk_tests_omp9
235/278 Test #133: shoc_sk_tests_omp9 ........................................   Passed    0.73 sec
236/278 Test  #83: p3_tests_omp12 ............................................   Passed    4.59 sec
        Start  84: p3_tests_omp13
237/278 Test  #84: p3_tests_omp13 ............................................   Passed    4.03 sec
        Start  85: p3_tests_omp14
174/273 Test   #4: io_test_np4 ...............................................   Passed   25.93 sec
        Start   8: io_test_se_grid_np4
175/273 Test   #8: io_test_se_grid_np4 .......................................   Passed    0.59 sec
        Start  20: io_remap_test_np4
176/273 Test  #20: io_remap_test_np4 .........................................   Passed    2.25 sec
        Start  28: field_utils_np4
177/273 Test  #28: field_utils_np4 ...........................................   Passed    0.32 sec
        Start  33: grid_np4
178/273 Test  #33: grid_np4 ..................................................   Passed    0.32 sec
        Start  37: coarsening_remapper_np4
238/278 Test  #85: p3_tests_omp14 ............................................   Passed    5.11 sec
        Start  86: p3_tests_omp15
179/27 [...]

2023-02-17 10:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3567</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4165</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4223</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: f5abed245c37b515f5965617574514d23e5addb4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-17 11:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3567</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4165</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4223</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3567</b> (click to expand)
</summary>
<pre>
<code>
167/273 Test #144: spa_one_to_one_remap_test_np3 .............................   Passed    1.36 sec
        Start 213: surface_coupling_np3
218/278 Test  #81: p3_tests_omp10 ............................................   Passed    4.08 sec
        Start  82: p3_tests_omp11
168/273 Test #213: surface_coupling_np3 ......................................   Passed    0.69 sec
219/278 Test  #82: p3_tests_omp11 ............................................   Passed    4.45 sec
        Start  83: p3_tests_omp12
220/278 Test  #83: p3_tests_omp12 ............................................   Passed    4.72 sec
        Start  84: p3_tests_omp13
169/273 Test #245: homme_shoc_cld_p3_rrtmgp_np4 ..............................   Passed  109.46 sec
        Start   4: io_test_np4
170/273 Test #244: homme_shoc_cld_p3_rrtmgp_np3 ..............................   Passed  162.70 sec
        Start   8: io_test_se_grid_np4
171/273 Test   #8: io_test_se_grid_np4 .......................................   Passed    0.61 sec
        Start  20: io_remap_test_np4
221/278 Test #265: homme_shoc_cld_spa_p3_rrtmgp_np4 ..........................   Passed   96.92 sec
        Start  94: p3_tests_fail_omp7
172/273 Test #258: homme_shoc_cld_spa_p3_rrtmgp_np2 ..........................   Passed  240.02 sec
        Start  28: field_utils_np4
222/278 Test  #84: p3_tests_omp13 ............................................   Passed    5.12 sec
        Start  95: p3_tests_fail_omp8
173/273 Test  #28: field_utils_np4 ...........................................   Passed    0.34 sec
        Start  33: grid_np4
174/273 Test  #20: io_remap_test_np4 .........................................   Passed    2.68 sec
        Start  37: coarsening_remapper_np4
175/273 Test  #33: grid_np4 ..................................................   Passed    0.27 sec
        Start  41: vertical_remapper_np4
176/273 Test  #41: vertical_remapper_np4 .....................................   Passed    0.45 sec
        Start  47: horizontal_remap_np4
177/273 Test  #37: coarsening_remapper_np4 ...................................   Passed    1.33 sec
        Start  51: homme_pd_remap_np4
178/273 Test  #47: horizontal_remap_np4 ......................................   Passed    1.05 sec
        Start  55: dyn_grid_io_np4
179/273 Test  #55: dyn_grid_io_np4 ...........................................   Passed    0.83 sec
        Start  59: physics_tests_omp4
180/273 Test  #51: homme_pd_remap_np4 ........................................   Passed    1.11 sec
        Start  75: p3_tests_omp4
181/273 Test  #59: physics_tests_omp4 ........................................   Passed    0.26 sec
        Start  91: p3_tests_fail_omp4
223/278 Test  #94: p3_tests_fail_omp7 ........................................   Passed    5.33 sec
        Start  96: p3_tests_fail_omp9
224/278 Test  #95: p3_tests_fail_omp8 ........................................   Passed    4.75 sec
        Start  97: p3_tests_fail_omp10
182/273 Test  #75: p3_tests_omp4 .............................................   Passed    3.75 sec
        Start 109: shoc_tests_omp4
183/273 Test  #91: p3_tests_fail_omp4 ........................................   Passed    4.85 sec
        Start 125: shoc_sk_tests_omp4
184/273 Test #109: shoc_tests_omp4 ...........................................   Passed    1.82 sec
        Start 141: spa_read_data_test_np4
185/273 Test #125: shoc_sk_tests_omp4 ........................................   Passed    0.66 sec
        Start 145: spa_one_to_one_remap_test_np4
225/278 Test  #96: p3_tests_fail_omp9 ........................................   Passed    5.81 sec
        Start 115: shoc_tests_omp7
226/278 Test  #97: p3_tests_fail_omp10 .......................................   Passed    5.56 sec
        Start  98: p3_tests_fail_omp11
186/273 Test #145: spa_one_to_one_remap_test_np4 .............................   Passed    2.15 sec
        Start 214: surface_coupling_np4
187/273 Test #141: spa_read_data_test_np4 ....................................   Passed    2.45 sec
188/273 Test #214: surface_coupling_np4 ......................................   Passed    0.89 sec
        Start  60: physics_tests_omp5
227/278 Test #237: shoc_cld_spa_p3_rrtmgp_np1 ................................   Passed  277.25 sec
        Start 241: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb
228/278 Test #241: shoc_cld_spa_p3_rrtmgp_np1_vs_np2_bfb ............... [...]

2023-02-17 16:27 UTC, jgfouca commented
@bartgol , the ensure_* functions have been flaky ever since I added them. I have repeatedly seen this "missing /tmp" error. I will investigate.

2023-02-17 16:36 UTC, jgfouca commented
@bartgol , it looks like updating the version of pip for the user e3sm-jenkins fixed the problem. I will try to incorporate some kind of update check in ensure_pip.

2023-02-17 18:40 UTC, AaronDonahue approved these changes

2023-02-17 21:09 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2023-02-17 21:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3572</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4170</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4228</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/u_and_v_as_fields</li>
    <li>SHA: f5abed245c37b515f5965617574514d23e5addb4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-02-17 21:51 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3572</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4170</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4228</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>enhancement;AT: RETEST;AT: AUTOMERGE</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2172</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bartgol/u_and_v_as_fields</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>f5abed245c37b515f5965617574514d23e5addb4</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>a6261d1464f92477a4c2145bd4a26a2c58e0b862</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2023-02-17 21:51 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ AaronDonahue ]!

2023-02-17 21:51 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2023-02-17 21:51 UTC, merged

2023-02-17 21:51 UTC, E3SM-Autotester commented
Merge on Pull Request# 2172: IS A SUCCESS - Pull Request successfully merged