Add a new CIME based EAMxx test to check output coarsening
E3SM-Project/scream pull request #2215
Opened 2023-03-06 22:06 UTC by AaronDonahue

This commit adds a new test `scream-output_coarsening` that will test that our horizontal and vertical output capability hasn't been broken for CIME cases.

2023-03-06 22:07 UTC, AaronDonahue commented
The last task for this PR is to upload the map file to the blues server so it is available for download.

2023-03-06 22:14 UTC, jgfouca requested changes

2023-03-06 22:14 UTC, jgfouca commented on components/eamxx/cime_config/testdefs/testmods_dirs/scream/output_coarsening/shell_commands
> +./xmlchange SCREAM_ATMCHANGE_BUFFER='Scorpio::output_yaml_files=${SRCROOT}/components/eamxx/data/scream_coarsening_output.yaml'
You'll want xmlchange to append this value (`--append`) so as to not flush whatever might have already been in the buffer.

2023-03-07 00:19 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-03-07 00:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3649</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4239</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4297</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_coarsening_CIME_test</li>
    <li>SHA: 80eea28a6f880477114fc06b833af3f9ed5b4c24</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2023-03-07 00:36 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3649</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4239</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4297</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>80eea28a6f880477114fc06b833af3f9ed5b4c24</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3649</b> (click to expand)
</summary>
<pre>
<code>
++ tcl_mod_paths=/usr/share/Modules/modulefiles
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ MODULEPATH=/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ '[' -d /projects/pressio/modules ']'
++ '[' -z '' ']'
++ export SEMS_LOADING=1
++ SEMS_LOADING=1
++ [[ rhel7-x86_64 == \t\o\s\s\3 ]]
++ [[ rhel7-x86_64 == \D\a\r\w\i\n* ]]
++ MODULEFILES_ROOT=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles;' export 'MODULEPATH;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t;' export '_ModuleTable001_;' '_ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==;' export '_ModuleTable002_;' '_ModuleTable_Sz_=2;' export '_ModuleTable_Sz_;'
+++ __LMOD_REF_COUNT_MODULEPATH='/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2;/usr/share/Modules/modulefiles:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1;/etc/modulefiles:1'
+++ export __LMOD_REF_COUNT_MODULEPATH
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1z [...]

2023-03-07 05:59 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2023-03-07 16:07 UTC, jgfouca submitted a review, later dismissed

2023-03-07 18:23 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-03-07 18:26 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3655</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4245</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4303</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_coarsening_CIME_test</li>
    <li>SHA: d7d28a3ed93cc94bec027ee0f5cdba227258d53f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2023-03-07 18:43 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3655</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4245</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4303</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3655</b> (click to expand)
</summary>
<pre>
<code>
++ tcl_mod_paths=/usr/share/Modules/modulefiles
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ MODULEPATH=/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ '[' -d /projects/pressio/modules ']'
++ '[' -z '' ']'
++ export SEMS_LOADING=1
++ SEMS_LOADING=1
++ [[ rhel7-x86_64 == \t\o\s\s\3 ]]
++ [[ rhel7-x86_64 == \D\a\r\w\i\n* ]]
++ MODULEFILES_ROOT=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles;' export 'MODULEPATH;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t;' export '_ModuleTable001_;' '_ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==;' export '_ModuleTable002_;' '_ModuleTable_Sz_=2;' export '_ModuleTable_Sz_;'
+++ __LMOD_REF_COUNT_MODULEPATH='/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2;/usr/share/Modules/modulefiles:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1;/etc/modulefiles:1'
+++ export __LMOD_REF_COUNT_MODULEPATH
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1z [...]

2023-03-07 19:04 UTC, AaronDonahue commented
Fails pending the upload of a new file to the data server.

2023-03-08 00:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3663</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4253</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4311</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_coarsening_CIME_test</li>
    <li>SHA: d7d28a3ed93cc94bec027ee0f5cdba227258d53f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2023-03-08 01:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3663</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4253</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4311</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3663</b> (click to expand)
</summary>
<pre>
<code>
++ tcl_mod_paths=/usr/share/Modules/modulefiles
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:
++ MODULEPATH=:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles:
++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ MODULEPATH=/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/etc/modulefiles
++ '[' -d /projects/pressio/modules ']'
++ '[' -z '' ']'
++ export SEMS_LOADING=1
++ SEMS_LOADING=1
++ [[ rhel7-x86_64 == \t\o\s\s\3 ]]
++ [[ rhel7-x86_64 == \D\a\r\w\i\n* ]]
++ MODULEFILES_ROOT=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles;' export 'MODULEPATH;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t;' export '_ModuleTable001_;' '_ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==;' export '_ModuleTable002_;' '_ModuleTable_Sz_=2;' export '_ModuleTable_Sz_;'
+++ __LMOD_REF_COUNT_MODULEPATH='/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2;/usr/share/Modules/modulefiles:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1;/etc/modulefiles:1'
+++ export __LMOD_REF_COUNT_MODULEPATH
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1z [...]

2023-03-08 06:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2023-03-11 00:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2023-03-11 01:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Weaver to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2023-03-11 07:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Mappy to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2023-03-13 13:13 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2023-03-13 13:30 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3711</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: RETEST;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4294</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: RETEST;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4351</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: RETEST;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>d7d28a3ed93cc94bec027ee0f5cdba227258d53f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>300cbe9e959c37b658a7b16de82940fb4fa762c2</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3711</b> (click to expand)
</summary>
<pre>
<code>
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t
+++ export _ModuleTable001_
+++ _ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==
+++ export _ModuleTable002_
+++ _ModuleTable_Sz_=2
+++ export _ModuleTable_Sz_
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:2\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/etc/modulefiles;' export 'MODULEPATH;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L3Byb2plY3QtbW9kdWxlZmlsZXMiLCIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXMiLCIvcHJvamVjdHMvc2Vtcy9tb2R1bGVmaWxlcy9yaGVsNy14ODZfNjQvc2Vtcy9saW51eC1yaGVsNy14ODZfNjQvY29tcGlsZXJzIiwiL2V0Yy9t;' export '_ModuleTable001_;' '_ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==;' export '_ModuleTable002_;' '_ModuleTable_Sz_=2;' export '_ModuleTable_Sz_;'
+++ __LMOD_REF_COUNT_MODULEPATH='/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:2;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2;/usr/share/Modules/modulefiles:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1;/etc/modulefiles:1'
+++ export __LMOD_REF_COUNT_MODULEPATH
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L3Byb2plY3QtbW9kdWxlZmlsZXMiLCIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXMiLCIvcHJvamVjdHMvc2Vtcy9tb2R1bGVmaWxlcy9yaGVsNy14ODZfNjQvc2Vtcy9saW51eC1yaGVsNy14ODZfNjQvY29tcGlsZXJzIiwiL2V0Yy9t
+++ export _ModuleTable001_
+++ _ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==
+++ export _ModuleTable002_
+++ _ModuleTable_Sz_=2
+++ export _ModuleTable_Sz_
++ modul [...]

2023-03-13 15:49 UTC, AaronDonahue commented
@jgfouca , I think I know why this is still failing.  The automatic download of the remap file it needs isn't being triggered because it isn't listed in the namelist_defaults file, instead it is set in an output control yaml file, which I don't think `buildnml` check for required files.  Is there a CIME command I can add to the `testdefs` that will trigger `wget` if a specific file is missing?

2023-03-13 15:51 UTC, jgfouca commented
@AaronDonahue , which yaml file is this? I can add it to the list of things buildnml scans for input files.

2023-03-13 15:55 UTC, jgfouca commented
I'm going to do an upstream merge to bring in recent buildnml changes.

2023-03-13 16:50 UTC, jgfouca commented
@AaronDonahue , @bartgol , see what you think of my latest commit.

2023-03-13 17:45 UTC, bartgol commented
This assumes that all streams requiring remap will use the same tgt grid, right? I thought @AaronDonahue said he may want 2+ separate coarsening remaps.

2023-03-13 18:02 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3714</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4297</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4354</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/add_coarsening_CIME_test</li>
    <li>SHA: 509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2023-03-13 18:26 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 3714</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4297</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 4354</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>testing;B4B;AT: AUTOMERGE;AT: Skip Stand-Alone Testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2215</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/add_coarsening_CIME_test</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>509a2b6bd5aa2874d6a57a53f808e421d3a8c13f</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>fecc13b18fd583d34363566a752152c26161a3c1</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100K lines) : SCREAM_PullRequest_Autotester_Mappy # 3714</b> (click to expand)
</summary>
<pre>
<code>
++ SEMS_LOADING=1
++ [[ rhel7-x86_64 == \t\o\s\s\3 ]]
++ [[ rhel7-x86_64 == \D\a\r\w\i\n* ]]
++ MODULEFILES_ROOT=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles;' export 'MODULEPATH;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t;' export '_ModuleTable001_;' '_ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==;' export '_ModuleTable002_;' '_ModuleTable_Sz_=2;' export '_ModuleTable_Sz_;'
+++ __LMOD_REF_COUNT_MODULEPATH='/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2;/usr/share/Modules/modulefiles:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:1;/etc/modulefiles:1'
+++ export __LMOD_REF_COUNT_MODULEPATH
+++ MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/etc/modulefiles
+++ export MODULEPATH
+++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXt9LG1wYXRoQT17Ii9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9wcm9qZWN0LW1vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Byb2plY3RzL3NlbXMvbW9kdWxlZmlsZXMvcmhlbDcteDg2XzY0L3NlbXMvbGludXgtcmhlbDcteDg2XzY0L2NvbXBpbGVycyIsIi9wcm9qZWN0cy9zZW1zL21vZHVsZWZpbGVzL3JoZWw3LXg4Nl82NC9zZW1zL2xpbnV4LXJoZWw3LXg4Nl82NC9Db3JlIiwiL2V0Yy9t
+++ export _ModuleTable001_
+++ _ModuleTable002_=b2R1bGVmaWxlcyIsfSxbInN5c3RlbUJhc2VNUEFUSCJdPSIvdXNyL3NoYXJlL01vZHVsZXMvbW9kdWxlZmlsZXM6L2V0Yy9tb2R1bGVmaWxlcyIsfQ==
+++ export _ModuleTable002_
+++ _ModuleTable_Sz_=2
+++ export _ModuleTable_Sz_
++ module use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core
+++ /projects/sems/install/rhel7-x86_64/sems/v2/lmod/lmod/8.3/gcc/10.1.0/zbzzu7k/lmod/lmod/libexec/lmod sh use /projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core
++ eval '__LMOD_REF_COUNT_MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:2\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:2\;/usr/share/Modules/modulefiles:1\;/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:1\;/etc/modulefiles:1;' export '__LMOD_REF_COUNT_MODULEPATH;' 'MODULEPATH=/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/Core:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/project-modulefiles:/usr/share/Modules/modulefiles:/projects/sems/modulefiles/rhel7-x86_64/sems/linux-rhel7-x86_64/compilers:/etc/modulefiles;' export  [...]

2023-03-21 22:45 UTC, AaronDonahue commented
> This assumes that all streams requiring remap will use the same tgt grid, right? I thought @AaronDonahue said he may want 2+ separate coarsening remaps.
@jgfouca , yes, I'm not sure we can anticipate what remap files a user will want ahead of time and it might be confusing if we make it a part of the scream_namelist file.  If that makes sense.  I wonder if there is a `shell_commands` that we can use that does the equivalent of CIME's file check.  In other words, a command or set of commands that will attempt to touch this specific file and if it is missing issue a `wget`.  Is that approach possible?

2023-06-30 21:12 UTC, bartgol commented
Taking care of #2414 would partially address the issues with this PR. @AaronDonahue another issue with this PR is that it adds both horiz and vert remap, while in the IO classes we explicitly prohibit to do horiz+vert (we only allow one of them).

Separately, @jgfouca what do you think about using ATM vars (not CIME XML vars) as selectors? Meaning, allow to atmchange (some) selectors. It seems pointless to set stuff like EAMXX_OUTPUT_GRID in the main CIME vars, when it is clearly just an atm setting... So, ideally, I'd like to do
```
./atmchange output_remap_grid=ne2pg2
./case.setup
```
and see the value of `horiz_remap_file` in the output yaml file changed. I think this would take two steps:
1. allow to atmchange selectors (perhaps we should revamp the "locked" attribute, to distinguish selectors that are linked to the case, and cannot be changed, like hgrid, from others)
2. in `do_cime_vars_on_yaml_output_files` (or in a separate analogue routine), also expand `${blah}` if `blah` is an EAMxx selector.
```

2023-07-03 18:11 UTC, jgfouca commented
@bartgol , I'd have to think about all the implications of that. It seems like it should be doable although it opens us up to circular dependencies.

2023-08-14 18:24 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2023-08-14 18:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2024-03-21 17:41 UTC, AaronDonahue commented
addressed by #2727

2024-03-21 17:41 UTC, closed without merging