Autogenerate markdown documentation file for all the atmchange-able parameters of EAMxx
E3SM-Project/scream pull request #2458
Opened 2023-08-15 23:52 UTC by bartgol

This script parses our `namelist_defaults_scream.xml` file, and produces a markdown file in the folder `components/eamxx/docs/mkdocs/common` (which will exist as soon as #2454 is merged). The generated file contains all (and only) the parameters that are atmchange-able, listing the name, type, description, and, if present, valid values and/or constraints.

The generated file (see attached) clearly shows that we have some work to do in adding more metadata to our XML defaults file.

Ideally, when someone adds a new configurable parameters, they should  run the script in their branch, and commit also the changed newly generated markdown file. Then, upon PR merge, deploy the new documentation via
```
$ cd components/eamxx/docs/mkdocs
$ mkdocs build
$ mkdocs gh-deploy
```
Note: the above folder does not yet exist in master, it will be created only when #2454 is merged.

If you don't have mkdocs, simply run `$ pip install mkdocs pymdown-extensions mkdocs-material`. That should be enough (as of today) to run mkdocs.

[eamxx_params.md](https://github.com/E3SM-Project/scream/files/12353778/eamxx_params.md)

2023-08-15 23:59 UTC, PeterCaldwell commented
This is great! We may not explain what any of our parameters do, but we certainly have a lot of them! Just seeing the list will be very useful.

2023-08-16 14:15 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2023-08-16 14:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 4190</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4e396d1460dad4f2ddbddbbb1a5c01dc7e63deb8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4727</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4e396d1460dad4f2ddbddbbb1a5c01dc7e63deb8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/eamxx-params-docs-autogen</li>
    <li>SHA: 4e396d1460dad4f2ddbddbbb1a5c01dc7e63deb8</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-08-16 14:22 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 4190</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4e396d1460dad4f2ddbddbbb1a5c01dc7e63deb8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4727</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>4e396d1460dad4f2ddbddbbb1a5c01dc7e63deb8</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2023-08-16 14:23 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2023-08-16 14:23 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-08-16 18:00 UTC, jgfouca requested changes
Looks good! My only thought is that eamxx-params-docs-autogen is not quite following the pattern of our other tools, specifically, it's not doing any option parsing/handling. I think it's probably worth adding this, even if `--help` is the only current supported option.

2023-08-16 18:04 UTC, bartgol commented
> Looks good! My only thought is that eamxx-params-docs-autogen is not quite following the pattern of our other tools, specifically, it's not doing any option parsing/handling. I think it's probably worth adding this, even if `--help` is the only current supported option.

I thought about it, but since there's no real option to parse, I figured I'd skip it. I can add that layer.

2023-08-16 18:14 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2023-08-16 18:15 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 4193</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8de6ff620ccec7a9452dd3a5f4a475b4bd0d3fed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4730</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8de6ff620ccec7a9452dd3a5f4a475b4bd0d3fed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bartgol/eamxx-params-docs-autogen</li>
    <li>SHA: 8de6ff620ccec7a9452dd3a5f4a475b4bd0d3fed</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bartgol
</details>

2023-08-16 18:21 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 4193</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8de6ff620ccec7a9452dd3a5f4a475b4bd0d3fed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 4730</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>documentation;AT: Integrate Without Testing;scripts;code usability</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>2458</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>8de6ff620ccec7a9452dd3a5f4a475b4bd0d3fed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>f8195d69bd66d41a32c383809df3fd2cfe70db9a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2023-08-16 18:22 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2023-08-16 18:22 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-08-16 18:29 UTC, jgfouca approved these changes

2023-08-16 19:47 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jgfouca ]!

2023-08-16 19:47 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2023-08-16 19:47 UTC, merged

2023-08-16 19:47 UTC, E3SM-Autotester commented
Merge on Pull Request# 2458: IS A SUCCESS - Pull Request successfully merged