Add git-hash information to EAMxx and in the output metadata
E3SM-Project/scream pull request #3094
Opened 2024-11-05 00:44 UTC by AaronDonahue

This commit changes the CMake commands for eamxx to ensure that the git-hash is saved to the EAMXX_GIT_VERSION variable and is thus available to EAMxx itself.

This naturally causes the git-hash to be added to the netCDF metadata for all EAMxx output.

Partially addresses #2142

2024-11-05 00:46 UTC, AaronDonahue commented
I'm not CMake savvy so I wouldn't be surprised if there is a better way to accomplish this.  @jgfouca or @bartgol , feel free to comment on this approach.

The main goal is to have the EAMXX_GIT_VERSION variable always be defined in EAMxx.  We already use this variable in the metadata of our output, but it is `""` in all of the examples I have checked.

2024-11-05 00:47 UTC, rljacob commented
Is this for standalone?  The coupler has the git hash in the infobuffer and passes it to all the models.

2024-11-05 00:50 UTC, AaronDonahue commented
This is for CIME cases.  If there is already a GIT hash variable available then that would be the correct way to grab the info I think.  @rljacob can you point me to an example of this being done?

2024-11-05 16:31 UTC, jgfouca submitted a review, later dismissed

2024-11-05 16:43 UTC, bartgol commented
@rljacob any reason to believe the info we get with rev-parse would differ from what CIME would pass?

I suppose there is a corner case, but it should not affect most users: the logic we have in our cmake code only runs when CMake runs. If one adds another commit and rebuilds, unless the changes trigger another cmake run, EAMXX_GIT_SHA will _not_ get updated.

That said, I think the corner case should not impact any production run, only development. So I am ok with it. Unless Rob sees a reason for which we SHOULD rely on CIME's passed var.

2024-11-05 18:03 UTC, AaronDonahue commented
Thanks for pointing me to the proper code @rljacob .  I'll make the change.

2024-11-05 19:30 UTC, AaronDonahue commented
Question for @rljacob , @jgfouca and @bartgol .  Following Rob's example for EAMxx it looks like I get a different git-hash then if I use the CMake approach.  I think the CMake approach will grab whatever the git-hash is for the current run, meaning it will change with new commits to a branch.  On the other hand I'm not sure how the `version` is determined.  On this branch when I looked at what I get it is `d291456767` which tracks to this commit: https://github.com/E3SM-Project/scream/commit/d291456767f9df5efd714a8df5276e0702208e63 .  

My question is about what we want in our metadata:
1. We can follow EAM convention, use `version` from the component coupler and call it `git_version` in the metadata.
2. We can have two fields, `git_version` as above following EAM convention and a separate one that is maybe called `git_branch_version` that takes the CMake value.

I think that regardless we want to use the EAM convention so that the metadata matches what the other components are using.  The main question is, do we also want to add the most up-to-date git hash to the meta data too?

2024-11-05 20:41 UTC, rljacob commented
The hash is what CIME retrieves.  And that will be from the SRCROOT.  If you've made new commits but haven't rerun preview_namelists (which happens with case.build or case.submit), it won't be updated.

2024-11-05 21:05 UTC, AaronDonahue commented
>The hash is what CIME retrieves. And that will be from the SRCROOT. If you've made new commits but haven't rerun preview_namelists (which happens with case.build or case.submit), it won't be updated.

That's interesting.  I definitely ran case.build and case.submit because I needed to rebuild after making the changes.  The commit that it appears to point to isn't even the `master` branch that this branch was built on.  I'm only noting that in case there is some strange behavior with the way CIME is querying that info that is worth a look.

2024-11-06 15:41 UTC, bartgol commented
If I understand CIME correctly, the sha you get from CIME will _always_ be at least as recent as the one you get in standalone EAMxx. I would use that one, it seems like it should an easy addition to our f90-cxx interface for the coupler.

2024-11-07 23:13 UTC, jgfouca approved these changes

2024-11-08 03:36 UTC, bartgol commented on components/eamxx/CMakeLists.txt
> +# Print the sha of the last commit (useful to double check which version was tested on CDash)
This block should now be moved back into where it was before.

2024-11-08 03:38 UTC, bartgol requested changes
Triggering mergify, to check something. But also pointing out that the mods in the main CMakeLists.txt file should be reverted.

2024-11-08 04:59 UTC, rljacob commented
I opened a CIME issue about the behavior. https://github.com/ESMCI/cime/issues/4705.  The hash is set at create_newcase time and never changes.  Its possible CIME always did this and no one noticed until Aaron started looking carefully.  For a production run, those will be done on master so the hash will be right.  For any runs done on a frequently changing feature branch, most of that data gets thrown away so no one checked.

2024-11-08 22:14 UTC, AaronDonahue commented
> Triggering mergify, to check something. But also pointing out that the mods in the main CMakeLists.txt file should be reverted.

@jgfouca do you agree?  From the perspective of this PR reverting the CMake changes makes sense.  We are no longer passing the EAMXX_GIT_VERSION variable to the netCDF metadata.  But in the old approach were we ever setting this variable to anything other than ""?  In other words should we keep my change so that if EAMXX_GIT_VERSION is ever queried it reflects the git hash?  If we plan to only use the CIME passed one can we remove EAMXX_GIT_VERSION altogether?

2024-11-11 15:55 UTC, bartgol commented
> > Triggering mergify, to check something. But also pointing out that the mods in the main CMakeLists.txt file should be reverted.
> 
> @jgfouca do you agree? From the perspective of this PR reverting the CMake changes makes sense. We are no longer passing the EAMXX_GIT_VERSION variable to the netCDF metadata. But in the old approach were we ever setting this variable to anything other than ""? In other words should we keep my change so that if EAMXX_GIT_VERSION is ever queried it reflects the git hash? If we plan to only use the CIME passed one can we remove EAMXX_GIT_VERSION altogether?

We cannot remove it altogether, since we need it for standalone runs. But is should not be used for CIME runs.

2024-11-11 18:32 UTC, AaronDonahue commented
@bartgol  and @jgfouca , I purged the commit that changed the CMakeLists.txt file.  This should be ready for re-review.

2024-11-11 18:38 UTC, bartgol approved these changes

2024-11-11 18:41 UTC, jgfouca approved these changes

2024-11-14 23:34 UTC, AaronDonahue commented
@bartgol can I go ahead and merge this?

2024-11-15 18:38 UTC, merged