Port clipping_diag_third_shoc_moment
E3SM-Project/scream pull request #605
Opened 2020-09-24 17:07 UTC by tcclevenger

Ports clipping_diag_third_shoc_moment to C++.

2020-09-24 17:37 UTC, jgfouca requested changes
Minor nit. otherwise perfect

2020-09-24 17:37 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_clipping_diag_third_shoc_moments_impl.hpp
> +    Spack tsign(1.0);
It's harmless here, and in the -1.0 below, but it's worth getting in the habit of using integer literals when you can.

2020-09-24 18:04 UTC, jeff-cohere approved these changes

2020-09-24 18:55 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jeff-cohere ]!

2020-09-24 18:56 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 143</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 139</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 141</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (tcclevenger/scream)</dt>
  <ul>
    <li>Branch: clipping_diag_third_moments</li>
    <li>SHA: 464f1f39ee238fde97ba214207d699385a144643</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: tcclevenger
</details>

2020-09-24 18:59 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 143</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 139</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 141</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>605</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>clipping_diag_third_moments</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/tcclevenger/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>464f1f39ee238fde97ba214207d699385a144643</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>8182a99cd5e4f3a982e25d858f04e7dc436a4ae0</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 143</b> (click to expand)
</summary>
<pre>
<code>
+ '[' -r /etc/profile.d/modules.sh ']'
+ '[' hxB '!=' hxB ']'
+ . /etc/profile.d/modules.sh
++++ /bin/ps -p 192085 -ocomm=
+++ /bin/basename bash
++ shell=bash
++ '[' -f /usr/share/Modules/init/bash ']'
++ . /usr/share/Modules/init/bash
+++ export -f module
+++ MODULESHOME=/usr/share/Modules
+++ export MODULESHOME
+++ '[' '' = '' ']'
+++ LOADEDMODULES=
+++ export LOADEDMODULES
+++ '[' /usr/share/Modules/modulefiles:/etc/modulefiles:/home/projects/x86-64-skylake/modulefiles:/home/projects/x86-64/modulefiles = '' ']'
+++ '[' 4 -ge 3 ']'
+++ '[' -r /usr/share/Modules/init/bash_completion ']'
+++ . /usr/share/Modules/init/bash_completion
++++ complete -o default -F _module module
+ for i in '/etc/profile.d/*.sh'
+ '[' -r /etc/profile.d/vim.sh ']'
+ '[' hxB '!=' hxB ']'
+ . /etc/profile.d/vim.sh
++ '[' -n '4.2.46(1)-release' -o -n '' -o -n '' ']'
++ '[' -x /usr/bin/id ']'
+++ /usr/bin/id -u
++ ID=114754
++ '[' -n 114754 -a 114754 -le 200 ']'
++ alias vi
++ alias vi=vim
+ for i in '/etc/profile.d/*.sh'
+ '[' -r /etc/profile.d/which2.sh ']'
+ '[' hxB '!=' hxB ']'
+ . /etc/profile.d/which2.sh
++ alias 'which=alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
+ unset i
+ unset -f pathmunge
+ '[' -f /ascldap/users/e3sm-jenkins/.bashrc ']'
+ . /ascldap/users/e3sm-jenkins/.bashrc
++ '[' -f /etc/bashrc ']'
++ . /etc/bashrc
+++ '[' '' ']'
+++ shopt -q login_shell
+ PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
+ export PATH
+ cd /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/143/
+ ./scream/components/scream/scripts/jenkins/jenkins_common.sh
+ IFS=';'
+ read -r -a labels
+ skip_testing=0
+ '[' 2 -gt 0 ']'
+ for label in '"${labels[@]}"'
+ '[' B4B == 'CI: Integrate Without Testing' ']'
+ for label in '"${labels[@]}"'
+ '[' shoc == 'CI: Integrate Without Testing' ']'
+ '[' 0 -eq 0 ']'
+ source ./scream/components/scream/scripts/jenkins/blake_setup
++ export PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
++ PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
++ source ./scream/components/scream/scripts/jenkins/sandia_son_proxy
+++ export http_proxy=http://sonproxy.sandia.gov:80
+++ http_proxy=http://sonproxy.sandia.gov:80
+++ export RSYNC_PROXY=sonproxy.sandia.gov:80
+++ RSYNC_PROXY=sonproxy.sandia.gov:80
+++ export rsync_proxy=sonproxy.sandia.gov:80
+++ rsync_proxy=sonproxy.sandia.gov:80
+++ export HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ export https_proxy=http://sonproxy.sandia.gov:80
+++ https_proxy=http://sonproxy.sandia.gov:80
+++ export HTTP_PROXY=http://sonproxy.sandia.gov:80
+++ HTTP_PROXY=http://sonproxy.sandia.gov:80
++ SCREAM_MACHINE=blake
+ git config --global user.email jenkins@ignore.com
+ git config --global user.name 'Jenkins Jenkins'
+ SUBMIT=--submit
+ '[' -n 605 ']'
+ SUBMIT=
+ BASELINES_DIR=AUTO
+ ./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m $machine ' -l -m blake
srun: Job step created
Last commit on ref '464f1f39ee238fde97ba214207d699385a144643': 464f1f3 change to int literals
srun: error: node03: task 0: Exited with exit code 1
ERROR: Command: 'git submodule update --init --recursive' failed with error 'Submodule 'extern/kokkos' (git@github.com:kokkos/kokkos) registered for path '../../externals/ekat/extern/kokkos'
Submodule 'extern/yaml-cpp' (git@github.com:SNLComputation/yaml-cpp.git) registered for path '../../externals/ekat/extern/yaml-cpp'
Cloning into '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/143/scream/externals/ekat/extern/kokkos'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kokkos/kokkos' into submodule path '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/143/scream/externals/ekat/extern/kokkos' failed
Failed to recurse into submodule path '../../externals/ekat'' from dir '/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/ [...]

2020-09-25 14:45 UTC, tcclevenger commented
Working off a forked branch currently, which doesn't allow the tester to run without approval. Switching to branch off of the scream repo so I can debug without everyone getting emails. I'll request reviews once I've sorted out the issues.

2020-09-29 23:16 UTC, closed without merging