SHOC property test cleanup
E3SM-Project/scream pull request #641
Opened 2020-10-02 16:45 UTC by bogensch

This PR:

1) Cleans up the trailing white space mess I made.
2) Adds in more rigorous reasonable bounds checking to some tests.
3) Add in more SHOC constants to be used by the tests for said bounds checking.
4) Fixes various misspellings and typ@s.
5) Removes unit conversions when input data is defined (just define in SI units).

2020-10-02 17:15 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-10-02 17:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 285</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 272</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 274</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bogensch/SHOC_proptest_cleanup</li>
    <li>SHA: 25fff458ee2efbab7d4908ed5e2c3a83522790f9</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bogensch
</details>

2020-10-02 17:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 285</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 272</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 274</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>25fff458ee2efbab7d4908ed5e2c3a83522790f9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-10-02 17:44 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

2020-10-02 17:45 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-02 18:19 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2020-10-02 18:19 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-02 20:14 UTC, jgfouca requested changes
I like the overall theme of the PR, but I noticed lots of indentation problems.  I would check that your editor's CXX mode is configured correctly.

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_assumed_pdf_tests.cpp
> +	REQUIRE(std::abs(SDS.wthv_sec[offset] < wthv_sec_bound));
Bad indent, tab instead of spaces.

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_assumed_pdf_tests.cpp
> +	REQUIRE(SDS.shoc_ql[offset] < shoc_ql_bound);
Same

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_check_length_tests.cpp
> +	REQUIRE(SDS.shoc_mix[offset] <= maxlen);
Same

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_conv_vel_length_tests.cpp
> +	if (s == 1){
Same

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_energy_update_dse_tests.cpp
> +	  REQUIRE(SDS.thlm[offset + 1] - SDS.thlm[offset] < 0);
Same

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_energy_update_dse_tests.cpp
> +	REQUIRE(SDS.host_dse[offset] > 0);
Same

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_energy_update_dse_tests.cpp
> +          REQUIRE(SDS.host_dse[offset + 1] - SDS.host_dse[offset] < 0);
SCREAM does 2-space indents for new code blocks.

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_grid_tests.cpp
>  	const auto offset = n + s * nlevi;
More bad indents.

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_grid_tests.cpp
> +	REQUIRE(SDS.rho_zt[offset] > 0);
bad tabs

2020-10-02 20:14 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_length_tests.cpp
> +	REQUIRE(SDS.shoc_mix[offset] <= maxlen);
same

2020-10-02 20:14 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2020-10-02 20:15 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-02 22:15 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-10-02 22:15 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-10-02 22:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 291</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 278</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 280</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: bogensch/SHOC_proptest_cleanup</li>
    <li>SHA: 7c7d49b6720300835c2d318de8965f2d068c44be</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: bogensch
</details>

2020-10-02 22:32 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 291</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Bowman</h3>
<ul>
  <li>Build Num: 278</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 280</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc;testing</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>641</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>bogensch/SHOC_proptest_cleanup</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7c7d49b6720300835c2d318de8965f2d068c44be</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>892fe4ad547f6343c74e4ae13986bba623e8724a</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-10-02 22:33 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2020-10-02 22:33 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-02 22:54 UTC, bogensch commented
criminy, @jgfouca thanks for pointing this mess out.  I issued an "untabify" on all .cpp files that I got my grubby hands on to end the madness.  Should all be fixed now.

2020-10-03 22:45 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-04 22:45 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-05 22:49 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-10-06 18:51 UTC, jgfouca approved these changes

2020-10-06 19:35 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jgfouca ]!

2020-10-06 19:35 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2020-10-06 19:35 UTC, merged

2020-10-06 19:35 UTC, E3SM-Autotester commented
Merge on Pull Request# 641: IS A SUCCESS - Pull Request successfully merged