Ports Shoc's isotrpoic_ts to C++/Kokkos
E3SM-Project/scream pull request #760
Opened 2020-11-25 00:38 UTC by singhbalwinder

Added BFB test as well

2020-11-25 00:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-25 00:41 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-11-25 00:44 UTC, singhbalwinder commented on components/scream/src/physics/shoc/shoc_integ_column_stability_impl.hpp
> +  static constexpr Scalar troppres = 80000;
@ambrad suggested this change in my previous attempt at porting this function.

2020-11-25 00:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 718</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 706</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 257</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: singhbalwinder/shoc/isotrpoic_ts_port_1</li>
    <li>SHA: 947b5caa3409e3e96533e72f15ca53aefaf158a9</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: singhbalwinder
</details>

2020-11-25 00:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has commited a change to the PR before testing completed.  The original testing SHA = 947b5caa3409e3e96533e72f15ca53aefaf158a9 Does not match the current commit SHA = 7026273df4eca83ce8ad208296e73781ffecceae.  The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

2020-11-25 00:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 718</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 706</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 257</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>947b5caa3409e3e96533e72f15ca53aefaf158a9</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 718</b> (click to expand)
</summary>
<pre>
<code>
+ for i in '/etc/profile.d/*.sh'
+ '[' -r /etc/profile.d/which2.sh ']'
+ '[' hxB '!=' hxB ']'
+ . /etc/profile.d/which2.sh
++ alias 'which=alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
+ unset i
+ unset -f pathmunge
+ '[' -f /ascldap/users/e3sm-jenkins/.bashrc ']'
+ . /ascldap/users/e3sm-jenkins/.bashrc
++ '[' -f /etc/bashrc ']'
++ . /etc/bashrc
+++ '[' '' ']'
+++ shopt -q login_shell
+ PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
+ export PATH
+ cd /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/
+ ./scream/components/scream/scripts/jenkins/jenkins_common.sh
+ IFS=';'
+ read -r -a labels
+ skip_testing=0
+ '[' 4 -gt 0 ']'
+ for label in '"${labels[@]}"'
+ '[' 'AT: AUTOMERGE' == 'CI: Integrate Without Testing' ']'
+ for label in '"${labels[@]}"'
+ '[' 'AT: RETEST' == 'CI: Integrate Without Testing' ']'
+ for label in '"${labels[@]}"'
+ '[' B4B == 'CI: Integrate Without Testing' ']'
+ for label in '"${labels[@]}"'
+ '[' shoc == 'CI: Integrate Without Testing' ']'
+ '[' 0 -eq 0 ']'
+ source ./scream/components/scream/scripts/jenkins/blake_setup
++ export PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
++ PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
++ source ./scream/components/scream/scripts/jenkins/sandia_son_proxy
+++ export http_proxy=http://sonproxy.sandia.gov:80
+++ http_proxy=http://sonproxy.sandia.gov:80
+++ export RSYNC_PROXY=sonproxy.sandia.gov:80
+++ RSYNC_PROXY=sonproxy.sandia.gov:80
+++ export rsync_proxy=sonproxy.sandia.gov:80
+++ rsync_proxy=sonproxy.sandia.gov:80
+++ export HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ export https_proxy=http://sonproxy.sandia.gov:80
+++ https_proxy=http://sonproxy.sandia.gov:80
+++ export HTTP_PROXY=http://sonproxy.sandia.gov:80
+++ HTTP_PROXY=http://sonproxy.sandia.gov:80
++ SCREAM_MACHINE=blake
+ git config --global user.email jenkins@ignore.com
+ git config --global user.name 'Jenkins Jenkins'
+ SUBMIT=--submit
+ '[' -n 760 ']'
+ SUBMIT=
+ BASELINES_DIR=AUTO
+ ./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m $machine ' -l -m blake
salloc: Granted job allocation 1001170
Last commit on ref '7026273df4eca83ce8ad208296e73781ffecceae': 7026273 removes debug statements
git ref origin/master successfully merged.
Last commit on ref '8aae8f8c09628f40fe3e8cd30e725ce8f981d12b': 8aae8f8 Automatic merge of origin/master
Baselines found and not expired. Skipping baselines generation.
Note: no value passed for --ctest-parallel-level. Using the default for this machine: 48
Note: no value passed for --make-parallel-level. Using the default for this machine: 48
test dbg can use 16 jobs to compile, and 16 jobs for testing
test sp can use 16 jobs to compile, and 16 jobs for testing
test fpe can use 16 jobs to compile, and 16 jobs for testing
###############################################################################
Running tests!
###############################################################################
Run dashboard with model Experimental
   Source directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/components/scream
   Build directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/components/scream/ctest-build/full_sp_debug
   Track: E3SM_SCREAM
Run dashboard with model Experimental
   Source directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/components/scream
   Build directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/components/scream/ctest-build/full_debug
   Track: E3SM_SCREAM
Run dashboard with model Experimental
   Source directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/components/scream
   Build directory: /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/718/scream/com [...]

2020-11-25 00:46 UTC, singhbalwinder commented on components/scream/src/physics/shoc/shoc_isotropic_ts_impl.hpp
> +  //Declate constants as Spacks to use ekat's min and max functions
This should be looked at carefully. I declared them as Spacks as I wanted to use ekat's min and max functions. I can modify the code if there is a better way to do it.

2020-11-25 02:43 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-25 02:43 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-11-25 02:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 720</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 708</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 259</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: singhbalwinder/shoc/isotrpoic_ts_port_1</li>
    <li>SHA: 7026273df4eca83ce8ad208296e73781ffecceae</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: singhbalwinder
</details>

2020-11-25 03:33 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 720</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 708</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 259</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>7026273df4eca83ce8ad208296e73781ffecceae</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 720</b> (click to expand)
</summary>
<pre>
<code>
35/66 Test #29: p3_tests_ut_np1_omp6 ..............   Passed    3.30 sec
      Start 31: p3_tests_ut_np1_omp8
36/66 Test #30: p3_tests_ut_np1_omp7 ..............   Passed    3.09 sec
      Start 48: shoc_tests_ut_np1_omp6
37/66 Test #48: shoc_tests_ut_np1_omp6 ............   Passed    1.04 sec
      Start 49: shoc_tests_ut_np1_omp7
38/66 Test #31: p3_tests_ut_np1_omp8 ..............   Passed    3.13 sec
      Start 32: p3_tests_ut_np1_omp9
39/66 Test #49: shoc_tests_ut_np1_omp7 ............   Passed    1.03 sec
40/66 Test #32: p3_tests_ut_np1_omp9 ..............   Passed    3.13 sec
      Start 17: physics_tests_ut_np1_omp10
41/66 Test #17: physics_tests_ut_np1_omp10 ........   Passed    0.33 sec
      Start 18: physics_tests_ut_np1_omp11
42/66 Test #18: physics_tests_ut_np1_omp11 ........   Passed    0.32 sec
      Start 19: physics_tests_ut_np1_omp12
43/66 Test #19: physics_tests_ut_np1_omp12 ........   Passed    0.32 sec
      Start 20: physics_tests_ut_np1_omp13
44/66 Test #20: physics_tests_ut_np1_omp13 ........   Passed    0.30 sec
      Start 21: physics_tests_ut_np1_omp14
45/66 Test #21: physics_tests_ut_np1_omp14 ........   Passed    0.32 sec
      Start 22: physics_tests_ut_np1_omp15
46/66 Test #22: physics_tests_ut_np1_omp15 ........   Passed    0.32 sec
      Start 23: physics_tests_ut_np1_omp16
47/66 Test #23: physics_tests_ut_np1_omp16 ........   Passed    0.33 sec
      Start 33: p3_tests_ut_np1_omp10
48/66 Test #33: p3_tests_ut_np1_omp10 .............   Passed    3.10 sec
      Start 34: p3_tests_ut_np1_omp11
49/66 Test #34: p3_tests_ut_np1_omp11 .............   Passed    3.11 sec
      Start 35: p3_tests_ut_np1_omp12
50/66 Test #35: p3_tests_ut_np1_omp12 .............   Passed    3.12 sec
      Start 36: p3_tests_ut_np1_omp13
51/66 Test #36: p3_tests_ut_np1_omp13 .............   Passed    3.09 sec
      Start 37: p3_tests_ut_np1_omp14
52/66 Test #37: p3_tests_ut_np1_omp14 .............   Passed    3.08 sec
      Start 38: p3_tests_ut_np1_omp15
53/66 Test #38: p3_tests_ut_np1_omp15 .............   Passed    3.05 sec
      Start 39: p3_tests_ut_np1_omp16
54/66 Test #39: p3_tests_ut_np1_omp16 .............   Passed    3.11 sec
      Start 40: p3_run_and_cmp_cxx_ut_np1_omp16
55/66 Test #40: p3_run_and_cmp_cxx_ut_np1_omp16 ...   Passed    2.33 sec
      Start 41: p3_run_and_cmp_f90_ut_np1_omp16
56/66 Test #41: p3_run_and_cmp_f90_ut_np1_omp16 ...   Passed    0.13 sec
      Start 50: shoc_tests_ut_np1_omp8
57/66 Test #50: shoc_tests_ut_np1_omp8 ............   Passed    0.97 sec
      Start 51: shoc_tests_ut_np1_omp9
58/66 Test #51: shoc_tests_ut_np1_omp9 ............   Passed    0.97 sec
      Start 52: shoc_tests_ut_np1_omp10
59/66 Test #52: shoc_tests_ut_np1_omp10 ...........   Passed    0.98 sec
      Start 53: shoc_tests_ut_np1_omp11
60/66 Test #53: shoc_tests_ut_np1_omp11 ...........   Passed    1.01 sec
      Start 54: shoc_tests_ut_np1_omp12
61/66 Test #54: shoc_tests_ut_np1_omp12 ...........   Passed    0.98 sec
      Start 55: shoc_tests_ut_np1_omp13
62/66 Test #55: shoc_tests_ut_np1_omp13 ...........   Passed    1.00 sec
      Start 56: shoc_tests_ut_np1_omp14
63/66 Test #56: shoc_tests_ut_np1_omp14 ...........   Passed    0.95 sec
      Start 57: shoc_tests_ut_np1_omp15
64/66 Test #57: shoc_tests_ut_np1_omp15 ...........   Passed    0.98 sec
      Start 58: shoc_tests_ut_np1_omp16
65/66 Test #58: shoc_tests_ut_np1_omp16 ...........   Passed    0.99 sec
      Start 59: shoc_run_and_cmp_ut_np1_omp16
66/66 Test #59: shoc_run_and_cmp_ut_np1_omp16 .....   Passed    0.72 sec

100% tests passed, 0 tests failed out of 66

Label Time Summary:
             = 762.85 sec*proc (59 tests)
 driver      =   0.96 sec*proc (2 tests)
 dynamics    =   1.74 sec*proc (1 test)
 p3          =  15.09 sec*proc (2 tests)
 rrtmgp      =   0.38 sec*proc (1 test)
 zm          =   0.44 sec*proc (1 test)
driver       =   1.74 sec*proc (1 test)
physics      =  15.91 sec*proc (4 tests)
shoc         =   7.54 sec*proc (1 test)

Total Test time (real) =  58.89 sec
===============================================================================
Testing '72282333770f4270c491fa1fbdb6cbff07cc62bc' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 16-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=16 CTEST_PARALLEL_LEVEL=16 ctest -V --outp [...]

2020-11-25 07:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-25 07:41 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-11-25 07:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 721</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 709</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 260</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: singhbalwinder/shoc/isotrpoic_ts_port_1</li>
    <li>SHA: 567a877a65a9274b1519b2b5debbee875acf4883</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: singhbalwinder
</details>

2020-11-25 09:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 721</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 709</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 260</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>567a877a65a9274b1519b2b5debbee875acf4883</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>d168511924390617a79e854a2c1909a94455da4d</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-11-25 09:01 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2020-11-25 09:01 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-11-25 17:53 UTC, jeff-cohere approved these changes

2020-11-25 18:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-25 18:38 UTC, jgfouca requested changes
Please do an upstream merge. I've marked the places that will need to change when you do it.

2020-11-25 18:38 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_isotropic_ts_impl.hpp
> +  static constexpr Scalar lambda_low   = sp(0.001);
These's sp's aren't necessary.

2020-11-25 18:38 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_tke_isotropic_ts_tests.cpp
> +    SHOCIsotropicData f90_data[] = {
This struct has been regenerated with a new name, so so minor changes will be needed here.

2020-11-25 18:38 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_tke_isotropic_ts_tests.cpp
> +      isotropic_ts_f(d.nlev(), d.shcol(), d.brunt_int, d.tke, d.a_diss, d.brunt, d.isotropy);
nlev, shcol are no longer methods.

2020-11-25 18:38 UTC, jgfouca commented on components/scream/src/physics/shoc/tests/shoc_tke_isotropic_ts_tests.cpp
> +      for (Int k = 0; k < d_f90.total1x2(); ++k) {
use `d_f90.total(isotropy)`

2020-11-25 19:38 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-25 20:53 UTC, xyuan approved these changes
It sounds good to me if Jame's suggestion is addressed.

2020-11-26 00:09 UTC, singhbalwinder commented
Thank you all! I have all the review comments.

2020-11-26 00:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-26 00:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-11-26 00:53 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-26 02:10 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-26 02:52 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-26 09:25 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-26 10:08 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-26 19:44 UTC, jgfouca approved these changes

2020-11-30 16:25 UTC, tcclevenger approved these changes

2020-12-01 02:37 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-12-01 02:37 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2020-12-01 05:39 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-12-01 05:39 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-12-01 05:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 732</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 720</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 271</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: singhbalwinder/shoc/isotrpoic_ts_port_1</li>
    <li>SHA: 452e75072ead0a54981b5aec0f33557a71f16c0b</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: singhbalwinder
</details>

2020-12-01 06:29 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 732</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 720</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 271</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>760</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>singhbalwinder/shoc/isotrpoic_ts_port_1</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>452e75072ead0a54981b5aec0f33557a71f16c0b</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-12-01 06:29 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2020-12-01 06:29 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-01 16:44 UTC, tcclevenger approved these changes

2020-12-01 16:45 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ tcclevenger ]!

2020-12-01 16:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2020-12-01 16:46 UTC, merged

2020-12-01 16:46 UTC, E3SM-Autotester commented
Merge on Pull Request# 760: IS A SUCCESS - Pull Request successfully merged