porting pblintd_init function
E3SM-Project/scream pull request #762
Opened 2020-11-25 22:58 UTC by xyuan

porting pblintd_init function

[BFB]

2020-11-25 23:24 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-25 23:24 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-11-26 00:08 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-26 00:54 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-26 01:40 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SCREAM_PullRequest_Autotester_Blake to start: Total Wait = 1803
- Other jobs have been previously started - We must stop them...

2020-11-30 18:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-30 18:28 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 722</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 710</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 261</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: xyuan/init</li>
    <li>SHA: e73d55d5506c126117efa4aea0c0301b431b7783</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: xyuan
</details>

2020-11-30 19:14 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 722</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 710</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 261</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 722</b> (click to expand)
</summary>
<pre>
<code>
61/66 Test #54: shoc_tests_ut_np1_omp12 ...........   Passed    1.06 sec
      Start 55: shoc_tests_ut_np1_omp13
62/66 Test #55: shoc_tests_ut_np1_omp13 ...........   Passed    1.06 sec
      Start 56: shoc_tests_ut_np1_omp14
55/66 Test #39: p3_tests_ut_np1_omp16 .............   Passed    3.17 sec
      Start 40: p3_run_and_cmp_cxx_ut_np1_omp16
63/66 Test #56: shoc_tests_ut_np1_omp14 ...........   Passed    1.06 sec
      Start 57: shoc_tests_ut_np1_omp15
64/66 Test #57: shoc_tests_ut_np1_omp15 ...........   Passed    1.05 sec
      Start 58: shoc_tests_ut_np1_omp16
56/66 Test #40: p3_run_and_cmp_cxx_ut_np1_omp16 ...   Passed    2.33 sec
      Start 41: p3_run_and_cmp_f90_ut_np1_omp16
57/66 Test #41: p3_run_and_cmp_f90_ut_np1_omp16 ...   Passed    0.14 sec
      Start 51: shoc_tests_ut_np1_omp9
65/66 Test #58: shoc_tests_ut_np1_omp16 ...........   Passed    1.06 sec
      Start 59: shoc_run_and_cmp_ut_np1_omp16
58/66 Test #51: shoc_tests_ut_np1_omp9 ............   Passed    1.11 sec
      Start 52: shoc_tests_ut_np1_omp10
66/66 Test #59: shoc_run_and_cmp_ut_np1_omp16 .....   Passed    0.67 sec

98% tests passed, 1 tests failed out of 66

Label Time Summary:
             = 905.34 sec*proc (59 tests)
 driver      =   0.91 sec*proc (2 tests)
 dynamics    =   1.82 sec*proc (1 test)
 p3          =  15.00 sec*proc (2 tests)
 rrtmgp      =   0.32 sec*proc (1 test)
 zm          =   0.44 sec*proc (1 test)
driver       =   1.82 sec*proc (1 test)
physics      =  15.77 sec*proc (4 tests)
shoc         =   7.42 sec*proc (1 test)

Total Test time (real) =  69.41 sec

The following tests FAILED:
	 28 - p3_tests_ut_np1_omp5 (Failed)
CMake Error at /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/722/scream/components/scream/cmake/ctest_script.cmake:62 (message):
  Test had fails


59/66 Test #52: shoc_tests_ut_np1_omp10 ...........   Passed    1.04 sec
      Start 53: shoc_tests_ut_np1_omp11
60/66 Test #53: shoc_tests_ut_np1_omp11 ...........   Passed    1.04 sec
      Start 54: shoc_tests_ut_np1_omp12
61/66 Test #54: shoc_tests_ut_np1_omp12 ...........   Passed    1.05 sec
      Start 55: shoc_tests_ut_np1_omp13
62/66 Test #55: shoc_tests_ut_np1_omp13 ...........   Passed    1.04 sec
      Start 56: shoc_tests_ut_np1_omp14
63/66 Test #56: shoc_tests_ut_np1_omp14 ...........   Passed    1.05 sec
      Start 57: shoc_tests_ut_np1_omp15
64/66 Test #57: shoc_tests_ut_np1_omp15 ...........   Passed    1.07 sec
      Start 58: shoc_tests_ut_np1_omp16
65/66 Test #58: shoc_tests_ut_np1_omp16 ...........   Passed    1.03 sec
      Start 59: shoc_run_and_cmp_ut_np1_omp16
66/66 Test #59: shoc_run_and_cmp_ut_np1_omp16 .....   Passed    0.70 sec

100% tests passed, 0 tests failed out of 66

Label Time Summary:
             = 782.53 sec*proc (59 tests)
 driver      =   1.02 sec*proc (2 tests)
 dynamics    =   1.70 sec*proc (1 test)
 p3          =  15.07 sec*proc (2 tests)
 rrtmgp      =   0.33 sec*proc (1 test)
 zm          =   0.47 sec*proc (1 test)
driver       =   1.70 sec*proc (1 test)
physics      =  15.88 sec*proc (4 tests)
shoc         =   7.45 sec*proc (1 test)

Total Test time (real) =  60.62 sec
===============================================================================
Testing 'e84e1f788f19e34bbb2cfcccc10f5c6f31beeafe' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 16-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=16 CTEST_PARALLEL_LEVEL=16 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/722/scream/components/scream/ctest-build/full_sp_debug/ctest_resource_file.json -DNO_SUBMIT=True -DBUILD_WORK_DIR=/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/722/scream/components/scream/ctest-build/full_sp_debug -S /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/722/scream/components/scream/cmake/ctest_script.cmake -DCMAKE_COMMAND="-C /home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/722/scream/components/scream/cmake/machine-files/blake.cmake -DCMAKE_BUILD_TYPE=Debug -DSCREAM_DOUBLE_PRECISION=False -DEKAT_DEFAULT_BFB=True -DEKAT_DISABLE_TPL_WARNINGS='ON' -DCMAKE_CXX_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicxx -DCMAKE_C_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.5/intel/19.1.144/bin/mpicc -DCMAKE_Fortran_COMPILER=/home/projects/x86-64-skylake/openmpi/2.1.5/intel/19. [...]

2020-11-30 21:00 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-30 21:02 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 725</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 713</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 264</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: xyuan/init</li>
    <li>SHA: e73d55d5506c126117efa4aea0c0301b431b7783</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: xyuan
</details>

2020-11-30 21:44 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 725</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 713</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 264</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>e73d55d5506c126117efa4aea0c0301b431b7783</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>4d70b2d1430d8bde29d2631db256596bd7b89253</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 725</b> (click to expand)
</summary>
<pre>
<code>
[ 69%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/mass_matrix_mod.F90.o
/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/mesh_mod.F90(1767): warning #6178: The return value of this FUNCTION has not been defined.   [NEDGE]
  function MeshCubeEdgeCount()  result(nedge)
---------------------------------------^
/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/mesh_mod.F90(1783): warning #6178: The return value of this FUNCTION has not been defined.   [NELEM]
  function MeshCubeElemCount()  result(nelem)
---------------------------------------^
[ 69%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/global_norms_mod.F90.o
[ 69%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/interpolate_mod.F90.o
[ 70%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/checksum_mod.F90.o
[ 70%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/global_norms_mod.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/viscosity_base.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/theta-l/share/viscosity_theta.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/dof_mod.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/mass_matrix_mod.F90.o
[ 72%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/test_src/dcmip12_wrapper.F90.o
[ 72%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/cg_mod.F90.o
[ 72%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/prim_si_mod.F90.o
[ 72%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/surfaces_mod.F90.o
[ 72%] Building Fortran object tests/scream_homme_dyn_ut_nlev72_qsize4/CMakeFiles/theta-l_kokkos_4_72_35.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/test_src/asp_tests.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/test_src/dcmip12_wrapper.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/cg_mod.F90.o
[ 72%] Building Fortran object src/dynamics/homme/tests/CMakeFiles/theta-l_kokkos_4_72_4.dir/home/e3sm-jenkins/blake/workspace/SCREAM_PullRequest_Autotester_Blake/725/scream/components/homme/src/share/prim_si_mod.F90.o
[ 73%] Buildin [...]

2020-11-30 22:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-11-30 22:23 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2020-12-01 02:37 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-12-01 02:37 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-12-01 02:41 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 729</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 717</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 268</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: xyuan/init</li>
    <li>SHA: ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: xyuan
</details>

2020-12-01 03:27 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 729</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 717</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 268</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>ec11d0d3d0e4039076d5b47e1998c75e26a37e0a</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>67f1363e0b1b449b2e178348870f1c0e00e9cc24</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-12-01 03:27 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

2020-12-01 03:28 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-01 14:44 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2020-12-01 14:44 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-01 17:58 UTC, jeff-cohere approved these changes
Looks good.

2020-12-01 18:31 UTC, jgfouca requested changes
Minor changes needed to _f.

2020-12-01 18:31 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_functions_f90.cpp
> +  ekat::device_to_host<int, 1>({rino}, {shcol}, {nlev}, out_2d_views, true);
You don't need to use the API that takes vectors of sizes if they are all the same.

2020-12-01 18:31 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_functions_f90.cpp
> +  ekat::device_to_host<int, 1>({pblh}, {shcol}, out_1d_views);
Same as above.

2020-12-01 18:31 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_functions_f90.cpp
> +  Kokkos::deep_copy(host_check_d, check_d);
device_to_host now works for bools so you should use that instead. In fact, I think it has always works for 1d data.

2020-12-01 20:27 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2020-12-01 20:27 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-02 20:41 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-03 21:10 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-04 21:42 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-05 22:10 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-06 22:40 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-07 03:40 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2020-12-08 04:49 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2020-12-08 21:10 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-12-08 21:12 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 801</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 789</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 340</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: xyuan/init</li>
    <li>SHA: 3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: xyuan
</details>

2020-12-08 21:32 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 801</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 789</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 340</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 801</b> (click to expand)
</summary>
<pre>
<code>
++ PATH=/ascldap/users/jgfouca/packages/Python-3.6.8-blake/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/ascldap/users/e3sm-jenkins/.local/bin:/ascldap/users/e3sm-jenkins/bin
++ source ./scream/components/scream/scripts/jenkins/sandia_son_proxy
+++ export http_proxy=http://sonproxy.sandia.gov:80
+++ http_proxy=http://sonproxy.sandia.gov:80
+++ export RSYNC_PROXY=sonproxy.sandia.gov:80
+++ RSYNC_PROXY=sonproxy.sandia.gov:80
+++ export rsync_proxy=sonproxy.sandia.gov:80
+++ rsync_proxy=sonproxy.sandia.gov:80
+++ export HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ HTTPS_PROXY=http://sonproxy.sandia.gov:80
+++ export https_proxy=http://sonproxy.sandia.gov:80
+++ https_proxy=http://sonproxy.sandia.gov:80
+++ export HTTP_PROXY=http://sonproxy.sandia.gov:80
+++ HTTP_PROXY=http://sonproxy.sandia.gov:80
++ SCREAM_MACHINE=blake
+ git config --global user.email jenkins@ignore.com
+ git config --global user.name 'Jenkins Jenkins'
+ SUBMIT=--submit
+ '[' -n 762 ']'
+ SUBMIT=
+ BASELINES_DIR=AUTO
+ ./scream/components/scream/scripts/gather-all-data './scripts/test-all-scream --baseline-dir AUTO $compiler -c EKAT_DISABLE_TPL_WARNINGS=ON -p -i -m $machine ' -l -m blake
salloc: Granted job allocation 1003441
Last commit on ref '3eb5076b0bb30a3eb2a6b1fde255dd986437a5ed': 3eb5076 Merge branch 'master' into xyuan/init
Merge of 'origin/master' not necessary. Current HEAD is already ahead.
Baselines expired. Rebuilding them.
Using commit origin/master to generate baselines
Note: no value passed for --ctest-parallel-level. Using the default for this machine: 48
Note: no value passed for --make-parallel-level. Using the default for this machine: 48
test dbg can use 16 jobs to compile, and 16 jobs for testing
test sp can use 16 jobs to compile, and 16 jobs for testing
test fpe can use 16 jobs to compile, and 16 jobs for testing
###############################################################################
Generating baselines for ref origin/master
###############################################################################
Switched to 'origin/master' (9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956)
Last commit on ref 'origin/master': 9c2bb13 Merge Pull Request #783 from E3SM-Project/scream/bogensch/SHOC_PBLH_proptests
FATAL: command execution failed
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2872)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3367)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: java.io.IOException: Backing channel 'blake' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:216)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:286)
	at com.sun.proxy.$Proxy69.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1211)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1203)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:194)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:144)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
FATAL: Unable to delete script file /tmp/jenkins78598 [...]

2020-12-08 23:16 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2020-12-08 23:16 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2020-12-08 23:21 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 804</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 792</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 343</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: xyuan/init</li>
    <li>SHA: a64671e704fcfd70e712e618bffd81ba8ee0365c</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: xyuan
</details>

2020-12-09 00:07 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 804</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 792</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 343</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST;B4B;shoc</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>762</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>xyuan/init</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>a64671e704fcfd70e712e618bffd81ba8ee0365c</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>9c2bb133d7bbf01d50e253c3d4ff8b47ec4a4956</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2020-12-09 00:07 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2020-12-09 00:07 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2020-12-09 19:01 UTC, jgfouca commented on components/scream/src/physics/shoc/shoc_functions_f90.cpp
> +  Kokkos::deep_copy(host_check_d, check_d);
I was wrong, device_to_host expects packed data.

2020-12-09 19:02 UTC, jgfouca approved these changes

2020-12-09 19:11 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jgfouca ]!

2020-12-09 19:11 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2020-12-09 19:11 UTC, merged

2020-12-09 19:11 UTC, E3SM-Autotester commented
Merge on Pull Request# 762: IS A SUCCESS - Pull Request successfully merged