Quick fix to a build error where the variable "thrd" was not defined in the bfb_math.inc file
E3SM-Project/scream pull request #854
Opened 2021-01-06 14:26 UTC by AaronDonahue

Fixes a build error that occurs when building scream through CIME related to a variable not being properly
defined in the bfb_math.inc file.

[BFB]

2021-01-06 14:40 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-01-06 14:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 933</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 921</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 467</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/bfb_cbrt_bugfix_20200106</li>
    <li>SHA: 9f7f932b5da969addaa160a2d4ff015fbe0f6f67</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2021-01-06 15:09 UTC, tcclevenger approved these changes

2021-01-06 17:46 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 933</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 921</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 467</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : SCREAM_PullRequest_Autotester_Blake # 933</b> (click to expand)
</summary>
<pre>
<code>
42/74 Test #24: physics_tests_ut_np1_omp9 .........   Passed    0.28 sec
      Start 25: physics_tests_ut_np1_omp10
43/74 Test #38: p3_tests_ut_np1_omp6 ..............   Passed    3.22 sec
      Start 57: shoc_tests_ut_np1_omp6
44/74 Test #25: physics_tests_ut_np1_omp10 ........   Passed    0.27 sec
      Start 39: p3_tests_ut_np1_omp7
45/74 Test #57: shoc_tests_ut_np1_omp6 ............   Passed    1.63 sec
      Start 40: p3_tests_ut_np1_omp8
46/74 Test #39: p3_tests_ut_np1_omp7 ..............   Passed    3.00 sec
      Start 58: shoc_tests_ut_np1_omp7
47/74 Test #40: p3_tests_ut_np1_omp8 ..............   Passed    3.01 sec
      Start 41: p3_tests_ut_np1_omp9
48/74 Test #58: shoc_tests_ut_np1_omp7 ............   Passed    1.61 sec
49/74 Test #41: p3_tests_ut_np1_omp9 ..............   Passed    3.02 sec
      Start 26: physics_tests_ut_np1_omp11
50/74 Test #26: physics_tests_ut_np1_omp11 ........   Passed    0.28 sec
      Start 27: physics_tests_ut_np1_omp12
51/74 Test #27: physics_tests_ut_np1_omp12 ........   Passed    0.28 sec
      Start 28: physics_tests_ut_np1_omp13
52/74 Test #28: physics_tests_ut_np1_omp13 ........   Passed    0.28 sec
      Start 29: physics_tests_ut_np1_omp14
53/74 Test #29: physics_tests_ut_np1_omp14 ........   Passed    0.28 sec
      Start 30: physics_tests_ut_np1_omp15
54/74 Test #30: physics_tests_ut_np1_omp15 ........   Passed    0.28 sec
      Start 31: physics_tests_ut_np1_omp16
55/74 Test #31: physics_tests_ut_np1_omp16 ........   Passed    0.28 sec
      Start 42: p3_tests_ut_np1_omp10
56/74 Test #42: p3_tests_ut_np1_omp10 .............   Passed    3.10 sec
      Start 43: p3_tests_ut_np1_omp11
57/74 Test #43: p3_tests_ut_np1_omp11 .............   Passed    3.09 sec
      Start 44: p3_tests_ut_np1_omp12
58/74 Test #44: p3_tests_ut_np1_omp12 .............   Passed    3.09 sec
      Start 45: p3_tests_ut_np1_omp13
59/74 Test #45: p3_tests_ut_np1_omp13 .............   Passed    3.09 sec
      Start 46: p3_tests_ut_np1_omp14
60/74 Test #46: p3_tests_ut_np1_omp14 .............   Passed    3.09 sec
      Start 47: p3_tests_ut_np1_omp15
61/74 Test #47: p3_tests_ut_np1_omp15 .............   Passed    3.13 sec
      Start 48: p3_tests_ut_np1_omp16
62/74 Test #48: p3_tests_ut_np1_omp16 .............   Passed    3.02 sec
      Start 49: p3_run_and_cmp_cxx_ut_np1_omp16
63/74 Test #49: p3_run_and_cmp_cxx_ut_np1_omp16 ...   Passed    2.33 sec
      Start 50: p3_run_and_cmp_f90_ut_np1_omp16
64/74 Test #50: p3_run_and_cmp_f90_ut_np1_omp16 ...   Passed    0.15 sec
      Start 59: shoc_tests_ut_np1_omp8
65/74 Test #59: shoc_tests_ut_np1_omp8 ............   Passed    1.61 sec
      Start 60: shoc_tests_ut_np1_omp9
66/74 Test #60: shoc_tests_ut_np1_omp9 ............   Passed    1.62 sec
      Start 61: shoc_tests_ut_np1_omp10
67/74 Test #61: shoc_tests_ut_np1_omp10 ...........   Passed    1.61 sec
      Start 62: shoc_tests_ut_np1_omp11
68/74 Test #62: shoc_tests_ut_np1_omp11 ...........   Passed    1.62 sec
      Start 63: shoc_tests_ut_np1_omp12
69/74 Test #63: shoc_tests_ut_np1_omp12 ...........   Passed    1.61 sec
      Start 64: shoc_tests_ut_np1_omp13
70/74 Test #64: shoc_tests_ut_np1_omp13 ...........   Passed    1.61 sec
      Start 65: shoc_tests_ut_np1_omp14
71/74 Test #65: shoc_tests_ut_np1_omp14 ...........   Passed    1.58 sec
      Start 66: shoc_tests_ut_np1_omp15
72/74 Test #66: shoc_tests_ut_np1_omp15 ...........   Passed    1.58 sec
      Start 67: shoc_tests_ut_np1_omp16
73/74 Test #67: shoc_tests_ut_np1_omp16 ...........   Passed    1.58 sec
      Start 68: shoc_run_and_cmp_ut_np1_omp16
74/74 Test #68: shoc_run_and_cmp_ut_np1_omp16 .....   Passed    0.95 sec

100% tests passed, 0 tests failed out of 74

Label Time Summary:
driver      =   7.20 sec*proc (2 tests)
dynamics    =   6.72 sec*proc (1 test)
p3          =  14.66 sec*proc (2 tests)
physics     =  15.53 sec*proc (4 tests)
rrtmgp      =   0.38 sec*proc (1 test)
shoc        =   7.27 sec*proc (1 test)
zm          =   0.48 sec*proc (1 test)

Total Test time (real) =  64.46 sec
===============================================================================
Testing '9f7f932b5da969addaa160a2d4ff015fbe0f6f67' for test 'full_sp_debug'
===============================================================================
RUN: taskset -c 16-31 sh -c 'SCREAM_BUILD_PARALLEL_LEVEL=16 CTEST_PARALLEL_LEVEL=16 ctest -V --output-on-failure --resource-spec-file /home/e3sm-jenkins/ [...]

2021-01-06 18:40 UTC, ambrad requested changes
I think the explicit type is needed, like this: `(1.0_real_kind/3.0_real_kind)`

2021-01-06 21:58 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 934</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 922</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 468</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/bfb_cbrt_bugfix_20200106</li>
    <li>SHA: 9f7f932b5da969addaa160a2d4ff015fbe0f6f67</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2021-01-06 22:17 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 934</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 922</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 468</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>9f7f932b5da969addaa160a2d4ff015fbe0f6f67</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2021-01-06 22:17 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2021-01-06 22:17 UTC, E3SM-Autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-01-07 14:57 UTC, AaronDonahue commented
@ambrad , yes, thank you for the review.  I went about implementing the requested chage, but this brings up a few questions:
1. "real_kind" doesn't work because that is undefined where it used.  However "rtype" does.  So presumably we should use that.
2.  However, "rtype" just happens to be the variable name used by the three F90 codes that use bfb_math.inc.  In the future, if for any reason we use bfb_math.inc with a different code, that defines real_kind as "r8" for example (as is the case for a big chunk of EAM) we will run into compiler errors which can be a pain to fix.
3. Alternatively, we could simply always use double precision, i.e. 1.0d0/3.0d0.  I'm guessing that this will result in a minor hit to performance when using single precision for everything else.  But maybe that is acceptable (?)

4. Last question, somewhat tangential.  In bfb_math.inc there is also the defined function: 
                              #  define bfb_expm1(val) (exp(val) - 1)
Here we are relying on the compiler casting the "1" as the same type as "val".  Is this safe, or should we be giving the same treatment, i.e 1._rtype or 1.0d0?

2021-01-07 17:14 UTC, AaronDonahue commented
Update: Sorry for what seems like free-floating consciousness...

A simpler approach is to just define `thrd` in `shoc.F90`.  Up until now we've only been using cbrt with P3 which has `thrd` explicitly defined in the proper precision.  We can add that to shoc and be done with it.

This of course means that `thrd` needs to be explicitly defined by every module that uses bfb_math.inc.  Which means there is room for a bug, but given that soon we will switch to C++ only and that it's not likely that `thrd` will be defined in a way other than 1/3 it might be the best approach here. (?)

2021-01-07 19:34 UTC, ambrad commented
A bare 1 is fine. Main thing is to get 0.3333... to full precision. Since this is for the F90 code only, not for BFB tests, 1.0d0/3.0d0 is fine.

2021-01-07 19:35 UTC, AaronDonahue commented
@ambrad , excellent.  Thanks for responding.  I'll push the d0 change.

2021-01-07 19:59 UTC, ambrad approved these changes

2021-01-07 20:11 UTC, E3SM-Autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-01-07 20:20 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 935</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 923</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 469</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: SCREAM (E3SM-Project/scream)</dt>
  <ul>
    <li>Branch: aarondonahue/bfb_cbrt_bugfix_20200106</li>
    <li>SHA: 77622d6c5e5f71d90de422472425cdb0594d457d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: AaronDonahue
</details>

2021-01-07 20:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Blake</h3>
<ul>
  <li>Build Num: 935</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Weaver</h3>
<ul>
  <li>Build Num: 923</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: SCREAM_PullRequest_Autotester_Mappy</h3>
<ul>
  <li>Build Num: 469</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;B4B;bugfix</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>854</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_BRANCH</td>
    <td>aarondonahue/bfb_cbrt_bugfix_20200106</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_SOURCE_SHA</td>
    <td>77622d6c5e5f71d90de422472425cdb0594d457d</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_REPO</td>
    <td>https://github.com/E3SM-Project/scream</td>
  </tr>

  <tr>
    <td>SCREAM_TARGET_SHA</td>
    <td>7646dc22e5b82200552d91d991b934323233bd30</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>SCREAM</td>
  </tr>
</table>
</details>

2021-01-07 20:45 UTC, E3SM-Autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ ambrad ]!

2021-01-07 20:45 UTC, E3SM-Autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2021-01-07 20:45 UTC, merged

2021-01-07 20:45 UTC, E3SM-Autotester commented
Merge on Pull Request# 854: IS A SUCCESS - Pull Request successfully merged